In [1]:
!pip install openai

Collecting openai
  Downloading openai-2.37.0-py3-none-any.whl.metadata (31 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from openai) (4.12.1)
Collecting distro<2,>=1.7.0 (from openai)
  Using cached distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from openai) (0.28.1)
Collecting jiter<1,>=0.10.0 (from openai)
  Downloading jiter-0.15.0-cp310-cp310-win_amd64.whl.metadata (5.3 kB)
Collecting pydantic<3,>=1.9.0 (from openai)
  Downloading pydantic-2.13.4-py3-none-any.whl.metadata (109 kB)
Requirement already satisfied: sniffio in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from openai) (4.15.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from anyio<5,>=3.5.0->openai) (1.3.0)
Requirement already satisfied: idna>=2.8 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: certifi in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from httpx<1,>=0.23.0->openai) (2026.1.4)
Requirement already satisfied: httpcore==1.* in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Collecting annotated-types>=0.6.0 (from pydantic<3,>=1.9.0->openai)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.4 (from pydantic<3,>=1.9.0->openai)
  Downloading pydantic_core-2.46.4-cp310-cp310-win_amd64.whl.metadata (6.7 kB)
Collecting typing-inspection>=0.4.2 (from pydantic<3,>=1.9.0->openai)
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: colorama in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from tqdm>4->openai) (0.4.6)
Downloading openai-2.37.0-py3-none-any.whl (1.3 MB)
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 1.3/1.3 MB 22.2 MB/s  0:00:00
Using cached distro-1.9.0-py3-none-any.whl (20 kB)
Downloading jiter-0.15.0-cp310-cp310-win_amd64.whl (200 kB)
Downloading pydantic-2.13.4-py3-none-any.whl (472 kB)
Downloading pydantic_core-2.46.4-cp310-cp310-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 38.6 MB/s  0:00:00
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Using cached typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Installing collected packages: typing-inspection, pydantic-core, jiter, distro, annotated-types, pydantic, openai

   ---------------------------- ----------- 5/7 [pydantic]
   ---------------------------- ----------- 5/7 [pydantic]
   ---------------------------- ----------- 5/7 [pydantic]
   ---------------------------- ----------- 5/7 [pydantic]
   ---------------------------------- ----- 6/7 [openai]
   ---------------------------------- ----- 6/7 [openai]
   ---------------------------------- ----- 6/7 [openai]
   ---------------------------------- ----- 6/7 [openai]
   ---------------------------------- ----- 6/7 [openai]
   ---------------------------------- ----- 6/7 [openai]
   ---------------------------------- ----- 6/7 [openai]
   ---------------------------------- ----- 6/7 [openai]
   ---------------------------------- ----- 6/7 [openai]
   ---------------------------------- ----- 6/7 [openai]
   ---------------------------------- ----- 6/7 [openai]
   ---------------------------------- ----- 6/7 [openai]
   ---------------------------------- ----- 6/7 [openai]
   ---------------------------------- ----- 6/7 [openai]
   ---------------------------------- ----- 6/7 [openai]
   ---------------------------------- ----- 6/7 [openai]
   ---------------------------------- ----- 6/7 [openai]
   ---------------------------------- ----- 6/7 [openai]
   ---------------------------------- ----- 6/7 [openai]
   ---------------------------------------- 7/7 [openai]

Successfully installed annotated-types-0.7.0 distro-1.9.0 jiter-0.15.0 openai-2.37.0 pydantic-2.13.4 pydantic-core-2.46.4 typing-inspection-0.4.2

In [2]:
!pip install datasets evaluate -qU

In [3]:
!pip install -U datasets huggingface_hub fsspec

Requirement already satisfied: datasets in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (4.8.5)
Requirement already satisfied: huggingface_hub in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (0.36.0)
Collecting huggingface_hub
  Downloading huggingface_hub-1.15.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: fsspec in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (2024.9.0)
Collecting fsspec
  Downloading fsspec-2026.4.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: filelock in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from datasets) (3.20.0)
Requirement already satisfied: numpy>=1.17 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=21.0.0 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from datasets) (22.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from datasets) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from datasets) (2.32.5)
Requirement already satisfied: httpx<1.0.0 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from datasets) (0.70.16)
  Downloading fsspec-2026.2.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: packaging in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from datasets) (6.0.3)
Collecting hf-xet<2.0.0,>=1.4.3 (from huggingface_hub)
  Downloading hf_xet-1.5.0-cp37-abi3-win_amd64.whl.metadata (4.9 kB)
Collecting typer>=0.20.0 (from huggingface_hub)
  Downloading typer-0.25.1-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: anyio in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from httpx<1.0.0->datasets) (4.12.1)
Requirement already satisfied: certifi in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from httpx<1.0.0->datasets) (2026.1.4)
Requirement already satisfied: httpcore==1.* in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: async-timeout<6.0,>=4.0 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (5.0.1)
Requirement already satisfied: attrs>=17.3.0 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from requests>=2.32.2->datasets) (2.6.3)
Requirement already satisfied: colorama in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Requirement already satisfied: click>=8.2.1 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from typer>=0.20.0->huggingface_hub) (8.3.1)
Collecting shellingham>=1.3.0 (from typer>=0.20.0->huggingface_hub)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=13.8.0 (from typer>=0.20.0->huggingface_hub)
  Downloading rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer>=0.20.0->huggingface_hub)
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=13.8.0->typer>=0.20.0->huggingface_hub)
  Downloading markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from rich>=13.8.0->typer>=0.20.0->huggingface_hub) (2.19.2)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=13.8.0->typer>=0.20.0->huggingface_hub)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from anyio->httpx<1.0.0->datasets) (1.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\alexander\anaconda3\envs\naics-classifier\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading huggingface_hub-1.15.0-py3-none-any.whl (663 kB)
   ---------------------------------------- 0.0/663.6 kB ? eta -:--:--
   ---------------------------------------- 663.6/663.6 kB 25.1 MB/s  0:00:00
Downloading fsspec-2026.2.0-py3-none-any.whl (202 kB)
Downloading hf_xet-1.5.0-cp37-abi3-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 4.0/4.0 MB 26.5 MB/s  0:00:00
Downloading typer-0.25.1-py3-none-any.whl (58 kB)
Using cached annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Downloading rich-15.0.0-py3-none-any.whl (310 kB)
Downloading markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Installing collected packages: shellingham, mdurl, hf-xet, fsspec, annotated-doc, markdown-it-py, rich, typer, huggingface_hub

  Attempting uninstall: hf-xet

    Found existing installation: hf-xet 1.4.0

    Uninstalling hf-xet-1.4.0:

      Successfully uninstalled hf-xet-1.4.0

  Attempting uninstall: fsspec

    Found existing installation: fsspec 2024.9.0

    Uninstalling fsspec-2024.9.0:

      Successfully uninstalled fsspec-2024.9.0

   ------------- -------------------------- 3/9 [fsspec]
   ------------- -------------------------- 3/9 [fsspec]
   ---------------------- ----------------- 5/9 [markdown-it-py]
   -------------------------- ------------- 6/9 [rich]
   -------------------------- ------------- 6/9 [rich]
   ------------------------------- -------- 7/9 [typer]
  Attempting uninstall: huggingface_hub
   ------------------------------- -------- 7/9 [typer]
    Found existing installation: huggingface-hub 0.36.0
   ------------------------------- -------- 7/9 [typer]
    Uninstalling huggingface-hub-0.36.0:
   ------------------------------- -------- 7/9 [typer]
   ----------------------------------- ---- 8/9 [huggingface_hub]
      Successfully uninstalled huggingface-hub-0.36.0
   ----------------------------------- ---- 8/9 [huggingface_hub]
   ----------------------------------- ---- 8/9 [huggingface_hub]
   ----------------------------------- ---- 8/9 [huggingface_hub]
   ----------------------------------- ---- 8/9 [huggingface_hub]
   ----------------------------------- ---- 8/9 [huggingface_hub]
   ---------------------------------------- 9/9 [huggingface_hub]

Successfully installed annotated-doc-0.0.4 fsspec-2026.2.0 hf-xet-1.5.0 huggingface_hub-1.15.0 markdown-it-py-4.2.0 mdurl-0.1.2 rich-15.0.0 shellingham-1.5.4 typer-0.25.1

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tokenizers 0.21.4 requires huggingface-hub<1.0,>=0.16.4, but you have huggingface-hub 1.15.0 which is incompatible.
transformers 4.48.0.dev0 requires huggingface-hub<1.0,>=0.24.0, but you have huggingface-hub 1.15.0 which is incompatible.

# Fine-tuning Language Models

Many APIs give us the capability of fine-tuning their models to make for results that better fit our goals. The following are some examples of what fine-tuning can achieve:
* Setting a specific style, tone, or format in the answers
* Following complex prompts that might be difficult to follow
* Performing tasks that might be difficult to articulate in natural language for a prompt

Basically, fine-tuning gives us a more specialized model, which is specially useful when the base model is a very powerful multi-purpose one, like GPT-3.5 and GPT-4. For this class, we will be finetuning GPT-3.5 through OpenAI's fine-tuning endpoint. However, other APIs give us the opportunity to fine-tune their pre-trained models in a similar way. Currently, for example, OpenAI does not allow for fine-tuning embedding models, but HuggingFace and LLaMa do. To learn more, you can access the following resources:
* [HuggingFace](https://huggingface.co/blog/how-to-train-sentence-transformers)
* [LLaMa](https://docs.llamaindex.ai/en/stable/optimizing/fine-tuning/fine-tuning.html)
* [OpenAI](https://platform.openai.com/docs/guides/fine-tuning)

**Important**: for the latter examples, it is better to use a GPU runtime for this Notebook, as otherwise the model training would take too long.

## Fine-tuning OpenAI models

Now let's start with the examples. First, some setup:

In [2]:
from sklearn.datasets import fetch_20newsgroups
from pprint import pprint
from openai import OpenAI
import json
import getpass
import pandas as pd
import requests
from io import BytesIO

api_key = getpass.getpass(prompt="Insert your OPENAI - API-KEY: ")
client = OpenAI(api_key=api_key)

For our first example, we will be using the 20 newsgroups dataset from the `sklearn` package. It is comprised of more than 18000 newsgroup posts on 20 topics, and is split in training and testing. We will only be using the training subset and will split it ourselves for validation and testing later. We would like to tune a model that specializes in classifying whether a post is related to the autos or the motorcycles topics. We will only be using these two topics, but we could extend this application to the 20 topics the dataset contains; specially since we have a very large amount of data.

In [5]:
categories = ["rec.autos", "rec.motorcycles"]
data = fetch_20newsgroups(subset="train", categories=categories)

In [6]:
data

{'data': ['From: gregl@zimmer.CSUFresno.EDU (Greg Lewis)\nSubject: Re: WARNING.....(please read)...\nKeywords: BRICK, TRUCK, DANGER\nNntp-Posting-Host: zimmer.csufresno.edu\nOrganization: CSU Fresno\nLines: 33\n\nIn article <1qh336INNfl5@CS.UTK.EDU> larose@austin.cs.utk.edu (Brian LaRose) writes:\n>This just a warning to EVERYBODY on the net.  Watch out for\n>folks standing NEXT to the road or on overpasses.   They can\n>cause SERIOUS HARM to you and your car.  \n>\n>(just a cliff-notes version of my story follows)\n>\n>10pm last night, I was travelling on the interstate here in\n>knoxville,  I was taking an offramp exit to another interstate\n>and my wife suddenly screamed and something LARGE hit the side\n>of my truck.  We slowed down, but after looking back to see the\n>vandals standing there, we drove on to the police station.\n>\n>She did get a good look at the guy and saw him "cock his arm" with\n>something the size of a cinderblock, BUT I never saw him. We are \n>VERY lucky the truck sits up high on the road; if it would have hit\n>her window, it would have killed her. \n>\n>The police are looking for the guy, but in all likelyhood he is gone. \nStuff deleted...\n\nI am sorry to report that in Southern California it was a sick sport\nfor a while to drop concrete blocks from the overpasses onto the\nfreeway.  Several persons were killed when said blocks came through\ntheir windshields.  Many overpass bridges are now fenced, and they\nhave made it illegal to loiter on such bridges (as if that would stop\nsuch people).  Yet many bridges are NOT fenced.  I always look up at a\nbridge while I still have time to take evasive action even though this\n*sport* has not reached us here in Fresno.\n___________________________________________________________________\nGreg_Lewis@csufresno.edu\nPhotojournalism sequence, Department of Journalism\nCSU Fresno, Fresno, CA 93740\n',
  'From: cjackson@adobe.com (Curtis Jackson)\nSubject: Tracing license plates of BDI cagers?\nArticle-I.D.: adobe.1993Apr6.184204.26184\nOrganization: Adobe Systems Incorporated, Mountain View\nLines: 24\n\nThis morning a truck that had been within my sight (and I within\nhis) for about 3 miles suddenly forgot that I existed and pulled\nover right on me -- my front wheel was about even with the back\nedge of his front passenger door as I was accelerating past him.\n\nIt was trivial enough for me to tap the brakes and slide behind him\nas he slewed over (with no signal, of course) on top of me, with\nmy little horn blaring (damn, I need Fiamms!), but the satisfaction\nof being aware of my surroundings and thus surviving was not enough,\nespecially when I later pulled up alongside the bastard and he made\nno apologetic wave or anything.\n\nIs there some way that I can memorize the license plate of an\noffending vehicle and get the name and address of the owner?\nI\'m not going to firebomb houses or anything, I\'d just like to\nwrite a consciousness-raising letter or two. I think that it would\nbe good for BDI cagers to know that We Know Where They Live.\nMaybe they\'d use 4 or 5 brain cells while driving instead of the\nusual 3.\n-- \nCurtis Jackson\t   cjackson@mv.us.adobe.com\t\'91 Hawk GT\t\'81 Maxim 650\nDoD#0721 KotB  \'91 Black Lab mix "Studley Doright"  \'92 Collie/Golden "George"\n"There is no justification for taking away individuals\' freedom\n in the guise of public safety." -- Thomas Jefferson\n',
  "From: Clarke@bdrc.bd.com (Richard Clarke)\nSubject: Countersteering sans Hands\nOrganization: Becton Dickinson Research Center R.T.P. NC USA\nLines: 7\nNntp-Posting-Host: polymr4.bdrc.bd.com\n\nSo how do I steer when my hands aren't on the bars? (Open Budweiser in left \nhand, Camel cigarette in the right, no feet allowed.) If I lean, and the \nbike turns, am I countersteering? Is countersteering like benchracing only \nwith a taller seat, so your feet aren't on the floor?\n\n-Rick\n\n",
  "From: zorro@picasso.ocis.temple.edu (John Grabowski)\nSubject: Re: Taurus/Sable rotor recall\nOrganization: Temple University\nLines: 23\nNntp-Posting-Host: picasso.ocis.temple.edu\nX-Newsreader: TIN [version 1.1 PL9]\n\nAntonio L. Balsamo (Save the wails) (balsamo@stargl.enet.dec.com) wrote:\n\n: From: OPDBS@vm.cc.latech.edu\n: Subject: Taurus/Sable rotor recall\n\n:        My '92 Taurus GL with only 26k on the clock also has rotor warp.\n:    Apparently they HAVEN'T fixed the problem yet.  But try convincing the Ford\n:    service person to fix it for free...Right!!!\n\n:    Tony\n\n\nGads, I have heard so many horror stories with Taurus and Sable cars!  I thought\nthese were premium American automobiles.  The way they sell, you'd think so.\nIs Ford really no better than in the late '70s when it was turning out tin\ncans like the Granada and the Fairmount?  Which would you get, a Taurus or \na Camry or Accord?\n\n\nJohn\nzorro@picasso.ocis.temple.edu\nzorro@astro.ocis.temple.edu\n^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
  'From: marshatt@feserve.cc.purdue.edu (Zauberer)\nSubject: Re: WARNING.....(please read)...\nOrganization: Purdue University\nDistribution: usa\nLines: 5\n\n sorry about that last post, my server neglected to send the message:\n\n Can we please keep this group to AUTOMOTIVE topics. Thank you.\n\n\n',
  'From: MJMUISE@1302.watstar.uwaterloo.ca (Mike Muise)\nSubject: Re: Drinking and Riding\nLines: 19\nOrganization: Waterloo Engineering\n\nIn article <C4wKBp.B9w@eskimo.com>, maven@eskimo.com (Norman Hamer) writes:\n>  What is a general rule of thumb for sobriety and cycling? Couple hours \n> after you "feel" sober? What? Or should I just work with "If I drink \n> tonight, I don\'t ride until tomorrow"?\n\n1 hr/drink for the first 4 drinks.\n1.5 hours/drink for the next 6 drinks.\n2 hours/drink for the rest.\n\nThese are fairly cautious guidelines, and will work even if you happen to \nhave a low tolerance or body mass.\nI think the cops and "Don\'t You Dare Drink & Drive" (tm) commercials will \nusually say 1hr/drink in general, but after about 5 drinks and 5 hrs, you \ncould very well be over the legal limit. \nWatch yourself.\n-Mike\n  ________________________________________________\n / Mike Muise / mjmuise@1302.watstar.uwaterloo.ca \\ no quotes, no jokes,\n \\ Electrical Engineering, University of Waterloo / no disclaimer, no fear.\n',
  "From: lynn@pacesetter.com (Lynn E. Hall)\nSubject: Re: story \nKeywords: PARTY!!!!\nNntp-Posting-Host: camellia\nOrganization: Siemens Pacesetter, Inc.\nLines: 20\n\n>lynn@pacesetter.com (Lynn E. Hall) writes:\n>\n>>allowed (yes, there is a God). No open containers on the street was the\n>>signs in the bars. Yeah, RIGHT! The 20 or so cops on hand for the couple of\n>>thousand of bikers in a 1 block main street were not citing anyone. The\n>>street was filled with empty cans at least 2 feet deep in the gutter. The\n>>crowd was raisin' hell - tittie shows everywhere. Can you say PARTY?\n>\n>\n>And still we wonder why they stereotype us...\n>\n>-Erc.\n\n Whacha mean 'we'...ifin they (whom ever 'they' are) want to stereotype me\nas one that likes to drink beer and watch lovely ladies display their\nbeautiful bodies - I like that stereotype.\n  If you were refering 'stereotype' to infer a negative - you noticed we\ndidn't rape, pillage, or burn down the town. We also left mucho bucks as in\nMONEY with the town. Me thinks the town LIKES us. Least they said so.\n                         Lynn Hall - NOS Bros\n",
  'From: qazi@csd4.csd.uwm.edu (Aamir Hafeez Qazi)\nSubject: Re: Difference between Lexus 300 series?\nArticle-I.D.: uwm.1pr5f8INN4om\nReply-To: qazi@csd4.csd.uwm.edu\nOrganization: University of Wisconsin - Milwaukee\nLines: 18\nNNTP-Posting-Host: 129.89.7.4\nOriginator: qazi@csd4.csd.uwm.edu\n\nFrom article <1993Apr5.200048.23421@ucsu.Colorado.EDU>, by lorenzo@rintintin.Colorado.EDU (Eric Lorenzo):\n> \tWhat is the difference between the LS300, ES300 and GS300?  Seems\n> Lexus can\'t stop popping out new models.\n\n--Let me put it like this.  The only similarity between the three models\n  is the "300", or 3-liter engine displacement.  Actually, the SC300 (the\n  coupe) and the GS300 (the funky-looking new sedan) share the same 3.0\n  liter inline-six, and the ES300 (popular small sedan) uses 3.0 V6 shared\n  with the Camry.  The SC300 is a luxury/sports coupe, the GS300 is the new\n  luxury sedan, and the ES300 is the base executive sedan.  All three look\n  completely different.\n\n--Aamir Qazi\n-- \n\nAamir Qazi\nqazi@csd4.csd.uwm.edu\n--Why should I care?  I\'d rather watch drying paint.\n',
  'From: ravi@merlin.dev.cdx.mot.com (Ravi Puvvala)\nSubject: $13,500 Mazda 626 DX (with Air, AM/FM) Good Deal?\nNntp-Posting-Host: elvis.dev.cdx.mot.com\nReply-To: ravi@merlin.dev.cdx.mot.com (Ravi Puvvala)\nOrganization: Motorola Codex\nLines: 12\n\nHi Netters\n\tI want to know if 13500 (w/o tax) is a good deal for 1993 Mazda 626 DX\nHow is the performance review so far on Mazda 626. Is it a good buy?\nPlease reply to me as I don\'t read this group often.\n\nThanks In advance\nRavi\n--\nRavi Kiran Puvvala\t\t| "The purpose of education is not merely, \nravi@merlin.dev.cdx.mot.com\t|  the assimilation of facts but blow all \nMotorola Codex, Boston  MA \t|  the money" - Ravi Puvvala\n----------------------------------------------------------------------------\n',
  'From: azw@aber.ac.uk (Andy Woodward)\nSubject: Re: Its still cold, but...\nOrganization: University College of Wales, Aberystwyth\nLines: 13\nNntp-Posting-Host: 144.124.112.30\n\n\n>> \n>> One thing is certain, though, its still too cold.  After about 40\n>> minutes, I had to stop and hold my muffler for a while.  \n\nBe VERY careful about this. If youre really cold the muffler will\nfeel fine till you leave all the charred skin on it when you peel\nyour hands off - I speak from experience. You can also do all \nkindsa (Americanism of the day) damage to your circulation warming \nhands up on something too hot. By far the best (fastest and safest)\nway to do it is to shove the hands up the opposit sleeves and\nstand there like a Ming emporer for a while. Five minutes should \ndo it.\n',
  "From: stlucas@gdwest.gd.com (Joseph St. Lucas)\nSubject: Re: Dumbest automotive concepts of all time\nOrganization: General Dynamics Corp.\nDistribution: usa\nLines: 10\n\nDon't have a list of what's been said before, so hopefully not repeating.\n\nHow about horizontally mounted oil filters (like on my Ford) that, no\nmatter how hard you try, will spill out their half quart on the bottom\nof the car when you change them?\n\n-- \nJoe St.Lucas    stlucas@gdwest.gd.com        Standard Disclaimers Apply\nGeneral Dynamics Space Systems, San Diego\nWork is something to keep me busy between Ultimate Frisbee games.\n",
  'From: jchen@wind.bellcore.com (Jason Chen)\nSubject: Re: No-Haggle Deals...Save $$???\nNntp-Posting-Host: wind.bellcore.com\nReply-To: jchen@ctt.bellcore.com\nOrganization: Bell Communications Research\nDistribution: usa\nLines: 2\n\nA local dealer is advertising "No negotiation necessary!"\nMake you wonder...\n',
  "From: nrmendel@unix.amherst.edu (Nathaniel Mendell)\nSubject: Re: Bike advice\nOrganization: Amherst College\nX-Newsreader: TIN [version 1.1 PL7]\nLines: 11\n\n\nUmmm...did you have any bikes other than that KX80? If not, I'd suggest you \nlook for an '89 ZX-7, since they only have about 90 horsepower, whereas the\n'90 has over 100 and might be a bit much for you...\n\nSincerely,\nNathaniel\n\nZX-10 \nDoD 0812\nAMA\n",
  "From: music@erich.triumf.ca (FRED W. BACH)\nSubject: Re: WARNING.....(please read)...\nOrganization: TRIUMF: Tri-University Meson Facility\nLines: 33\nDistribution: world\nNNTP-Posting-Host: erich.triumf.ca\nKeywords: BRICK, TRUCK, DANGER\nNews-Software: VAX/VMS VNEWS 1.41    \n\nIn article <C5JoIt.E31@bcstec.ca.boeing.com>, neil@bcstec.ca.boeing.com\n (Neil Williams) writes...\n\n# \n#As long as we're on the subject... Several years ago myself and two others\n#were riding in the front of a Toyota pickup heading south on Interstate 5\n#north of Seattle, WA. Someone threw a rock of an overpass and hit our\n#windshield. Not by accident I'm sure, it was impossible to get up to the\n#overpass quickly to see who did it. We figured it was kids, reported it and\n#left.\n#A couple of years ago it happend again and killed a guy at my company. He was\n#in his mid-fourties and left behind a wife and children. Turned out there was\n#a reformatory for juviniles a few blocks away. They caught the 14 year old\n#that did it. They put a cover over the overpass, what else could they do?\n#I don't think I'll over forget this story.\n#Neil Williams, Boeing Computer Services, Bellevue WA.\n#..\n# \n\n  Neil, what did they do to the 14-year-old who they caught?  What did\n the man's insurance company do?  This could be significant and in any case\n very interesting.\n\n  Followups to alt.parents-teens.\n\n\n Fred W. Bach ,    Operations Group        |  Internet: music@erich.triumf.ca\n TRIUMF (TRI-University Meson Facility)    |  Voice:  604-222-1047 loc 327/278\n 4004 WESBROOK MALL, UBC CAMPUS            |  FAX:    604-222-1074\n University of British Columbia, Vancouver, B.C., CANADA   V6T 2A3\n\n These are my opinions, which should ONLY make you read, think, and question.\n They do NOT necessarily reflect the views of my employer or fellow workers.\n",
  'From: essbaum@rchland.vnet.ibm.com (Alexander Essbaum)\nSubject: Re: Speeding ticket from CHP\nDisclaimer: This posting represents the poster\'s views, not necessarily those of IBM\nNntp-Posting-Host: florida.rchland.ibm.com\nOrganization: IBM Rochester\nLines: 37\n\nIn article <dmatejkaC51DMB.LH6@netcom.com>, dmatejka@netcom.com (Daniel Matejka) writes:\n|> In article <1pq4t7$k5i@agate.berkeley.edu> downey@homer.CS.Berkeley.EDU (Allen B. Downey) writes:\n|> >       Fight your ticket : California edition by David Brown 1st ed.\n|> >       Berkeley, CA : Nolo Press, 1982\n|> >\n|> >The second edition is out (but not in UCB\'s library).  Good luck; let\n|> >us know how it goes.\n|> >\n|>   Daniel Matejka writes:\n\n|>   Can you beat this ticket?  Personally, I think it\'s your Duty As a Citizen\n|> to make it as much trouble as possible for them, so maybe they\'ll Give Up\n|> and Leave Us Alone Someday Soon.\n|>   The cop was certainly within his legal rights to nail you by guessing\n|> your speed.  Mr. Brown (the author of Fight Your Ticket) mentions an\n|> Oakland judge who convicted a speeder "on the officer\'s testimony that\n|> the driver\'s car sounded like it was being driven at an excessive speed."\n\n*cough* *choke*  WHAT?!?  if a cop gave me a ticket for "sounding" like\ni was speeding i\'d probably show up in court without a lawyer simply\nbecause "sounding" like speeding is ridiculous.  if i was found guilty\ni\'d appeal and then show up with a lawyer.\n\nif a cop doesn\'t do one of:\n\nVASCAR (from car or plane)\nRADAR, LIDAR, other electronic speed measuring device\npace me\n\nand i\'m within 15mph or so of the limit i\'d go to court.  i can accept a\ncop "seeing" me going excessively fast (like 25+ over the limit) but\n"he looked like he was going 70 or so in a 55 zone" is not "beyond a\nreasonable doubt".  granted i may well lose the case but 70 in a 55 measured\nby eye???  take it to court for sure.\n\naxel\n\n',
  "From: ryan_cousineau@compdyn.questor.org (Ryan Cousineau) \nSubject: Re: Bat-helmet.\nReply-To: ryan_cousineau@compdyn.questor.org (Ryan Cousineau) \nDistribution: world\nOrganization: Computer Dynamics-Vancouver B.C.-(604)986-9937 (604)255-9937\nLines: 49\n\nCBD>From: Christopher Bradley Devlin <cd1i+@andrew.cmu.edu>\n\nCBD>>but it's nothing compared to the (ahem) unique helmet\nCBD>>design seen in the new Animated Series: it has a huge opening for his\nCBD>>mouth, topped by the world's tiniest eyeslits above the enormous mouth\nCBD>>opening. Batman's helmet probably cuts you down to about 12 degrees of\nCBD>>unrestricted vision. With a helmet like this, he might just be better\nCBD>>off with the leather cap/mask thingy.\n\nCBD>C'mon, Batman doesn't need to SEE.  He's Batman.\n\nCBD>Did you notice he only takes the bike out in the snow or rain?\n\nSo let's see what we have on the Batdude so far: He has a weird helmet.\nHe drags his knee in corners (thanks, Cookson, but how does he do it?\nHidden Bat-pucks?), and he only takes the bike out in the snow or rain.\nAlso, he lets Robin ride! I think I could have used a Bat-mom. Would\nhave made getting my license a lot easier!\n\nThere's a trend here: Stylish helmet, Stylish knee-dragging, rides only\nin Stylish cartoon precipitation. Hmm . . . Could it be that we're\ndealing with a veritable airborne mammalian poseur? Dare I say it, a\nBAT-SQUID?? (huh? Bat-Squid?) It all adds up now . . .\n\nLet's make the B-man an honorary DoD DuDe. All he needs is a DoD\nsticker.\n\nActually, anyone have an address for Batman's current artists, both\ncomic book and animated series? We'll write and ask if Batman would like\nto become an honorary Denizen! Yeah!\n\nSpecial To The KoTL: Is there a precedent for inducting an imaginary\nmember with an imaginary motorcycle? Having seen the computers in the\nBat-Cave, I think we can safely assume that he also has imaginary\nInternet access.\n\nRyan Cousinetc.|1982 Yamaha Vision XZ550 -Black Pig of Inverness|Live to Ride\nKotRB          |1958 AJS 500 C/S -King Rat                      |to Work to\nDoD# 0863      |I'd be a squid if I could afford the bike...    |Flame to\nryan.cousineau@compdyn.questor.org  |   Vancouver, BC, Canada   |Live . . .\n\n\n * SLMR 2.1a * My (virtual) reality check just bounced.\n                              \n----\n+===============================================================+\n|COMPUTER DYNAMICS BBS    604-255-9937(HST)    604-986-9937(V32)|\n|Vancouver, BC, Canada -  Easy Access, Low Rates, Friendly Sysop|\n+===============================================================+\n",
  "From: brother@mrcnext.cso.uiuc.edu (Jesse McCabe)\nSubject: There's rust on my Beamer! Help!\nOrganization: University of Illinois at Urbana\nLines: 16\n\nActually I wasn't too surprised, since I bought it with the rust.  Any of you \ngot some ideas of getting rid of this CHEAPLY (key word)??  It has eaten all \nthe\nway through on the door panels.  Can I use Bondo?  \n \nAlso, is there a good paint that will bond to Aluminum rims?  The paint thati\nwas on my rims has peeled off, actually, there's some rust looking 'stuff' on\nthe rims themselves...  but it comes off pretty easily.  \n \nOne more thing...\nHave any of you done self-painting to a car?  How do you start?  What do I need\nto do this?\n \nPlease help me!\nJesse\n\n",
  'From: bclarke@galaxy.gov.bc.ca\nSubject: How to buy a first bike, etc.\nOrganization: BC Systems Corporation\nLines: 8\n\nThere have been a *lot* of posts lately about "I wanna buy my first bike - is a\nGSXR/ZX/CBR/FZR a good bike to learn on?" etc.\n\nI think I\'m going to put together a FAQ on buying a new bike. Ravi used to post\none all the time.\n-- \nBruce Clarke       B.C. Environment\n                   e-mail: bclarke@galaxy.gov.bc.ca\n',

Our data now contains two categories: "rec.autos" and "rec.motorcycles". They are one-hot-encoded to 0 for autos and 1 for motorcycles

In [7]:
pprint(list(data.target_names))

['rec.autos', 'rec.motorcycles']

In [8]:
data.target[:10]

array([0, 1, 1, 0, 0, 1, 1, 0, 0, 1], dtype=int64)

Let's take a look at a post.

In [9]:
print(data.data[5])

From: MJMUISE@1302.watstar.uwaterloo.ca (Mike Muise)
Subject: Re: Drinking and Riding
Lines: 19
Organization: Waterloo Engineering

In article <C4wKBp.B9w@eskimo.com>, maven@eskimo.com (Norman Hamer) writes:
>  What is a general rule of thumb for sobriety and cycling? Couple hours
> after you "feel" sober? What? Or should I just work with "If I drink
> tonight, I don't ride until tomorrow"?

1 hr/drink for the first 4 drinks.
1.5 hours/drink for the next 6 drinks.
2 hours/drink for the rest.

These are fairly cautious guidelines, and will work even if you happen to
have a low tolerance or body mass.
I think the cops and "Don't You Dare Drink & Drive" (tm) commercials will
usually say 1hr/drink in general, but after about 5 drinks and 5 hrs, you
could very well be over the legal limit.
Watch yourself.
-Mike
  ________________________________________________
 / Mike Muise / mjmuise@1302.watstar.uwaterloo.ca \ no quotes, no jokes,
 \ Electrical Engineering, University of Waterloo / no disclaimer, no fear.

Now that we have a better understand of how our data looks, we can get started with building the training and validation sets.

In [10]:
train_posts = data.data[:10]
train_targets = [categories[target] for target in data.target[:10]]
validation_posts = data.data[10:20]
validation_targets = [categories[target] for target in data.target[10:20]]

The OpenAI fine-tuning endpoint works by feeding examples of message chains, each with a system prompt, a user query, and an ideal response to the query.
We will use a one-shot prompt for our example. It is recommended to first try several iterations of prompts to get the best posible results before fine-tuning, and proceed with fine-tuning when we would like to see further improvements.

In [11]:
DELIMITER = "####"

system_prompt = f"""
You are a helpful assistant that will classify posts from a newsgroup.
You will be provided with the post and you must classify it with one of two \
tags.

rec.autos
rec.motorcycles

The message will be delimited by {DELIMITER} characters.

Only output the classification, as in the following example

{DELIMITER}From: MJMUISE@1302.watstar.uwaterloo.ca (Mike Muise)
Subject: Re: Drinking and Riding
Lines: 19
Organization: Waterloo Engineering

In article <C4wKBp.B9w@eskimo.com>, maven@eskimo.com (Norman Hamer) writes:
>  What is a general rule of thumb for sobriety and cycling? Couple hours
> after you "feel" sober? What? Or should I just work with "If I drink
> tonight, I don't ride until tomorrow"?

1 hr/drink for the first 4 drinks.
1.5 hours/drink for the next 6 drinks.
2 hours/drink for the rest.

These are fairly cautious guidelines, and will work even if you happen to
have a low tolerance or body mass.
I think the cops and "Don't You Dare Drink & Drive" (tm) commercials will
usually say 1hr/drink in general, but after about 5 drinks and 5 hrs, you
could very well be over the legal limit.
Watch yourself.
-Mike
  ________________________________________________
 / Mike Muise / mjmuise@1302.watstar.uwaterloo.ca \ no quotes, no jokes,
 \ Electrical Engineering, University of Waterloo / no disclaimer, no fear.{DELIMITER}

 rec.motorcycles
"""

We build a two lists, each with the training and validation message chain examples

In [12]:
for post, target in zip(train_posts, train_targets):
  print(post, target)

From: gregl@zimmer.CSUFresno.EDU (Greg Lewis)
Subject: Re: WARNING.....(please read)...
Keywords: BRICK, TRUCK, DANGER
Nntp-Posting-Host: zimmer.csufresno.edu
Organization: CSU Fresno
Lines: 33

In article <1qh336INNfl5@CS.UTK.EDU> larose@austin.cs.utk.edu (Brian LaRose) writes:
>This just a warning to EVERYBODY on the net.  Watch out for
>folks standing NEXT to the road or on overpasses.   They can
>cause SERIOUS HARM to you and your car.
>
>(just a cliff-notes version of my story follows)
>
>10pm last night, I was travelling on the interstate here in
>knoxville,  I was taking an offramp exit to another interstate
>and my wife suddenly screamed and something LARGE hit the side
>of my truck.  We slowed down, but after looking back to see the
>vandals standing there, we drove on to the police station.
>
>She did get a good look at the guy and saw him "cock his arm" with
>something the size of a cinderblock, BUT I never saw him. We are
>VERY lucky the truck sits up high on the road; if it would have hit
>her window, it would have killed her.
>
>The police are looking for the guy, but in all likelyhood he is gone.
Stuff deleted...

I am sorry to report that in Southern California it was a sick sport
for a while to drop concrete blocks from the overpasses onto the
freeway.  Several persons were killed when said blocks came through
their windshields.  Many overpass bridges are now fenced, and they
have made it illegal to loiter on such bridges (as if that would stop
such people).  Yet many bridges are NOT fenced.  I always look up at a
bridge while I still have time to take evasive action even though this
*sport* has not reached us here in Fresno.
___________________________________________________________________
Greg_Lewis@csufresno.edu
Photojournalism sequence, Department of Journalism
CSU Fresno, Fresno, CA 93740
 rec.autos
From: cjackson@adobe.com (Curtis Jackson)
Subject: Tracing license plates of BDI cagers?
Article-I.D.: adobe.1993Apr6.184204.26184
Organization: Adobe Systems Incorporated, Mountain View
Lines: 24

This morning a truck that had been within my sight (and I within
his) for about 3 miles suddenly forgot that I existed and pulled
over right on me -- my front wheel was about even with the back
edge of his front passenger door as I was accelerating past him.

It was trivial enough for me to tap the brakes and slide behind him
as he slewed over (with no signal, of course) on top of me, with
my little horn blaring (damn, I need Fiamms!), but the satisfaction
of being aware of my surroundings and thus surviving was not enough,
especially when I later pulled up alongside the bastard and he made
no apologetic wave or anything.

Is there some way that I can memorize the license plate of an
offending vehicle and get the name and address of the owner?
I'm not going to firebomb houses or anything, I'd just like to
write a consciousness-raising letter or two. I think that it would
be good for BDI cagers to know that We Know Where They Live.
Maybe they'd use 4 or 5 brain cells while driving instead of the
usual 3.
--
Curtis Jackson	   cjackson@mv.us.adobe.com	'91 Hawk GT	'81 Maxim 650
DoD#0721 KotB  '91 Black Lab mix "Studley Doright"  '92 Collie/Golden "George"
"There is no justification for taking away individuals' freedom
 in the guise of public safety." -- Thomas Jefferson
 rec.motorcycles
From: Clarke@bdrc.bd.com (Richard Clarke)
Subject: Countersteering sans Hands
Organization: Becton Dickinson Research Center R.T.P. NC USA
Lines: 7
Nntp-Posting-Host: polymr4.bdrc.bd.com

So how do I steer when my hands aren't on the bars? (Open Budweiser in left
hand, Camel cigarette in the right, no feet allowed.) If I lean, and the
bike turns, am I countersteering? Is countersteering like benchracing only
with a taller seat, so your feet aren't on the floor?

-Rick

 rec.motorcycles
From: zorro@picasso.ocis.temple.edu (John Grabowski)
Subject: Re: Taurus/Sable rotor recall
Organization: Temple University
Lines: 23
Nntp-Posting-Host: picasso.ocis.temple.edu
X-Newsreader: TIN [version 1.1 PL9]

Antonio L. Balsamo (Save the wails) (balsamo@stargl.enet.dec.com) wrote:

: From: OPDBS@vm.cc.latech.edu
: Subject: Taurus/Sable rotor recall

:        My '92 Taurus GL with only 26k on the clock also has rotor warp.
:    Apparently they HAVEN'T fixed the problem yet.  But try convincing the Ford
:    service person to fix it for free...Right!!!

:    Tony


Gads, I have heard so many horror stories with Taurus and Sable cars!  I thought
these were premium American automobiles.  The way they sell, you'd think so.
Is Ford really no better than in the late '70s when it was turning out tin
cans like the Granada and the Fairmount?  Which would you get, a Taurus or
a Camry or Accord?


John
zorro@picasso.ocis.temple.edu
zorro@astro.ocis.temple.edu
^^^^^^^^^^^^^^^^^^^^^^^^^^^
 rec.autos
From: marshatt@feserve.cc.purdue.edu (Zauberer)
Subject: Re: WARNING.....(please read)...
Organization: Purdue University
Distribution: usa
Lines: 5

 sorry about that last post, my server neglected to send the message:

 Can we please keep this group to AUTOMOTIVE topics. Thank you.


 rec.autos
From: MJMUISE@1302.watstar.uwaterloo.ca (Mike Muise)
Subject: Re: Drinking and Riding
Lines: 19
Organization: Waterloo Engineering

In article <C4wKBp.B9w@eskimo.com>, maven@eskimo.com (Norman Hamer) writes:
>  What is a general rule of thumb for sobriety and cycling? Couple hours
> after you "feel" sober? What? Or should I just work with "If I drink
> tonight, I don't ride until tomorrow"?

1 hr/drink for the first 4 drinks.
1.5 hours/drink for the next 6 drinks.
2 hours/drink for the rest.

These are fairly cautious guidelines, and will work even if you happen to
have a low tolerance or body mass.
I think the cops and "Don't You Dare Drink & Drive" (tm) commercials will
usually say 1hr/drink in general, but after about 5 drinks and 5 hrs, you
could very well be over the legal limit.
Watch yourself.
-Mike
  ________________________________________________
 / Mike Muise / mjmuise@1302.watstar.uwaterloo.ca \ no quotes, no jokes,
 \ Electrical Engineering, University of Waterloo / no disclaimer, no fear.
 rec.motorcycles
From: lynn@pacesetter.com (Lynn E. Hall)
Subject: Re: story
Keywords: PARTY!!!!
Nntp-Posting-Host: camellia
Organization: Siemens Pacesetter, Inc.
Lines: 20

>lynn@pacesetter.com (Lynn E. Hall) writes:
>
>>allowed (yes, there is a God). No open containers on the street was the
>>signs in the bars. Yeah, RIGHT! The 20 or so cops on hand for the couple of
>>thousand of bikers in a 1 block main street were not citing anyone. The
>>street was filled with empty cans at least 2 feet deep in the gutter. The
>>crowd was raisin' hell - tittie shows everywhere. Can you say PARTY?
>
>
>And still we wonder why they stereotype us...
>
>-Erc.

 Whacha mean 'we'...ifin they (whom ever 'they' are) want to stereotype me
as one that likes to drink beer and watch lovely ladies display their
beautiful bodies - I like that stereotype.
  If you were refering 'stereotype' to infer a negative - you noticed we
didn't rape, pillage, or burn down the town. We also left mucho bucks as in
MONEY with the town. Me thinks the town LIKES us. Least they said so.
                         Lynn Hall - NOS Bros
 rec.motorcycles
From: qazi@csd4.csd.uwm.edu (Aamir Hafeez Qazi)
Subject: Re: Difference between Lexus 300 series?
Article-I.D.: uwm.1pr5f8INN4om
Reply-To: qazi@csd4.csd.uwm.edu
Organization: University of Wisconsin - Milwaukee
Lines: 18
NNTP-Posting-Host: 129.89.7.4
Originator: qazi@csd4.csd.uwm.edu

From article <1993Apr5.200048.23421@ucsu.Colorado.EDU>, by lorenzo@rintintin.Colorado.EDU (Eric Lorenzo):
> 	What is the difference between the LS300, ES300 and GS300?  Seems
> Lexus can't stop popping out new models.

--Let me put it like this.  The only similarity between the three models
  is the "300", or 3-liter engine displacement.  Actually, the SC300 (the
  coupe) and the GS300 (the funky-looking new sedan) share the same 3.0
  liter inline-six, and the ES300 (popular small sedan) uses 3.0 V6 shared
  with the Camry.  The SC300 is a luxury/sports coupe, the GS300 is the new
  luxury sedan, and the ES300 is the base executive sedan.  All three look
  completely different.

--Aamir Qazi
--

Aamir Qazi
qazi@csd4.csd.uwm.edu
--Why should I care?  I'd rather watch drying paint.
 rec.autos
From: ravi@merlin.dev.cdx.mot.com (Ravi Puvvala)
Subject: $13,500 Mazda 626 DX (with Air, AM/FM) Good Deal?
Nntp-Posting-Host: elvis.dev.cdx.mot.com
Reply-To: ravi@merlin.dev.cdx.mot.com (Ravi Puvvala)
Organization: Motorola Codex
Lines: 12

Hi Netters
	I want to know if 13500 (w/o tax) is a good deal for 1993 Mazda 626 DX
How is the performance review so far on Mazda 626. Is it a good buy?
Please reply to me as I don't read this group often.

Thanks In advance
Ravi
--
Ravi Kiran Puvvala		| "The purpose of education is not merely,
ravi@merlin.dev.cdx.mot.com	|  the assimilation of facts but blow all
Motorola Codex, Boston  MA 	|  the money" - Ravi Puvvala
----------------------------------------------------------------------------
 rec.autos
From: azw@aber.ac.uk (Andy Woodward)
Subject: Re: Its still cold, but...
Organization: University College of Wales, Aberystwyth
Lines: 13
Nntp-Posting-Host: 144.124.112.30


>>
>> One thing is certain, though, its still too cold.  After about 40
>> minutes, I had to stop and hold my muffler for a while.

Be VERY careful about this. If youre really cold the muffler will
feel fine till you leave all the charred skin on it when you peel
your hands off - I speak from experience. You can also do all
kindsa (Americanism of the day) damage to your circulation warming
hands up on something too hot. By far the best (fastest and safest)
way to do it is to shove the hands up the opposit sleeves and
stand there like a Ming emporer for a while. Five minutes should
do it.
 rec.motorcycles

In [16]:
training_messages = [
    {"messages": [{"role": "system", "content": system_prompt},
    {"role": "user", "content": f"{DELIMITER}{post}{DELIMITER}"},
    {"role": "assistant", "content": target}]}
    for post, target in zip(train_posts, train_targets)
]

validation_messages = [
    {"messages": [{"role": "system", "content": system_prompt},
    {"role": "user", "content": f"{DELIMITER}{post}{DELIMITER}"},
    {"role": "assistant", "content": target}]}
    for post, target in zip(validation_posts, validation_targets)
]

The OpenAI fine-tuning endpoint takes its data in .jsonl format. Each example message chain is in a line, contained within a dictionary with the key `"messages"`. Let's write a function that allows us to represent each set in this format.

In [17]:
def write_jsonl(data_list: list, filename: str) -> None:
    with open(filename, "w") as out:
        for ddict in data_list:
            jout = json.dumps(ddict) + "\n"
            out.write(jout)

Now we write our files.

In [19]:
training_filename = "ng_training_data.jsonl"
validation_filename = "ng_validation_data.jsonl"

write_jsonl(training_messages, training_filename)
write_jsonl(validation_messages, validation_filename)

Now we take a look at one of our files

In [ ]:
!head -n 2 training_data.jsonl

head: cannot open 'training_data.jsonl' for reading: No such file or directory

Next, we upload our files into the Files endpoint of the OpenAI API. Once uploaded, they will be assigned an ID that we will need for fetching the files when we request for them to be used in the fine-tuning enpoint

In [ ]:
training_filename

'ng_training_data.jsonl'

In [20]:
with open(training_filename, "rb") as training_data:
    training_file_response = client.files.create(
        file=training_data,
        purpose="fine-tune"
    )

training_file_id = training_file_response.id

with open(validation_filename, "rb") as validation_data:
    validation_file_response = client.files.create(
        file=validation_data,
        purpose="fine-tune"
    )

validation_file_id = validation_file_response.id

These are our file IDs

In [22]:
validation_file_id
training_file_id

'file-MZMqYHs4FG6YZMirp2rSmY'

In [23]:
print(f"Training file ID: {training_file_id}")
print(f"Validation file ID: {validation_file_id}")

Training file ID: file-MZMqYHs4FG6YZMirp2rSmY
Validation file ID: file-XWMHo5g8YtMNFSfLv5WYdF

Now we create a fine-tuning job. It will consist in training and validating a custom model based off of the one we pass into the `model` parameter. It will automatically chose the batch size and the number of epochs for training, but we can choose them ourselves by specifying the `method` argument and specifying the type of method (supervised) and the the number of epochs

In [24]:
response = client.fine_tuning.jobs.create(
    training_file=training_file_id,
    validation_file=validation_file_id,
    model="gpt-3.5-turbo",
    suffix="newsgroup",
    method={
        "type": "supervised",
        "supervised": {"hyperparameters": {"n_epochs": 2}}
    }
)

## es un modelo supervisado, este último código es el más importante, lo anterior era limpiar la data. recomienda 10 epochs para la chamba. Con que salga chech, no significa que ya terminó, sino que está cotrabajando

This job will also be given an ID, which we will need to check the status of the training of our model.

In [30]:
job_id = response.id
print(f"The job's ID is: {response.id}")
print(f"The job's status is {response.status}")

AttributeError: 'SyncCursorPage[FineTuningJobEvent]' object has no attribute 'id'

We retrieve the model if necessary with the following code

In [28]:
response = client.fine_tuning.jobs.retrieve(job_id)

print("Job ID:", response.id)
print("Status:", response.status)
print("Trained Tokens:", response.trained_tokens)

Job ID: ftjob-JVu7pweaHi7kWNko6B5O3dfy
Status: running
Trained Tokens: None

We can fetch updates on the status of the fine-tuning job by listing the events related to it. The following cell can be ran repeatedly to acquire the updates to the status.

In [65]:
response = client.fine_tuning.jobs.list_events(job_id)

events = response.data
events.reverse()

for event in events:
    print(event.message)

Step 6/20: training loss=0.03, validation loss=0.00
Step 7/20: training loss=0.00, validation loss=0.00
Step 8/20: training loss=0.00, validation loss=0.00
Step 9/20: training loss=0.00, validation loss=0.00
Step 10/20: training loss=0.00, validation loss=0.00, full validation loss=0.00
Step 11/20: training loss=0.00, validation loss=0.00
Step 12/20: training loss=0.00, validation loss=0.26
Step 13/20: training loss=0.00, validation loss=0.00
Step 14/20: training loss=0.00, validation loss=0.00
Step 15/20: training loss=0.00, validation loss=0.00
Step 16/20: training loss=0.00, validation loss=0.00
Step 17/20: training loss=0.00, validation loss=0.00
Step 18/20: training loss=0.00, validation loss=0.00
Step 19/20: training loss=0.00, validation loss=0.00
Step 20/20: training loss=0.00, validation loss=0.00, full validation loss=0.15
Checkpoint created at step 10
New fine-tuned model created
Evaluating model against our usage policies
Moderation checks for snapshot ft:gpt-3.5-turbo-0125:pucp:newsgroup:DhEYFSga passed.
Usage policy evaluations completed, model is now enabled for sampling

In [66]:
job_info = client.fine_tuning.jobs.retrieve(job_id)
print("Status:", job_info.status)
print("Fine-tuned model:", job_info.fine_tuned_model)

Status: succeeded
Fine-tuned model: ft:gpt-3.5-turbo-0125:pucp:newsgroup:DhEYFSga

In [67]:
# Get the status of a specific fine-tuning job
job_info = client.fine_tuning.jobs.retrieve(job_id)

# Check if the job is complete
if job_info.status == "succeeded":
    print("Fine-tuning complete!")
    print(f"Fine-tuned model: {job_info.fine_tuned_model}")
elif job_info.status == "failed":
    print("Fine-tuning failed.")
    print(f"Error: {job_info.error}")
else:
    print(f"Current status: {job_info.status}")

    # If still in progress, you might want to check progress
    if hasattr(job_info, 'training_metrics'):
        print(f"Training loss: {job_info.training_metrics.training_loss}")
        if hasattr(job_info.training_metrics, 'training_accuracy'):
            print(f"Training accuracy: {job_info.training_metrics.training_accuracy}")

Fine-tuning complete!
Fine-tuned model: ft:gpt-3.5-turbo-0125:pucp:newsgroup:DhEYFSga

When it finishes, we can retrieve the name of our fine-tuned model

In [70]:
response = client.fine_tuning.jobs.retrieve(job_id)
fine_tuned_model_id = response.fine_tuned_model

if fine_tuned_model_id is None:
    raise RuntimeError("Fine-tuned model ID not found. Your job has likely not been completed yet.")

print("Fine-tuned model ID:", fine_tuned_model_id)

Fine-tuned model ID: ft:gpt-3.5-turbo-0125:pucp:newsgroup:DhEYFSga

Now let's apply our model with an out-of-sample query

In [71]:
print(data.data[54])

From: cjackson@adobe.com (Curtis Jackson)
Subject: Re: Live Free, but Quietly, or Die
Article-I.D.: adobe.1993Apr6.194913.29264
Organization: Adobe Systems Incorporated, Mountain View
Lines: 15

In article <C52nnt.J3I@dartvax.dartmouth.edu> Russell.P.Hughes@dartmouth.edu (Russell P. Hughes) writes:
}start her up and rev to about 3000 rpm....I FAIL cuz I register 120 DB,
}and the max allowed is 110! If I fail with these pipes, there are gonna

Next time make the numbers more believable -- this is poor flamebait.
120 DB is getting close to the sound of a jumbo jet engine at takeoff
revs from some small number of yards away. It is certainly right
around the pain threshold for humans. No way in hell the state permits
110 DB if they have any standard at all.

--
Curtis Jackson	   cjackson@mv.us.adobe.com	'91 Hawk GT	'81 Maxim 650
DoD#0721 KotB  '91 Black Lab mix "Studley Doright"  '92 Collie/Golden "George"
"There is no justification for taking away individuals' freedom
 in the guise of public safety." -- Thomas Jefferson

In [72]:
fine_tuned_model_id

'ft:gpt-3.5-turbo-0125:pucp:newsgroup:DhEYFSga'

In [73]:
test_messages = [
    {"role": "system", "content": system_prompt},
    {"role": "user", "content": f"{DELIMITER}{data.data[54]}{DELIMITER}"}
]

response = client.chat.completions.create(
    model=fine_tuned_model_id,
    messages=test_messages,
    temperature=0,
    max_tokens=500
)
print(response.choices[0].message.content)

rec.motorcycles

Fine-tuning is specially useful when we want a very specific behavior, like outputs in list or JSON format. In this next example, we finetune a model that returns a list of the ingredient names from cookbook recipes. We use a small sample of the [RecipeNLG dataset](https://github.com/Glorf/recipenlg). This example is based off of the OpenAI Cookbook entry on [How to fine-tune chat models](https://cookbook.openai.com/examples/how_to_finetune_chat_models) by Simón Fishman. We will be using only 10 training examples again for demonstration purposes, but 50 to 100 examples usually make for better improvements.

In [ ]:
import requests
import pandas as pd
from io import BytesIO

url = "https://raw.githubusercontent.com/RodrigoGrijalba/fine-tuning-class-data/main/recipe_data_short.csv"

data_response = requests.get(url)

data = pd.read_csv(BytesIO(data_response.content))
data = data.drop(data.columns[[0, 1]], axis=1)
data.head()

,title,ingredients,directions,link,source,NER
0,Old-Fashioned All-American Apple Pie,"[""1 recipe Thin Butter Crust"", ""6 to 8 freshly...","[""1."", ""Prepare the pie dough, divide half and...",www.epicurious.com/recipes/food/views/old-fash...,Recipes1M,"[""recipe Thin Butter"", ""apples"", ""sugar"", ""gro..."
1,Chicken and Rice Casserole,"[""1 stewed chicken, picked of meat"", ""1 (10 3/...","[""Shred chicken and add other ingredients."", ""...",www.food.com/recipe/chicken-and-rice-casserole...,Recipes1M,"[""chicken"", ""cream of chicken soup"", ""bell pep..."
2,Mediterranean Meatball Ratatouille,"[""2 tablespoons olive oil, divided"", ""1 lb bul...","[""Pour 1 tablespoon olive oil into 5-quart slo...",www.food.com/recipe/mediterranean-meatball-rat...,Gathered,"[""olive oil"", ""Italian sausage"", ""mushrooms"", ..."
3,Layered Ham And Spinach Salad,"[""16 CUPS TORN FRESH SPINACH"", ""1 TSP SUGAR. 1...","[""PLACE 2/3 OF SPINACH IN A LARGE SALAD BOWL, ...",www.epicurious.com/recipes/member/views/layere...,Gathered,"[""FRESH SPINACH"", ""SUGAR"", ""SALT"", ""EGGS"", ""HA..."
4,Rustic Glazed Carrots,"[""1 Tablespoon Unsalted Butter"", ""12 whole Sma...","[""Melt butter in a saute pan over medium heat....",tastykitchen.com/recipes/sidedishes/rustic-gla...,Gathered,"[""Butter"", ""Carrots"", ""Brown Sugar"", ""Olive Oi..."

We can create our message triples from this data, it just takes some simple functions

In [ ]:
system_prompt = """
"You are a helpful recipe assistant. You are to extract the generic ingredients from each of the recipes provided."
"""

def create_user_message(row):
    return f"""Title: {row['title']}\n\nIngredients: {row['ingredients']}\n\nGeneric ingredients: """

def prepare_example_conversation(row):
    user_message = create_user_message(row)
    assistant_message = row["NER"]
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_message},
        {"role": "assistant", "content": assistant_message}
    ]
    return {"messages": messages}

In [ ]:
training_data = data[:10].apply(prepare_example_conversation, axis=1).tolist()
validation_data = data[10:20].apply(prepare_example_conversation, axis=1).tolist()

In [ ]:
import json

def write_jsonl(data, filename):
    with open(filename, 'w', encoding='utf-8') as f:
        for item in data:
            json_line = json.dumps(item)
            f.write(json_line + '\n')

In [ ]:
training_filename = "training_recipes.jsonl"
validatin_data = "validatin_recipes.jsonl"

write_jsonl(training_data, "training_recipes.jsonl")
write_jsonl(validation_data, "validation_recipes.jsonl")

Now we take a look at our new training data

In [ ]:
!head -n 2 training_recipes.jsonl

{"messages": [{"role": "system", "content": "\n\"You are a helpful recipe assistant. You are to extract the generic ingredients from each of the recipes provided.\"\n"}, {"role": "user", "content": "Title: Old-Fashioned All-American Apple Pie\n\nIngredients: [\"1 recipe Thin Butter Crust\", \"6 to 8 freshly picked firm and slightly tart apples, such as Rhode Island Greenings, Gravensteins or Granny Smiths (about 3 pounds)\", \"granulated sugar (see Note)\", \"ground cinnamon\", \"about 3 tablespoons sifted all-purpose flour\", \"3 tablespoons butter, cut in small bits\"]\n\nGeneric ingredients: "}, {"role": "assistant", "content": "[\"recipe Thin Butter\", \"apples\", \"sugar\", \"ground cinnamon\", \"flour\", \"butter\"]"}]}
{"messages": [{"role": "system", "content": "\n\"You are a helpful recipe assistant. You are to extract the generic ingredients from each of the recipes provided.\"\n"}, {"role": "user", "content": "Title: Chicken and Rice Casserole\n\nIngredients: [\"1 stewed chicken, picked of meat\", \"1 (10 3/4 ounce) can cream of chicken soup\", \"14 cup bell pepper, chopped fine\", \"2 cups chicken broth\", \"1 cup dry rice\", \"12 cup butter, cut in slices\", \"1 chopped onion\", \"salt and pepper\"]\n\nGeneric ingredients: "}, {"role": "assistant", "content": "[\"chicken\", \"cream of chicken soup\", \"bell pepper\", \"chicken broth\", \"rice\", \"butter\", \"onion\", \"salt\"]"}]}

We proceed the same as before

In [ ]:
import openai

client = openai.OpenAI(api_key="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")

In [ ]:
# Asegúrate de definir estos nombres de archivo
training_filename = "training_recipes.jsonl"
validation_filename = "validation_recipes.jsonl"

# Subir archivo de entrenamiento
with open(training_filename, "rb") as training_data:
    training_file_response = client.files.create(
        file=training_data,
        purpose="fine-tune"
    )

training_file_id = training_file_response.id

# Subir archivo de validación
with open(validation_filename, "rb") as validation_data:
    validation_file_response = client.files.create(
        file=validation_data,
        purpose="fine-tune"
    )

validation_file_id = validation_file_response.id

In [ ]:
print(f"Training file ID: {training_file_id}")
print(f"Validation file ID: {validation_file_id}")

Training file ID: file-AeGcJu17oL5bpy2frAvDas
Validation file ID: file-6nmcfKiHEeeNJA6RK3pkqi

In [ ]:
response = client.fine_tuning.jobs.create(
    training_file=training_file_id,
    validation_file=validation_file_id,
    model="gpt-3.5-turbo",
    suffix="recipes",
    method={
        "type": "supervised",
        "supervised": {"hyperparameters": {"n_epochs": 2}}
    }
)

In [ ]:
job_id = response.id
print(f"The job's ID is: {response.id}")
print(f"The job's status is {response.status}")

The job's ID is: ftjob-DHmhDkTwKS9ynp3nUTSUJPcO
The job's status is running

In [ ]:
response = client.fine_tuning.jobs.retrieve(job_id)

print("Job ID:", response.id)
print("Status:", response.status)
print("Trained Tokens:", response.trained_tokens)

Job ID: ftjob-DHmhDkTwKS9ynp3nUTSUJPcO
Status: running
Trained Tokens: None

In [ ]:
response = client.fine_tuning.jobs.list_events(job_id)

events = response.data
events.reverse()

for event in events:
    print(event.message)

Step 4/20: training loss=1.03, validation loss=0.43
Step 5/20: training loss=0.35, validation loss=0.49
Step 6/20: training loss=0.26, validation loss=0.42
Step 7/20: training loss=0.07, validation loss=0.21
Step 8/20: training loss=1.16, validation loss=0.00
Step 9/20: training loss=0.01, validation loss=0.31
Step 10/20: training loss=0.92, validation loss=0.04, full validation loss=0.26
Step 11/20: training loss=0.19, validation loss=0.30
Step 12/20: training loss=0.05, validation loss=0.32
Step 13/20: training loss=0.17, validation loss=0.57
Step 14/20: training loss=0.00, validation loss=0.27
Step 15/20: training loss=0.23, validation loss=0.16
Step 16/20: training loss=0.21, validation loss=0.37
Step 17/20: training loss=0.55, validation loss=0.04
Step 18/20: training loss=0.31, validation loss=0.16
Step 19/20: training loss=0.61, validation loss=0.01
Step 20/20: training loss=0.02, validation loss=0.20, full validation loss=0.22
Checkpoint created at step 10
New fine-tuned model created
Evaluating model against our usage policies

In [ ]:
response = client.fine_tuning.jobs.retrieve(job_id)
fine_tuned_model_id = response.fine_tuned_model

if fine_tuned_model_id is None:
    raise RuntimeError("Fine-tuned model ID not found. Your job has likely not been completed yet.")

print("Fine-tuned model ID:", fine_tuned_model_id)

RuntimeError: Fine-tuned model ID not found. Your job has likely not been completed yet.

In [ ]:
test_messages = [
    {"role": "system", "content": system_prompt},
    {"role": "user", "content": f"{data.ingredients[24]}"}
]

In [ ]:
test_messages

[{'role': 'system',
  'content': '\n"You are a helpful recipe assistant. You are to extract the generic ingredients from each of the recipes provided."\n'},
 {'role': 'user',
  'content': '["1 (12 ounce) can low-fat cream of mushroom soup", "1 (12 ounce) can cream of chicken soup", "12 ounces skim milk", "1 small onion", "1 (4 ounce) can mushrooms (optional)", "8 ounces cheddar cheese", "12 lb green chili pepper", "15 -20 corn tortillas"]'}]

In [ ]:
response = client.chat.completions.create(
    model=fine_tuned_model_id,
    messages=test_messages,
    temperature=0,
    max_tokens=500
)
print(response.choices[0].message.content)

We can even see that, in this example, our fine-tuned model performs slightly better than the example answer contained in the data, where instead of "bittersweet chocolate", it lists "bittersweet" as an ingredient.

# Fine-tune a pretrained model from Hugging Face

In [ ]:
# Transformers installation
# ! pip install transformers datasets evaluate
# To install from source instead of the last release, comment the command above and uncomment the following one.
# ! pip install git+https://github.com/huggingface/transformers.git

## Fine-tune HuggingFace Models

There are significant benefits to using a pretrained model. It reduces computation costs, your carbon footprint, and allows you to use state-of-the-art models without having to train one from scratch. 🤗 Transformers provides access to thousands of pretrained models for a wide range of tasks. When you use a pretrained model, you train it on a dataset specific to your task. This is known as fine-tuning, an incredibly powerful training technique. In this tutorial, you will fine-tune a pretrained model with a deep learning framework of your choice:

* Fine-tune a pretrained model with 🤗 Transformers [Trainer](https://huggingface.co/docs/transformers/main/en/main_classes/trainer#transformers.Trainer).
* Fine-tune a pretrained model in TensorFlow with Keras.
* Fine-tune a pretrained model in native PyTorch.

<a id='data-processing'></a>

### Prepare a dataset

Before you can fine-tune a pretrained model, download a dataset and prepare it for training. The previous tutorial showed you how to process data for training, and now you get an opportunity to put those skills to the test!

Begin by loading the [Yelp Reviews](https://huggingface.co/datasets/yelp_review_full) dataset:

In [ ]:
from datasets import load_dataset, DatasetDict

dataset = load_dataset("yelp_review_full", split=["train[:10000]", "test[:10000]"])
dataset = DatasetDict({"train": dataset[0], "test": dataset[1]})
dataset["train"][100]

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md:   0%|          | 0.00/6.72k [00:00<?, ?B/s]

train-00000-of-00001.parquet:   0%|          | 0.00/299M [00:00<?, ?B/s]

test-00000-of-00001.parquet:   0%|          | 0.00/23.5M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/650000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/50000 [00:00<?, ? examples/s]

{'label': 0,
 'text': 'My expectations for McDonalds are t rarely high. But for one to still fail so spectacularly...that takes something special!\\nThe cashier took my friends\'s order, then promptly ignored me. I had to force myself in front of a cashier who opened his register to wait on the person BEHIND me. I waited over five minutes for a gigantic order that included precisely one kid\'s meal. After watching two people who ordered after me be handed their food, I asked where mine was. The manager started yelling at the cashiers for \\"serving off their orders\\" when they didn\'t have their food. But neither cashier was anywhere near those controls, and the manager was the one serving food to customers and clearing the boards.\\nThe manager was rude when giving me my order. She didn\'t make sure that I had everything ON MY RECEIPT, and never even had the decency to apologize that I felt I was getting poor service.\\nI\'ve eaten at various McDonalds restaurants for over 30 years. I\'ve worked at more than one location. I expect bad days, bad moods, and the occasional mistake. But I have yet to have a decent experience at this store. It will remain a place I avoid unless someone in my party needs to avoid illness from low blood sugar. Perhaps I should go back to the racially biased service of Steak n Shake instead!'}

In [ ]:
dataset

DatasetDict({
    train: Dataset({
        features: ['label', 'text'],
        num_rows: 10000
    })
    test: Dataset({
        features: ['label', 'text'],
        num_rows: 10000
    })
})

As you now know, you need a tokenizer to process the text and include a padding and truncation strategy to handle any variable sequence lengths. To process your dataset in one step, use 🤗 Datasets [`map`](https://huggingface.co/docs/datasets/process.html#map) method to apply a preprocessing function over the entire dataset:

In [ ]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")


def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True)


tokenized_datasets = dataset.map(tokenize_function, batched=True)

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

Map:   0%|          | 0/10000 [00:00<?, ? examples/s]

Map:   0%|          | 0/10000 [00:00<?, ? examples/s]

If you like, you can create a smaller subset of the full dataset to fine-tune on to reduce the time it takes:

In [ ]:
small_train_dataset = tokenized_datasets["train"].shuffle(seed=42).select(range(1000))
small_eval_dataset = tokenized_datasets["test"].shuffle(seed=42).select(range(1000))

In [ ]:
small_eval_dataset

Dataset({
    features: ['label', 'text', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 1000
})

<a id='trainer'></a>

### Train with PyTorch Trainer

🤗Transformers provides a [Trainer](https://huggingface.co/docs/transformers/main/en/main_classes/trainer#transformers.Trainer) class optimized for training 🤗 Transformers models, making it easier to start training without manually writing our own training loop. The [Trainer](https://huggingface.co/docs/transformers/main/en/main_classes/trainer#transformers.Trainer) API supports a wide range of training options and features such as logging, gradient accumulation, and mixed precision.

Start by loading our model and specify the number of expected labels. From the Yelp Review [dataset card](https://huggingface.co/datasets/yelp_review_full#data-fields), there are five labels:

In [ ]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained("bert-base-cased", num_labels=5)

model.safetensors:   0%|          | 0.00/436M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

<Tip>

You will see a warning about some of the pretrained weights not being used and some weights being randomly
initialized. Don't worry, this is completely normal! The pretrained head of the BERT model is discarded, and replaced with a randomly initialized classification head. You will fine-tune this new model head on your sequence classification task, transferring the knowledge of the pretrained model to it.

</Tip>

#### Training hyperparameters

Next, create a [TrainingArguments](https://huggingface.co/docs/transformers/main/en/main_classes/trainer#transformers.TrainingArguments) class which contains all the hyperparameters we can tune as well as flags for activating different training options. For this tutorial we can start with the default training [hyperparameters](https://huggingface.co/docs/transformers/main_classes/trainer#transformers.TrainingArguments), but feel free to experiment with these to find more optimal settings.

Specify where to save the checkpoints from our training:

In [ ]:
from transformers import TrainingArguments

training_args = TrainingArguments(output_dir="test_trainer")

#### Evaluate

[Trainer](https://huggingface.co/docs/transformers/main/en/main_classes/trainer#transformers.Trainer) does not automatically evaluate model performance during training. We'll need to pass [Trainer](https://huggingface.co/docs/transformers/main/en/main_classes/trainer#transformers.Trainer) a function to compute and report metrics. The [🤗 Evaluate](https://huggingface.co/docs/evaluate/index) library provides a simple [`accuracy`](https://huggingface.co/spaces/evaluate-metric/accuracy) function we can load with the [evaluate.load](https://huggingface.co/docs/evaluate/main/en/package_reference/loading_methods#evaluate.load) (see this [quicktour](https://huggingface.co/docs/evaluate/a_quick_tour) for more information) function:

In [ ]:
import numpy as np
import evaluate

metric = evaluate.load("accuracy")

Downloading builder script:   0%|          | 0.00/4.20k [00:00<?, ?B/s]

Call `compute` on `metric` to calculate the accuracy of your predictions. Before passing your predictions to `compute`, you need to convert the predictions to logits (remember all 🤗 Transformers models return logits):

In [ ]:
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

In case we would like to monitor our evaluation metrics during fine-tuning, we can specify the `evaluation_strategy` parameter in our training arguments to report the evaluation metric at the end of each epoch:

In [ ]:
from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(output_dir="test_trainer", report_to="none")

#### Trainer

Create a [Trainer](https://huggingface.co/docs/transformers/main/en/main_classes/trainer#transformers.Trainer) object with your model, training arguments, training and test datasets, and evaluation function:

In [ ]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=small_train_dataset,
    eval_dataset=small_eval_dataset,
    compute_metrics=compute_metrics,
)

Then fine-tune your model by calling [train()](https://huggingface.co/docs/transformers/main/en/main_classes/trainer#transformers.Trainer.train):

In [ ]:
trainer.train()

TrainOutput(global_step=375, training_loss=1.031009765625, metrics={'train_runtime': 278.6341, 'train_samples_per_second': 10.767, 'train_steps_per_second': 1.346, 'total_flos': 789354427392000.0, 'train_loss': 1.031009765625, 'epoch': 3.0})

<a id='pytorch_native'></a>

In [ ]:
import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer
import numpy as np

# 1. Load your fine-tuned model and tokenizer
model_path = "test_trainer"  # The path where your model was saved during training
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")  # Use the same tokenizer as during training
model = AutoModelForSequenceClassification.from_pretrained("test_trainer/checkpoint-375")

# 2. Prepare your model for inference
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()

# 3. Example function to make predictions on new text
def predict_sentiment(text):
    # Tokenize the text
    inputs = tokenizer(text, padding=True, truncation=True, return_tensors="pt")
    inputs = {k: v.to(device) for k, v in inputs.items()}

    # Make prediction
    with torch.no_grad():
        outputs = model(**inputs)

    # Get predictions
    logits = outputs.logits
    predictions = torch.argmax(logits, dim=-1)

    # Map the prediction to sentiment label (for Yelp reviews: 1-5 stars)
    # Adjust the labels based on your specific task
    sentiment_labels = {
        0: "1 star - very negative",
        1: "2 stars - negative",
        2: "3 stars - neutral",
        3: "4 stars - positive",
        4: "5 stars - very positive"
    }

    predicted_label = sentiment_labels[predictions.item()]
    confidence = torch.softmax(logits, dim=-1).max().item()

    return {
        "text": text,
        "prediction": predictions.item(),
        "label": predicted_label,
        "confidence": confidence,
        "probabilities": torch.softmax(logits, dim=-1).cpu().numpy()[0]
    }

# 4. Test with some example reviews
example_reviews = [
"""
The first time my boyfriend and I came here, it instantly became
 our favorite AYCE. I love seafood and my boyfriend loves meat so this
 was the perfect spot for date night. The food is definitely worth the price tag.
"""
]

# 5. Make predictions
results = []
for review in example_reviews:
    prediction = predict_sentiment(review)
    results.append(prediction)

# 6. Print results
for result in results:
    print(f"Text: {result['text']}")
    print(f"Sentiment: {result['label']} (confidence: {result['confidence']:.4f})")
    print("-" * 80)

# 7. Batch prediction (more efficient for multiple inputs)
def predict_batch(texts):
    inputs = tokenizer(texts, padding=True, truncation=True, return_tensors="pt")
    inputs = {k: v.to(device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model(**inputs)

    logits = outputs.logits
    predictions = torch.argmax(logits, dim=-1)
    probabilities = torch.softmax(logits, dim=-1)

    return predictions.cpu().numpy(), probabilities.cpu().numpy()

# 8. Example of batch prediction
batch_predictions, batch_probs = predict_batch(example_reviews)
print("\nBatch Prediction Results:")
for i, (text, pred, probs) in enumerate(zip(example_reviews, batch_predictions, batch_probs)):
    sentiment_label = {
        0: "1 star - very negative",
        1: "2 stars - negative",
        2: "3 stars - neutral",
        3: "4 stars - positive",
        4: "5 stars - very positive"
    }[pred]

    print(f"Review {i+1}: {sentiment_label} (confidence: {probs[pred]:.4f})")

Text:
The first time my boyfriend and I came here, it instantly became
 our favorite AYCE. I love seafood and my boyfriend loves meat so this
 was the perfect spot for date night. The food is definitely worth the price tag.

Sentiment: 5 stars - very positive (confidence: 0.6786)
--------------------------------------------------------------------------------

Batch Prediction Results:
Review 1: 5 stars - very positive (confidence: 0.6786)

### Train in native PyTorch

[Trainer](https://huggingface.co/docs/transformers/main/en/main_classes/trainer#transformers.Trainer) takes care of the training loop and allows we to fine-tune a model in a single line of code. For users who prefer to write their own training loop, we can also fine-tune a 🤗 Transformers model in native PyTorch.

At this point, we may need to restart our notebook or execute the following code to free some memory:

In [ ]:
del model
del trainer
import torch
torch.cuda.empty_cache()

Next, manually postprocess `tokenized_dataset` to prepare it for training.

1. Remove the `text` column because the model does not accept raw text as an input:

In [ ]:
tokenized_datasets = tokenized_datasets.remove_columns(["text"])

2. Rename the `label` column to `labels` because the model expects the argument to be named `labels`:

In [ ]:
tokenized_datasets = tokenized_datasets.rename_column("label", "labels")

3. Set the format of the dataset to return PyTorch tensors instead of lists:

In [ ]:
tokenized_datasets.set_format("torch")

Then create a smaller subset of the dataset as previously shown to speed up the fine-tuning:

In [ ]:
small_train_dataset = tokenized_datasets["train"].shuffle(seed=42).select(range(1000))
small_eval_dataset = tokenized_datasets["test"].shuffle(seed=42).select(range(1000))

#### DataLoader

Create a `DataLoader` for your training and test datasets so you can iterate over batches of data:

In [ ]:
from torch.utils.data import DataLoader

train_dataloader = DataLoader(small_train_dataset, shuffle=True, batch_size=8)
eval_dataloader = DataLoader(small_eval_dataset, batch_size=8)

Now we can load our model with the number of expected labels:

In [ ]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained("bert-base-cased", num_labels=5)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

#### Optimizer and learning rate scheduler

We must create an optimizer and learning rate scheduler to fine-tune the model. Let's use the [`AdamW`](https://pytorch.org/docs/stable/generated/torch.optim.AdamW.html) optimizer from PyTorch:

In [ ]:
from torch.optim import AdamW

optimizer = AdamW(model.parameters(), lr=5e-5)

Create the default learning rate scheduler from [Trainer](https://huggingface.co/docs/transformers/main/en/main_classes/trainer#transformers.Trainer):

In [ ]:
from transformers import get_scheduler

num_epochs = 3
num_training_steps = num_epochs * len(train_dataloader)
lr_scheduler = get_scheduler(
    name="linear", optimizer=optimizer, num_warmup_steps=0, num_training_steps=num_training_steps
)

Lastly, we specify `device` to use a GPU if we have access to one. Otherwise, training on a CPU may take several hours instead of a couple of minutes. In our case, we can use the GPU provided by Colab

In [ ]:
import torch

device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
model.to(device)

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(28996, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=5, bias=True)
)

#### Training loop

To keep track of our training progress, use the [tqdm](https://tqdm.github.io/) library to add a progress bar over the number of training steps:

In [ ]:
from tqdm.auto import tqdm

progress_bar = tqdm(range(num_training_steps))

model.train()
for epoch in range(num_epochs):
    for batch in train_dataloader:
        batch = {k: v.to(device) for k, v in batch.items()}
        outputs = model(**batch)
        loss = outputs.loss
        loss.backward()

        optimizer.step()
        lr_scheduler.step()
        optimizer.zero_grad()
        progress_bar.update(1)

  0%|          | 0/375 [00:00<?, ?it/s]

#### Evaluate

Just like how we added an evaluation function to [Trainer](https://huggingface.co/docs/transformers/main/en/main_classes/trainer#transformers.Trainer), we need to do the same when we write our own training loop. But instead of calculating and reporting the metric at the end of each epoch, this time we'll accumulate all the batches with `add_batch` and calculate the metric at the very end.

In [ ]:
import evaluate

metric = evaluate.load("accuracy")
model.eval()
for batch in eval_dataloader:
    batch = {k: v.to(device) for k, v in batch.items()}
    with torch.no_grad():
        outputs = model(**batch)

    logits = outputs.logits
    predictions = torch.argmax(logits, dim=-1)
    metric.add_batch(predictions=predictions, references=batch["labels"])

metric.compute()

{'accuracy': 0.54}

### Train a TensorFlow model with Keras

You can also train 🤗 Transformers models in TensorFlow with the Keras API!

#### Loading data for Keras

When you want to train a 🤗 Transformers model with the Keras API, you need to convert your dataset to a format that
Keras understands. If your dataset is small, you can just convert the whole thing to NumPy arrays and pass it to Keras.
Let's try that first before we do anything more complicated.

First, load a dataset. We'll use the CoLA dataset from the [GLUE benchmark](https://huggingface.co/datasets/glue),
since it's a simple binary text classification task, and just take the training split for now.

In [ ]:
from datasets import load_dataset

dataset = load_dataset("glue", "cola")
dataset = dataset["train"]  # Just take the training split for now

Next, load a tokenizer and tokenize the data as NumPy arrays. Note that the labels are already a list of 0 and 1s,
so we can just convert that directly to a NumPy array without tokenization!

In [ ]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")
tokenized_data = tokenizer(dataset["sentence"], return_tensors="np", padding=True)
# Tokenizer returns a BatchEncoding, but we convert that to a dict for Keras
tokenized_data = dict(tokenized_data)

labels = np.array(dataset["label"])  # Label is already an array of 0 and 1

Finally, load, [`compile`](https://keras.io/api/models/model_training_apis/#compile-method), and [`fit`](https://keras.io/api/models/model_training_apis/#fit-method) the model. Note that Transformers models all have a default task-relevant loss function, so you don't need to specify one unless you want to:

In [ ]:
from transformers import TFAutoModelForSequenceClassification
from tensorflow.keras.optimizers import Adam

# Load and compile our model
model = TFAutoModelForSequenceClassification.from_pretrained("bert-base-cased")
# Lower learning rates are often better for fine-tuning transformers
model.compile(optimizer=Adam(3e-5))  # No loss argument!

model.fit(tokenized_data, labels)

<Tip>

You don't have to pass a loss argument to your models when you `compile()` them! Hugging Face models automatically
choose a loss that is appropriate for their task and model architecture if this argument is left blank. You can always
override this by specifying a loss yourself if you want to!

</Tip>

This approach works great for smaller datasets, but for larger datasets, you might find it starts to become a problem. Why?
Because the tokenized array and labels would have to be fully loaded into memory, and because NumPy doesn’t handle
“jagged” arrays, so every tokenized sample would have to be padded to the length of the longest sample in the whole
dataset. That’s going to make your array even bigger, and all those padding tokens will slow down training too!

#### Loading data as a tf.data.Dataset

If you want to avoid slowing down training, you can load your data as a `tf.data.Dataset` instead. Although you can write your own
`tf.data` pipeline if you want, 🤗 Transformers provides two convenience methods for doing this:

- [prepare_tf_dataset()](https://huggingface.co/docs/transformers/main/en/main_classes/model#transformers.TFPreTrainedModel.prepare_tf_dataset): This is the recommended method for most cases. Because it is a method
on your model, it can inspect the model to automatically figure out which columns are usable as model inputs, and
discard the others to make a simpler, more performant dataset.
- [to_tf_dataset](https://huggingface.co/docs/datasets/main/en/package_reference/main_classes#datasets.Dataset.to_tf_dataset): This method is more low-level, and is useful when you want to exactly control how
your dataset is created, by specifying exactly which `columns` and `label_cols` to include.

Before you can use [prepare_tf_dataset()](https://huggingface.co/docs/transformers/main/en/main_classes/model#transformers.TFPreTrainedModel.prepare_tf_dataset), you will need to add the tokenizer outputs to your dataset as columns, as shown in
the following code sample:

In [ ]:
def tokenize_dataset(data):
    # Keys of the returned dictionary will be added to the dataset as columns
    return tokenizer(data["text"])


dataset = dataset.map(tokenize_dataset)

Remember that Hugging Face datasets are stored on disk by default, so this will not inflate your memory usage! Once the
columns have been added, you can stream batches from the dataset and add padding to each batch, which greatly
reduces the number of padding tokens compared to padding the entire dataset.

In [ ]:
tf_dataset = model.prepare_tf_dataset(dataset["train"], batch_size=16, shuffle=True, tokenizer=tokenizer)

Note that in the code sample above, you need to pass the tokenizer to `prepare_tf_dataset` so it can correctly pad batches as they're loaded.
If all the samples in your dataset are the same length and no padding is necessary, you can skip this argument.
If you need to do something more complex than just padding samples (e.g. corrupting tokens for masked language
modelling), you can use the `collate_fn` argument instead to pass a function that will be called to transform the
list of samples into a batch and apply any preprocessing you want.

Once you've created a `tf.data.Dataset`, you can compile and fit the model as before:

In [ ]:
model.compile(optimizer=Adam(3e-5))  # No loss argument!

model.fit(tf_dataset)

### Acknowledgement

The section on finetuning with HuggingFace was adapted from the HuggingFace documentation, which you can ready [here](https://huggingface.co/docs/transformers/training)