# APIS

##  Application Programming Interfac

What is an API?

## 🛠️ Types of APIs: REST, SOAP, GraphQL

| **API Type**  | **Description** | **Data Format** | **Example** |
|--------------|---------------|---------------|------------|
| **REST** 🌍  | HTTP-based API, uses URLs and methods like GET, POST | JSON, XML | FRED API, OpenWeather |
| **SOAP** 🛑  | Older protocol, uses XML and strict rules | XML only | Bank or large enterprise APIs |
| **GraphQL** 🚀 | Allows requesting only the needed data | JSON | GitHub API |

#### APIS PUBLICAS

In [6]:
import requests

url = "https://jsonplaceholder.typicode.com/posts/1"
response = requests.get(url)
print(response.json())  # Devuelve un diccionario con los datos
#print(response)  # 200 --> Correcto

{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

In [7]:
#REST
import json
import requests

url = "https://pokeapi.co/api/v2/pokemon/pikachu"
response = requests.get(url)
print(response.json())  # # Returns Pikachu's data

{'abilities': [{'ability': {'name': 'static', 'url': 'https://pokeapi.co/api/v2/ability/9/'}, 'is_hidden': False, 'slot': 1}, {'ability': {'name': 'lightning-rod', 'url': 'https://pokeapi.co/api/v2/ability/31/'}, 'is_hidden': True, 'slot': 3}], 'base_experience': 112, 'cries': {'latest': 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/25.ogg', 'legacy': 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/legacy/25.ogg'}, 'forms': [{'name': 'pikachu', 'url': 'https://pokeapi.co/api/v2/pokemon-form/25/'}], 'game_indices': [{'game_index': 84, 'version': {'name': 'red', 'url': 'https://pokeapi.co/api/v2/version/1/'}}, {'game_index': 84, 'version': {'name': 'blue', 'url': 'https://pokeapi.co/api/v2/version/2/'}}, {'game_index': 84, 'version': {'name': 'yellow', 'url': 'https://pokeapi.co/api/v2/version/3/'}}, {'game_index': 25, 'version': {'name': 'gold', 'url': 'https://pokeapi.co/api/v2/version/4/'}}, {'game_index': 25, 'version': {'name': 'silver', 'url': 'https://pokeapi.co/api/v2/version/5/'}}, {'game_index': 25, 'version': {'name': 'crystal', 'url': 'https://pokeapi.co/api/v2/version/6/'}}, {'game_index': 25, 'version': {'name': 'ruby', 'url': 'https://pokeapi.co/api/v2/version/7/'}}, {'game_index': 25, 'version': {'name': 'sapphire', 'url': 'https://pokeapi.co/api/v2/version/8/'}}, {'game_index': 25, 'version': {'name': 'emerald', 'url': 'https://pokeapi.co/api/v2/version/9/'}}, {'game_index': 25, 'version': {'name': 'firered', 'url': 'https://pokeapi.co/api/v2/version/10/'}}, {'game_index': 25, 'version': {'name': 'leafgreen', 'url': 'https://pokeapi.co/api/v2/version/11/'}}, {'game_index': 25, 'version': {'name': 'diamond', 'url': 'https://pokeapi.co/api/v2/version/12/'}}, {'game_index': 25, 'version': {'name': 'pearl', 'url': 'https://pokeapi.co/api/v2/version/13/'}}, {'game_index': 25, 'version': {'name': 'platinum', 'url': 'https://pokeapi.co/api/v2/version/14/'}}, {'game_index': 25, 'version': {'name': 'heartgold', 'url': 'https://pokeapi.co/api/v2/version/15/'}}, {'game_index': 25, 'version': {'name': 'soulsilver', 'url': 'https://pokeapi.co/api/v2/version/16/'}}, {'game_index': 25, 'version': {'name': 'black', 'url': 'https://pokeapi.co/api/v2/version/17/'}}, {'game_index': 25, 'version': {'name': 'white', 'url': 'https://pokeapi.co/api/v2/version/18/'}}, {'game_index': 25, 'version': {'name': 'black-2', 'url': 'https://pokeapi.co/api/v2/version/21/'}}, {'game_index': 25, 'version': {'name': 'white-2', 'url': 'https://pokeapi.co/api/v2/version/22/'}}], 'height': 4, 'held_items': [{'item': {'name': 'oran-berry', 'url': 'https://pokeapi.co/api/v2/item/132/'}, 'version_details': [{'rarity': 50, 'version': {'name': 'ruby', 'url': 'https://pokeapi.co/api/v2/version/7/'}}, {'rarity': 50, 'version': {'name': 'sapphire', 'url': 'https://pokeapi.co/api/v2/version/8/'}}, {'rarity': 50, 'version': {'name': 'emerald', 'url': 'https://pokeapi.co/api/v2/version/9/'}}, {'rarity': 50, 'version': {'name': 'diamond', 'url': 'https://pokeapi.co/api/v2/version/12/'}}, {'rarity': 50, 'version': {'name': 'pearl', 'url': 'https://pokeapi.co/api/v2/version/13/'}}, {'rarity': 50, 'version': {'name': 'platinum', 'url': 'https://pokeapi.co/api/v2/version/14/'}}, {'rarity': 50, 'version': {'name': 'heartgold', 'url': 'https://pokeapi.co/api/v2/version/15/'}}, {'rarity': 50, 'version': {'name': 'soulsilver', 'url': 'https://pokeapi.co/api/v2/version/16/'}}, {'rarity': 50, 'version': {'name': 'black', 'url': 'https://pokeapi.co/api/v2/version/17/'}}, {'rarity': 50, 'version': {'name': 'white', 'url': 'https://pokeapi.co/api/v2/version/18/'}}]}, {'item': {'name': 'light-ball', 'url': 'https://pokeapi.co/api/v2/item/213/'}, 'version_details': [{'rarity': 5, 'version': {'name': 'ruby', 'url': 'https://pokeapi.co/api/v2/version/7/'}}, {'rarity': 5, 'version': {'name': 'sapphire', 'url': 'https://pokeapi.co/api/v2/version/8/'}}, {'rarity': 5, 'version': {'name': 'emerald', 'url': 'https://pokeapi.co/api/v2/version/9/'}}, {'rarity': 5, 'version': {'name': 'diamond', 'url': 'https://pokeapi.co/api/v2/version/12/'}}, {'rarity': 5, 'version': {'name': 'pearl', 'url': 'https://pokeapi.co/api/v2/version/13/'}}, {'rarity': 5, 'version': {'name': 'platinum', 'url': 'https://pokeapi.co/api/v2/version/14/'}}, {'rarity': 5, 'version': {'name': 'heartgold', 'url': 'https://pokeapi.co/api/v2/version/15/'}}, {'rarity': 5, 'version': {'name': 'soulsilver', 'url': 'https://pokeapi.co/api/v2/version/16/'}}, {'rarity': 1, 'version': {'name': 'black', 'url': 'https://pokeapi.co/api/v2/version/17/'}}, {'rarity': 1, 'version': {'name': 'white', 'url': 'https://pokeapi.co/api/v2/version/18/'}}, {'rarity': 5, 'version': {'name': 'black-2', 'url': 'https://pokeapi.co/api/v2/version/21/'}}, {'rarity': 5, 'version': {'name': 'white-2', 'url': 'https://pokeapi.co/api/v2/version/22/'}}, {'rarity': 5, 'version': {'name': 'x', 'url': 'https://pokeapi.co/api/v2/version/23/'}}, {'rarity': 5, 'version': {'name': 'y', 'url': 'https://pokeapi.co/api/v2/version/24/'}}, {'rarity': 5, 'version': {'name': 'omega-ruby', 'url': 'https://pokeapi.co/api/v2/version/25/'}}, {'rarity': 5, 'version': {'name': 'alpha-sapphire', 'url': 'https://pokeapi.co/api/v2/version/26/'}}, {'rarity': 5, 'version': {'name': 'sun', 'url': 'https://pokeapi.co/api/v2/version/27/'}}, {'rarity': 5, 'version': {'name': 'moon', 'url': 'https://pokeapi.co/api/v2/version/28/'}}, {'rarity': 5, 'version': {'name': 'ultra-sun', 'url': 'https://pokeapi.co/api/v2/version/29/'}}, {'rarity': 5, 'version': {'name': 'ultra-moon', 'url': 'https://pokeapi.co/api/v2/version/30/'}}]}], 'id': 25, 'is_default': True, 'location_area_encounters': 'https://pokeapi.co/api/v2/pokemon/25/encounters', 'moves': [{'move': {'name': 'mega-punch', 'url': 'https://pokeapi.co/api/v2/move/5/'}, 'version_group_details': [{'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'red-blue', 'url': 'https://pokeapi.co/api/v2/version-group/1/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'yellow', 'url': 'https://pokeapi.co/api/v2/version-group/2/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'tutor', 'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'}, 'order': None, 'version_group': {'name': 'emerald', 'url': 'https://pokeapi.co/api/v2/version-group/6/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'tutor', 'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'}, 'order': None, 'version_group': {'name': 'firered-leafgreen', 'url': 'https://pokeapi.co/api/v2/version-group/7/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'sword-shield', 'url': 'https://pokeapi.co/api/v2/version-group/20/'}}]}, {'move': {'name': 'pay-day', 'url': 'https://pokeapi.co/api/v2/move/6/'}, 'version_group_details': [{'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'red-blue', 'url': 'https://pokeapi.co/api/v2/version-group/1/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'yellow', 'url': 'https://pokeapi.co/api/v2/version-group/2/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'lets-go-pikachu-lets-go-eevee', 'url': 'https://pokeapi.co/api/v2/version-group/19/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'sword-shield', 'url': 'https://pokeapi.co/api/v2/version-group/20/'}}]}, {'move': {'name': 'thunder-punch', 'url': 'https://pokeapi.co/api/v2/move/9/'}, 'version_group_details': [{'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'gold-silver', 'url': 'https://pokeapi.co/api/v2/version-group/3/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'crystal', 'url': 'https://pokeapi.co/api/v2/version-group/4/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'tutor', 'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'}, 'order': None, 'version_group': {'name': 'emerald', 'url': 'https://pokeapi.co/api/v2/version-group/6/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'tutor', 'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'}, 'order': None, 'version_group': {'name': 'platinum', 'url': 'https://pokeapi.co/api/v2/version-group/9/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'tutor', 'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'}, 'order': None, 'version_group': {'name': 'heartgold-soulsilver', 'url': 'https://pokeapi.co/api/v2/version-group/10/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'tutor', 'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'}, 'order': None, 'version_group': {'name': 'black-2-white-2', 'url': 'https://pokeapi.co/api/v2/version-group/14/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'tutor', 'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'}, 'order': None, 'version_group': {'name': 'omega-ruby-alpha-sapphire', 'url': 'https://pokeapi.co/api/v2/version-group/16/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'tutor', 'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'}, 'order': None, 'version_group': {'name': 'ultra-sun-ultra-moon', 'url': 'https://pokeapi.co/api/v2/version-group/18/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'lets-go-pikachu-lets-go-eevee', 'url': 'https://pokeapi.co/api/v2/version-group/19/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'sword-shield', 'url': 'https://pokeapi.co/api/v2/version-group/20/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'scarlet-violet', 'url': 'https://pokeapi.co/api/v2/version-group/25/'}}]}, {'move': {'name': 'slam', 'url': 'https://pokeapi.co/api/v2/move/21/'}, 'version_group_details': [{'level_learned_at': 20, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'yellow', 'url': 'https://pokeapi.co/api/v2/version-group/2/'}}, {'level_learned_at': 20, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'gold-silver', 'url': 'https://pokeapi.co/api/v2/version-group/3/'}}, {'level_learned_at': 20, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'crystal', 'url': 'https://pokeapi.co/api/v2/version-group/4/'}}, {'level_learned_at': 20, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'ruby-sapphire', 'url': 'https://pokeapi.co/api/v2/version-group/5/'}}, {'level_learned_at': 20, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'emerald', 'url': 'https://pokeapi.co/api/v2/version-group/6/'}}, {'level_learned_at': 20, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'firered-leafgreen', 'url': 'https://pokeapi.co/api/v2/version-group/7/'}}, {'level_learned_at': 21, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'diamond-pearl', 'url': 'https://pokeapi.co/api/v2/version-group/8/'}}, {'level_learned_at': 21, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'platinum', 'url': 'https://pokeapi.co/api/v2/version-group/9/'}}, {'level_learned_at': 21, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'heartgold-soulsilver', 'url': 'https://pokeapi.co/api/v2/version-group/10/'}}, {'level_learned_at': 26, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'black-white', 'url': 'https://pokeapi.co/api/v2/version-group/11/'}}, {'level_learned_at': 20, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'colosseum', 'url': 'https://pokeapi.co/api/v2/version-group/12/'}}, {'level_learned_at': 20, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'xd', 'url': 'https://pokeapi.co/api/v2/version-group/13/'}}, {'level_learned_at': 26, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'black-2-white-2', 'url': 'https://pokeapi.co/api/v2/version-group/14/'}}, {'level_learned_at': 26, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'x-y', 'url': 'https://pokeapi.co/api/v2/version-group/15/'}}, {'level_learned_at': 37, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'omega-ruby-alpha-sapphire', 'url': 'https://pokeapi.co/api/v2/version-group/16/'}}, {'level_learned_at': 37, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'sun-moon', 'url': 'https://pokeapi.co/api/v2/version-group/17/'}}, {'level_learned_at': 37, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'ultra-sun-ultra-moon', 'url': 'https://pokeapi.co/api/v2/version-group/18/'}}, {'level_learned_at': 24, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'lets-go-pikachu-lets-go-eevee', 'url': 'https://pokeapi.co/api/v2/version-group/19/'}}, {'level_learned_at': 28, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'sword-shield', 'url': 'https://pokeapi.co/api/v2/version-group/20/'}}, {'level_learned_at': 28, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'brilliant-diamond-and-shining-pearl', 'url': 'https://pokeapi.co/api/v2/version-group/23/'}}]}, {'move': {'name': 'double-kick', 'url': 'https://pokeapi.co/api/v2/move/24/'}, 'version_group_details': [{'level_learned_at': 9, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'lets-go-pikachu-lets-go-eevee', 'url': 'https://pokeapi.co/api/v2/version-group/19/'}}]}, {'move': {'name': 'mega-kick', 'url': 'https://pokeapi.co/api/v2/move/25/'}, 'version_group_details': [{'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'red-blue', 'url': 'https://pokeapi.co/api/v2/version-group/1/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'yellow', 'url': 'https://pokeapi.co/api/v2/version-group/2/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'tutor', 'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'}, 'order': None, 'version_group': {'name': 'emerald', 'url': 'https://pokeapi.co/api/v2/version-group/6/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'tutor', 'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'}, 'order': None, 'version_group': {'name': 'firered-leafgreen', 'url': 'https://pokeapi.co/api/v2/version-group/7/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'sword-shield', 'url': 'https://pokeapi.co/api/v2/version-group/20/'}}]}, {'move': {'name': 'headbutt', 'url': 'https://pokeapi.co/api/v2/move/29/'}, 'version_group_details': [{'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'gold-silver', 'url': 'https://pokeapi.co/api/v2/version-group/3/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'crystal', 'url': 'https://pokeapi.co/api/v2/version-group/4/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'tutor', 'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'}, 'order': None, 'version_group': {'name': 'heartgold-soulsilver', 'url': 'https://pokeapi.co/api/v2/version-group/10/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'lets-go-pikachu-lets-go-eevee', 'url': 'https://pokeapi.co/api/v2/version-group/19/'}}]}, {'move': {'name': 'body-slam', 'url': 'https://pokeapi.co/api/v2/move/34/'}, 'version_group_details': [{'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'red-blue', 'url': 'https://pokeapi.co/api/v2/version-group/1/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'yellow', 'url': 'https://pokeapi.co/api/v2/version-group/2/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'tutor', 'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'}, 'order': None, 'version_group': {'name': 'emerald', 'url': 'https://pokeapi.co/api/v2/version-group/6/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'tutor', 'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'}, 'order': None, 'version_group': {'name': 'firered-leafgreen', 'url': 'https://pokeapi.co/api/v2/version-group/7/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'tutor', 'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'}, 'order': None, 'version_group': {'name': 'xd', 'url': 'https://pokeapi.co/api/v2/version-group/13/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'sword-shield', 'url': 'https://pokeapi.co/api/v2/version-group/20/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_gr

In [8]:
import requests
import json  # Import the json module

url = "https://pokeapi.co/api/v2/pokemon/pikachu"
response = requests.get(url)

if response.status_code == 200:
    data = response.json()
    print(json.dumps(data, indent=4))  # Format JSON with 4-space indentation
else:
    print("Error retrieving data:", response.status_code)

{
    "abilities": [
        {
            "ability": {
                "name": "static",
                "url": "https://pokeapi.co/api/v2/ability/9/"
            },
            "is_hidden": false,
            "slot": 1
        },
        {
            "ability": {
                "name": "lightning-rod",
                "url": "https://pokeapi.co/api/v2/ability/31/"
            },
            "is_hidden": true,
            "slot": 3
        }
    ],
    "base_experience": 112,
    "cries": {
        "latest": "https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/25.ogg",
        "legacy": "https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/legacy/25.ogg"
    },
    "forms": [
        {
            "name": "pikachu",
            "url": "https://pokeapi.co/api/v2/pokemon-form/25/"
        }
    ],
    "game_indices": [
        {
            "game_index": 84,
            "version": {
                "name": "red",
                "url": "https://pokeapi.co/api/v2/version/1/"
            }
        },
        {
            "game_index": 84,
            "version": {
                "name": "blue",
                "url": "https://pokeapi.co/api/v2/version/2/"
            }
        },
        {
            "game_index": 84,
            "version": {
                "name": "yellow",
                "url": "https://pokeapi.co/api/v2/version/3/"
            }
        },
        {
            "game_index": 25,
            "version": {
                "name": "gold",
                "url": "https://pokeapi.co/api/v2/version/4/"
            }
        },
        {
            "game_index": 25,
            "version": {
                "name": "silver",
                "url": "https://pokeapi.co/api/v2/version/5/"
            }
        },
        {
            "game_index": 25,
            "version": {
                "name": "crystal",
                "url": "https://pokeapi.co/api/v2/version/6/"
            }
        },
        {
            "game_index": 25,
            "version": {
                "name": "ruby",
                "url": "https://pokeapi.co/api/v2/version/7/"
            }
        },
        {
            "game_index": 25,
            "version": {
                "name": "sapphire",
                "url": "https://pokeapi.co/api/v2/version/8/"
            }
        },
        {
            "game_index": 25,
            "version": {
                "name": "emerald",
                "url": "https://pokeapi.co/api/v2/version/9/"
            }
        },
        {
            "game_index": 25,
            "version": {
                "name": "firered",
                "url": "https://pokeapi.co/api/v2/version/10/"
            }
        },
        {
            "game_index": 25,
            "version": {
                "name": "leafgreen",
                "url": "https://pokeapi.co/api/v2/version/11/"
            }
        },
        {
            "game_index": 25,
            "version": {
                "name": "diamond",
                "url": "https://pokeapi.co/api/v2/version/12/"
            }
        },
        {
            "game_index": 25,
            "version": {
                "name": "pearl",
                "url": "https://pokeapi.co/api/v2/version/13/"
            }
        },
        {
            "game_index": 25,
            "version": {
                "name": "platinum",
                "url": "https://pokeapi.co/api/v2/version/14/"
            }
        },
        {
            "game_index": 25,
            "version": {
                "name": "heartgold",
                "url": "https://pokeapi.co/api/v2/version/15/"
            }
        },
        {
            "game_index": 25,
            "version": {
                "name": "soulsilver",
                "url": "https://pokeapi.co/api/v2/version/16/"
            }
        },
        {
            "game_index": 25,
            "version": {
                "name": "black",
                "url": "https://pokeapi.co/api/v2/version/17/"
            }
        },
        {
            "game_index": 25,
            "version": {
                "name": "white",
                "url": "https://pokeapi.co/api/v2/version/18/"
            }
        },
        {
            "game_index": 25,
            "version": {
                "name": "black-2",
                "url": "https://pokeapi.co/api/v2/version/21/"
            }
        },
        {
            "game_index": 25,
            "version": {
                "name": "white-2",
                "url": "https://pokeapi.co/api/v2/version/22/"
            }
        }
    ],
    "height": 4,
    "held_items": [
        {
            "item": {
                "name": "oran-berry",
                "url": "https://pokeapi.co/api/v2/item/132/"
            },
            "version_details": [
                {
                    "rarity": 50,
                    "version": {
                        "name": "ruby",
                        "url": "https://pokeapi.co/api/v2/version/7/"
                    }
                },
                {
                    "rarity": 50,
                    "version": {
                        "name": "sapphire",
                        "url": "https://pokeapi.co/api/v2/version/8/"
                    }
                },
                {
                    "rarity": 50,
                    "version": {
                        "name": "emerald",
                        "url": "https://pokeapi.co/api/v2/version/9/"
                    }
                },
                {
                    "rarity": 50,
                    "version": {
                        "name": "diamond",
                        "url": "https://pokeapi.co/api/v2/version/12/"
                    }
                },
                {
                    "rarity": 50,
                    "version": {
                        "name": "pearl",
                        "url": "https://pokeapi.co/api/v2/version/13/"
                    }
                },
                {
                    "rarity": 50,
                    "version": {
                        "name": "platinum",
                        "url": "https://pokeapi.co/api/v2/version/14/"
                    }
                },
                {
                    "rarity": 50,
                    "version": {
                        "name": "heartgold",
                        "url": "https://pokeapi.co/api/v2/version/15/"
                    }
                },
                {
                    "rarity": 50,
                    "version": {
                        "name": "soulsilver",
                        "url": "https://pokeapi.co/api/v2/version/16/"
                    }
                },
                {
                    "rarity": 50,
                    "version": {
                        "name": "black",
                        "url": "https://pokeapi.co/api/v2/version/17/"
                    }
                },
                {
                    "rarity": 50,
                    "version": {
                        "name": "white",
                        "url": "https://pokeapi.co/api/v2/version/18/"
                    }
                }
            ]
        },
        {
            "item": {
                "name": "light-ball",
                "url": "https://pokeapi.co/api/v2/item/213/"
            },
            "version_details": [
                {
                    "rarity": 5,
                    "version": {
                        "name": "ruby",
                        "url": "https://pokeapi.co/api/v2/version/7/"
                    }
                },
                {
                    "rarity": 5,
                    "version": {
                        "name": "sapphire",
                        "url": "https://pokeapi.co/api/v2/version/8/"
                    }
                },
                {
                    "rarity": 5,
                    "version": {
                        "name": "emerald",
                        "url": "https://pokeapi.co/api/v2/version/9/"
                    }
                },
                {
                    "rarity": 5,
                    "version": {
                        "name": "diamond",
                        "url": "https://pokeapi.co/api/v2/version/12/"
                    }
                },
                {
                    "rarity": 5,
                    "version": {
                        "name": "pearl",
                        "url": "https://pokeapi.co/api/v2/version/13/"
                    }
                },
                {
                    "rarity": 5,
                    "version": {
                        "name": "platinum",
                        "url": "https://pokeapi.co/api/v2/version/14/"
                    }
                },
                {
                    "rarity": 5,
                    "version": {
                        "name": "heartgold",
                        "url": "https://pokeapi.co/api/v2/version/15/"
                    }
                },
                {
                    "rarity": 5,
                    "version": {
                        "name": "soulsilver",
                        "url": "https://pokeapi.co/api/v2/version/16/"
                    }
                },
                {
                    "rarity": 1,
                    "version": {
                        "name": "black",
                        "url": "https://pokeapi.co/api/v2/version/17/"
                    }
                },
                {
                    "rarity": 1,
                    "version": {
                        "name": "white",
                        "url": "https://pokeapi.co/api/v2/version/18/"
                    }
                },
                {
                    "rarity": 5,
                    "version": {
                        "name": "black-2",
                        "url": "https://pokeapi.co/api/v2/version/21/"
                    }
                },
                {
                    "rarity": 5,
                    "version": {
                        "name": "white-2",
                        "url": "https://pokeapi.co/api/v2/version/22/"
                    }
                },
                {
                    "rarity": 5,
                    "version": {
                        "name": "x",
                        "url": "https://pokeapi.co/api/v2/version/23/"
                    }
                },
                {
                    "rarity": 5,
                    "version": {
                        "name": "y",
                        "url": "https://pokeapi.co/api/v2/version/24/"
                    }
                },
                {
                    "rarity": 5,
                    "version": {
                        "name": "omega-ruby",
                        "url": "https://pokeapi.co/api/v2/version/25/"
                    }
                },
                {
                    "rarity": 5,
                    "version": {
                        "name": "alpha-sapphire",
                        "url": "https://pokeapi.co/api/v2/version/26/"
                    }
                },
                {
                    "rarity": 5,
                    "version": {
                        "name": "sun",
                        "url": "https://pokeapi.co/api/v2/version/27/"
                    }
                },
                {
                    "rarity": 5,
                    "version": {
                        "name": "moon",
                        "url": "https://pokeapi.co/api/v2/version/28/"
                    }
                },
                {
                    "rarity": 5,
                    "version": {
                        "name": "ultra-sun",
                        "url": "https://pokeapi.co/api/v2/version/29/"
                    }
                },
                {
                    "rarity": 5,
                    "version": {
                        "name": "ultra-moon",
                        "url": "https://pokeapi.co/api/v2/version/30/"
                    }
                }
            ]
        }
    ],
    "id": 25,
    "is_default": true,
    "location_area_encounters": "https://pokeapi.co/api/v2/pokemon/25/encounters",
    "moves": [
        {
            "move": {
                "name": "mega-punch",
                "url": "https://pokeapi.co/api/v2/move/5/"
            },
            "version_group_details": [
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "machine",
                        "url": "https://pokeapi.co/api/v2/move-learn-method/4/"
                    },
                    "order": null,
                    "version_group": {
                        "name": "red-blue",
                        "url": "https://pokeapi.co/api/v2/version-group/1/"
                    }
                },
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "machine",
                        "url": "https://pokeapi.co/api/v2/move-learn-method/4/"
                    },
                    "order": null,
                    "version_group": {
                        "name": "yellow",
                        "url": "https://pokeapi.co/api/v2/version-group/2/"
                    }
                },
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "tutor",
                        "url": "https://pokeapi.co/api/v2/move-learn-method/3/"
                    },
                    "order": null,
                    "version_group": {
                        "name": "emerald",
                        "url": "https://pokeapi.co/api/v2/version-group/6/"
                    }
                },
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "tutor",
                        "url": "https://pokeapi.co/api/v2/move-learn-method/3/"
                    },
                    "order": null,
                    "version_group": {
                        "name": "firered-leafgreen",
                        "url": "https://pokeapi.co/api/v2/version-group/7/"
                    }
                },
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "machine",
                        "url": "https://pokeapi.co/api/v2/move-learn-method/4/"
                    },
                    "order": null,
                    "version_group": {
                        "name": "sword-shield",
                        "url": "https://pokeapi.co/api/v2/version-group/20/"
                    }
                }
            ]
        },
        {
            "move": {
                "name": "pay-day",
                "url": "https://pokeapi.co/api/v2/move/6/"
            },
            "version_group_details": [
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "machine",
                        "url": "https://pokeapi.co/api/v2/move-learn-method/4/"
                    },
                    "order": null,
                    "version_group": {
                        "name": "red-blue",
                        "url": "https://pokeapi.co/api/v2/version-group/1/"
                    }
                },
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "machine",
                        "url": "https://pokeapi.co/api/v2/move-learn-method/4/"
                    },
                    "order": null,
                    "version_group": {
                        "name": "yellow",
                        "url": "https://pokeapi.co/api/v2/version-group/2/"
                    }
                },
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "machine",
                        "url": "https://pokeapi.co/api/v2/move-learn-method/4/"
                    },
                    "order": null,
                    "version_group": {
                        "name": "lets-go-pikachu-lets-go-eevee",
                        "url": "https://pokeapi.co/api/v2/version-group/19/"
                    }
                },
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "machine",
                        "url": "https://pokeapi.co/api/v2/move-learn-method/4/"
                    },
                    "order": null,
                    "version_group": {
                        "name": "sword-shield",
                        "url": "https://pokeapi.co/api/v2/version-group/20/"
                    }
                }
            ]
        },
        {
            "move": {
                "name": "thunder-punch",
                "url": "https://pokeapi.co/api/v2/move/9/"
            },
            "version_group_details": [
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "machine",
                        "url": "https://pokeapi.co/api/v2/move-learn-method/4/"
                    },
                    "order": null,
                    "version_group": {
                        "name": "gold-silver",
                        "url": "https://pokeapi.co/api/v2/version-group/3/"
                    }
                },
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "machine",
                        "url": "https://pokeapi.co/api/v2/move-learn-method/4/"
                    },
                    "order": null,
                    "version_group": {
                        "name": "crystal",
                        "url": "https://pokeapi.co/api/v2/version-group/4/"
                    }
                },
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "tutor",
                        "url": "https://pokeapi.co/api/v2/move-learn-method/3/"
                    },
                    "order": null,
                    "version_group": {
                        "name": "emerald",
                        "url": "https://pokeapi.co/api/v2/version-group/6/"
                    }
                },
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "tutor",
                        "url": "https://pokeapi.co/api/v2/move-learn-method/3/"
                    },
                    "order": null,
                    "version_group": {
                        "name": "platinum",
                        "url": "https://pokeapi.co/api/v2/version-group/9/"
                    }
                },
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "tutor",
                        "url": "https://pokeapi.co/api/v2/move-learn-method/3/"
                    },
                    "order": null,
                    "version_group": {
                        "name": "heartgold-soulsilver",
                        "url": "https://pokeapi.co/api/v2/version-group/10/"
                    }
                },
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "tutor",

In [9]:
{
    "fecha": "2024-03-30",
    "tipo_cambio": 3.75
}

{'fecha': '2024-03-30', 'tipo_cambio': 3.75}

In [10]:
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
   <soap:Body>
      <GetExchangeRate>
         <Currency>USD</Currency>
      </GetExchangeRate>
   </soap:Body>
</soap:Envelope>

SyntaxError: invalid syntax (2857368445.py, line 1)

## 📂 JSON vs. XML: Estructura y diferencias  

| **Formato**   | **JSON 🟢** | **XML 🔵** |
|--------------|------------|------------|
| **Sintaxis**  | Más simple, estilo diccionario | Más verboso, usa etiquetas |
| **Usabilidad** | Más fácil de leer y usar en Python | Necesita más procesamiento |
| **Popularidad** | Muy usado en APIs REST | Más común en SOAP |
| **Ejemplo** | `{ "nombre": "Juan", "edad": 30 }` | `<persona><nombre>Juan</nombre><edad>30</edad></persona>` |

(JavaScript Object Notation) |  Extensible Markup Language

In [11]:
import requests

# URL to get information about Pikachu
url = "https://pokeapi.co/api/v2/pokemon/pikachu"

# Make the API request
response = requests.get(url)

# Convert the response to JSON
data = response.json()

# Extract some key data
name = data["name"] # Nombre de la columna en el json
height = data["height"] / 10  # Converted to meters
weight = data["weight"] / 10  # Converted to kg
types = [tipo["type"]["name"] for tipo in data["types"]]
abilities = [ability["ability"]["name"] for ability in data["abilities"]]

# Display results
print(f"📌 Pokémon: {name.capitalize()}")
print(f"📏 Height: {height} m")
print(f"⚖️ Weight: {weight} kg")
print(f"🔥 Type(s): {', '.join(types)}")
print(f"🛠️ Abilities: {', '.join(abilities)}")

📌 Pokémon: Pikachu
📏 Height: 0.4 m
⚖️ Weight: 6.0 kg
🔥 Type(s): electric
🛠️ Abilities: static, lightning-rod

In [12]:
url = "https://pokeapi.co/api/v2/pokemon?limit=10"

response = requests.get(url)
data = response.json()

# Extract names of the first 10 Pokémon
pokemon_list = [pokemon["name"] for pokemon in data["results"]]

print("📜 First 10 Pokémon in the Pokédex:")
for i, pokemon in enumerate(pokemon_list, 1):
    print(f"{i}. {pokemon.capitalize()}")

📜 First 10 Pokémon in the Pokédex:
1. Bulbasaur
2. Ivysaur
3. Venusaur
4. Charmander
5. Charmeleon
6. Charizard
7. Squirtle
8. Wartortle
9. Blastoise
10. Caterpie

In [13]:
pokemon = "charizard"
url = f"https://pokeapi.co/api/v2/pokemon/{pokemon}"

response = requests.get(url)
data = response.json()

# Extract stats
stats = {stat["stat"]["name"]: stat["base_stat"] for stat in data["stats"]}

print(f"📊 Stats of {pokemon.capitalize()}:")
for stat, value in stats.items():
    print(f"{stat.capitalize()}: {value}")

📊 Stats of Charizard:
Hp: 78
Attack: 84
Defense: 78
Special-attack: 109
Special-defense: 85
Speed: 100

In [ ]:
type_name = "fire"
url = f"https://pokeapi.co/api/v2/type/{type_name}"

response = requests.get(url)
data = response.json()

# Get the first 10 Fire-type Pokémon
fire_type_pokemon = [poke["pokemon"]["name"] for poke in data["pokemon"][:10]]

print(f"🔥 {type_name.capitalize()}-type Pokémon:")
for i, poke in enumerate(fire_type_pokemon, 1):
    print(f"{i}. {poke.capitalize()}")

🔥 Fire-type Pokémon:
1. Charmander
2. Charmeleon
3. Charizard
4. Vulpix
5. Ninetales
6. Growlithe
7. Arcanine
8. Ponyta
9. Rapidash
10. Magmar

# BCRP

## Formato API BRCP

Introduction to the BCRP API

The Central Reserve Bank of Peru (BCRP) API provides access to macroeconomic statistical series such as inflation, GDP, and exchange rates, facilitating economic and financial analysis.

Main Features:

HTTP Methods: GET and POST.

Output Formats: HTML, Graph, XLS, XML, JSON, JSONP, TXT, CSV.

Access to data in Spanish and English.

**URL BASE**

In [14]:
https://estadisticas.bcrp.gob.pe/estadisticas/series/api/{CODIGO_SERIE}/{FORMATO}/{FECHA_INICIO}/{FECHA_FIN}

SyntaxError: invalid syntax (1861909875.py, line 1)

Main Parameters:

COD_SERIE: Code of the statistical series.

FORMATO: Output format (json, xml, csv, xls, etc.).

FECHA_INI/FECHA_FIN: Date range (YYYY-MM-DD).

IDIOMA: Spanish (esp) or English (ing).

HTTP Methods: GET and POST
GET:

It is the most commonly used method in public APIs.

It allows requesting data from a server without modifying the stored information.

| **Feature**           | **GET**                               | **POST**                               |
|-----------------------|---------------------------------------|----------------------------------------|
| **Purpose**           | Retrieve data                        | Send data to the server               |
| **Visibility**        | Parameters in the URL                | Parameters in the request body        |
| **Security**          | Not secure for sensitive data        | More secure for sensitive data        |
| **Typical Use**       | Retrieve information (searches, etc.)| Submit forms, upload files            |
| **Data Size**         | Limited by the length of the URL     | Can handle large amounts of data      |

### GET

In [15]:
import requests

# Example URL
url = "https://jsonplaceholder.typicode.com/posts"

# Making a GET request
response = requests.get(url)

# Checking the response status
if response.status_code == 200:
    print("GET request successful")
    # Print the first 3 items from the response
    posts = response.json()  # Parse JSON
    print(posts[:3])  # Show the first 3 posts
else:
    print("Error in GET request:", response.status_code)

GET request successful
[{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}, {'userId': 1, 'id': 2, 'title': 'qui est esse', 'body': 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla'}, {'userId': 1, 'id': 3, 'title': 'ea molestias quasi exercitationem repellat qui ipsa sit aut', 'body': 'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut'}]

### POST

In [ ]:
import requests

# Example URL
url = "https://jsonplaceholder.typicode.com/posts"

# Data to be sent in the POST request body
data = {
    "title": "My new post",
    "body": "This is the content of my post",
    "userId": 1
}

# Making a POST request
response = requests.post(url, json=data)

# Checking the response status
if response.status_code == 201:
    print("POST request successful")
    print("Data sent:", response.json())  # Print the data returned by the server
else:
    print("Error in POST request:", response.status_code)

POST request successful
Data sent: {'title': 'My new post', 'body': 'This is the content of my post', 'userId': 1, 'id': 101}

### Example in the BCRP API:

In [16]:
import requests
import pandas as pd

url = "https://estadisticas.bcrp.gob.pe/estadisticas/series/api/PD04640PD/json/2024-01-01/2024-12-31"

response = requests.get(url)
data = response.json()

df = pd.DataFrame(data['periods'])
print(df.head())  # Show first values

        name   values
0  03.Ene.24  [3.738]
1  04.Ene.24   [3.74]
2  05.Ene.24  [3.723]
3  08.Ene.24  [3.719]
4  09.Ene.24  [3.708]

In [17]:
url = "https://estadisticas.bcrp.gob.pe/estadisticas/series/api/PD04640PD/json/2024-01-01/2024-12-31/esp"
response = requests.get(url)
data = response.json()
data

{'config': {'title': 'Tipo de cambio',
  'series': [{'name': 'Tipo de cambio - TC Sistema bancario SBS (S/ por US$) - Venta',
    'dec': '3'}]},
 'periods': [{'name': '03.Ene.24', 'values': ['3.738']},
  {'name': '04.Ene.24', 'values': ['3.74']},
  {'name': '05.Ene.24', 'values': ['3.723']},
  {'name': '08.Ene.24', 'values': ['3.719']},
  {'name': '09.Ene.24', 'values': ['3.708']},
  {'name': '10.Ene.24', 'values': ['3.704']},
  {'name': '11.Ene.24', 'values': ['3.703']},
  {'name': '12.Ene.24', 'values': ['3.696']},
  {'name': '15.Ene.24', 'values': ['3.704']},
  {'name': '16.Ene.24', 'values': ['3.718']},
  {'name': '17.Ene.24', 'values': ['3.739']},
  {'name': '18.Ene.24', 'values': ['3.742']},
  {'name': '19.Ene.24', 'values': ['3.743']},
  {'name': '22.Ene.24', 'values': ['3.746']},
  {'name': '23.Ene.24', 'values': ['3.755']},
  {'name': '24.Ene.24', 'values': ['3.76']},
  {'name': '25.Ene.24', 'values': ['3.765']},
  {'name': '26.Ene.24', 'values': ['3.786']},
  {'name': '29.Ene.24', 'values': ['3.807']},
  {'name': '30.Ene.24', 'values': ['3.813']},
  {'name': '31.Ene.24', 'values': ['3.808']},
  {'name': '01.Feb.24', 'values': ['3.808']},
  {'name': '02.Feb.24', 'values': ['3.829']},
  {'name': '05.Feb.24', 'values': ['3.852']},
  {'name': '06.Feb.24', 'values': ['3.858']},
  {'name': '07.Feb.24', 'values': ['3.868']},
  {'name': '08.Feb.24', 'values': ['3.854']},
  {'name': '09.Feb.24', 'values': ['3.868']},
  {'name': '12.Feb.24', 'values': ['3.869']},
  {'name': '13.Feb.24', 'values': ['3.883']},
  {'name': '14.Feb.24', 'values': ['3.877']},
  {'name': '15.Feb.24', 'values': ['3.87']},
  {'name': '16.Feb.24', 'values': ['3.844']},
  {'name': '19.Feb.24', 'values': ['3.807']},
  {'name': '20.Feb.24', 'values': ['3.784']},
  {'name': '21.Feb.24', 'values': ['3.797']},
  {'name': '22.Feb.24', 'values': ['3.807']},
  {'name': '23.Feb.24', 'values': ['3.799']},
  {'name': '26.Feb.24', 'values': ['3.803']},
  {'name': '27.Feb.24', 'values': ['3.793']},
  {'name': '28.Feb.24', 'values': ['3.797']},
  {'name': '29.Feb.24', 'values': ['3.782']},
  {'name': '01.Mar.24', 'values': ['3.773']},
  {'name': '04.Mar.24', 'values': ['3.771']},
  {'name': '05.Mar.24', 'values': ['3.77']},
  {'name': '06.Mar.24', 'values': ['3.736']},
  {'name': '07.Mar.24', 'values': ['3.726']},
  {'name': '08.Mar.24', 'values': ['3.696']},
  {'name': '11.Mar.24', 'values': ['3.692']},
  {'name': '12.Mar.24', 'values': ['3.695']},
  {'name': '13.Mar.24', 'values': ['3.671']},
  {'name': '14.Mar.24', 'values': ['3.677']},
  {'name': '15.Mar.24', 'values': ['3.692']},
  {'name': '18.Mar.24', 'values': ['3.698']},
  {'name': '19.Mar.24', 'values': ['3.703']},
  {'name': '20.Mar.24', 'values': ['3.696']},
  {'name': '21.Mar.24', 'values': ['3.701']},
  {'name': '22.Mar.24', 'values': ['3.694']},
  {'name': '25.Mar.24', 'values': ['3.707']},
  {'name': '26.Mar.24', 'values': ['3.727']},
  {'name': '27.Mar.24', 'values': ['3.721']},
  {'name': '01.Abr.24', 'values': ['3.734']},
  {'name': '02.Abr.24', 'values': ['3.711']},
  {'name': '03.Abr.24', 'values': ['3.694']},
  {'name': '04.Abr.24', 'values': ['3.685']},
  {'name': '05.Abr.24', 'values': ['3.691']},
  {'name': '08.Abr.24', 'values': ['3.681']},
  {'name': '09.Abr.24', 'values': ['3.693']},
  {'name': '10.Abr.24', 'values': ['3.71']},
  {'name': '11.Abr.24', 'values': ['3.711']},
  {'name': '12.Abr.24', 'values': ['3.707']},
  {'name': '15.Abr.24', 'values': ['3.725']},
  {'name': '16.Abr.24', 'values': ['3.755']},
  {'name': '17.Abr.24', 'values': ['3.749']},
  {'name': '18.Abr.24', 'values': ['3.744']},
  {'name': '19.Abr.24', 'values': ['3.702']},
  {'name': '22.Abr.24', 'values': ['3.701']},
  {'name': '23.Abr.24', 'values': ['3.701']},
  {'name': '24.Abr.24', 'values': ['3.724']},
  {'name': '25.Abr.24', 'values': ['3.745']},
  {'name': '26.Abr.24', 'values': ['3.756']},
  {'name': '29.Abr.24', 'values': ['3.734']},
  {'name': '30.Abr.24', 'values': ['3.752']},
  {'name': '02.May.24', 'values': ['3.757']},
  {'name': '03.May.24', 'values': ['3.726']},
  {'name': '06.May.24', 'values': ['3.73']},
  {'name': '07.May.24', 'values': ['3.728']},
  {'name': '08.May.24', 'values': ['3.724']},
  {'name': '09.May.24', 'values': ['3.713']},
  {'name': '10.May.24', 'values': ['3.708']},
  {'name': '13.May.24', 'values': ['3.723']},
  {'name': '14.May.24', 'values': ['3.728']},
  {'name': '15.May.24', 'values': ['3.718']},
  {'name': '16.May.24', 'values': ['3.728']},
  {'name': '17.May.24', 'values': ['3.742']},
  {'name': '20.May.24', 'values': ['3.736']},
  {'name': '21.May.24', 'values': ['3.733']},
  {'name': '22.May.24', 'values': ['3.743']},
  {'name': '23.May.24', 'values': ['3.746']},
  {'name': '24.May.24', 'values': ['3.739']},
  {'name': '27.May.24', 'values': ['3.748']},
  {'name': '28.May.24', 'values': ['3.75']},
  {'name': '29.May.24', 'values': ['3.762']},
  {'name': '30.May.24', 'values': ['3.753']},
  {'name': '31.May.24', 'values': ['3.741']},
  {'name': '03.Jun.24', 'values': ['3.736']},
  {'name': '04.Jun.24', 'values': ['3.74']},
  {'name': '05.Jun.24', 'values': ['3.747']},
  {'name': '06.Jun.24', 'values': ['3.756']},
  {'name': '10.Jun.24', 'values': ['3.781']},
  {'name': '11.Jun.24', 'values': ['3.787']},
  {'name': '12.Jun.24', 'values': ['3.772']},
  {'name': '13.Jun.24', 'values': ['3.777']},
  {'name': '14.Jun.24', 'values': ['3.776']},
  {'name': '17.Jun.24', 'values': ['3.796']},
  {'name': '18.Jun.24', 'values': ['3.789']},
  {'name': '19.Jun.24', 'values': ['3.818']},
  {'name': '20.Jun.24', 'values': ['3.814']},
  {'name': '21.Jun.24', 'values': ['3.806']},
  {'name': '24.Jun.24', 'values': ['3.805']},
  {'name': '25.Jun.24', 'values': ['3.817']},
  {'name': '26.Jun.24', 'values': ['3.822']},
  {'name': '27.Jun.24', 'values': ['3.825']},
  {'name': '28.Jun.24', 'values': ['3.837']},
  {'name': '01.Jul.24', 'values': ['3.851']},
  {'name': '02.Jul.24', 'values': ['3.833']},
  {'name': '03.Jul.24', 'values': ['3.802']},
  {'name': '04.Jul.24', 'values': ['3.802']},
  {'name': '05.Jul.24', 'values': ['3.797']},
  {'name': '08.Jul.24', 'values': ['3.797']},
  {'name': '09.Jul.24', 'values': ['3.789']},
  {'name': '10.Jul.24', 'values': ['3.785']},
  {'name': '11.Jul.24', 'values': ['3.771']},
  {'name': '12.Jul.24', 'values': ['3.74']},
  {'name': '15.Jul.24', 'values': ['3.733']},
  {'name': '16.Jul.24', 'values': ['3.725']},
  {'name': '17.Jul.24', 'values': ['3.723']},
  {'name': '18.Jul.24', 'values': ['3.735']},
  {'name': '19.Jul.24', 'values': ['3.743']},
  {'name': '22.Jul.24', 'values': ['3.758']},
  {'name': '24.Jul.24', 'values': ['3.778']},
  {'name': '25.Jul.24', 'values': ['3.764']},
  {'name': '30.Jul.24', 'values': ['3.742']},
  {'name': '31.Jul.24', 'values': ['3.722']},
  {'name': '01.Ago.24', 'values': ['3.741']},
  {'name': '02.Ago.24', 'values': ['3.748']},
  {'name': '05.Ago.24', 'values': ['3.754']},
  {'name': '07.Ago.24', 'values': ['3.74']},
  {'name': '08.Ago.24', 'values': ['3.732']},
  {'name': '09.Ago.24', 'values': ['3.731']},
  {'name': '12.Ago.24', 'values': ['3.747']},
  {'name': '13.Ago.24', 'values': ['3.75']},
  {'name': '14.Ago.24', 'values': ['3.744']},
  {'name': '15.Ago.24', 'values': ['3.737']},
  {'name': '16.Ago.24', 'values': ['3.748']},
  {'name': '19.Ago.24', 'values': ['3.74']},
  {'name': '20.Ago.24', 'values': ['3.747']},
  {'name': '21.Ago.24', 'values': ['3.744']},
  {'name': '22.Ago.24', 'values': ['3.76']},
  {'name': '23.Ago.24', 'values': ['3.748']},
  {'name': '26.Ago.24', 'values': ['3.759']},
  {'name': '27.Ago.24', 'values': ['3.748']},
  {'name': '28.Ago.24', 'values': ['3.743']},
  {'name': '29.Ago.24', 'values': ['3.75']},
  {'name': '02.Set.24', 'values': ['3.768']},
  {'name': '03.Set.24', 'values': ['3.781']},
  {'name': '04.Set.24', 'values': ['3.797']},
  {'name': '05.Set.24', 'values': ['3.796']},
  {'name': '06.Set.24', 'values': ['3.781']},
  {'name': '09.Set.24', 'values': ['3.816']},
  {'name': '10.Set.24', 'values': ['3.823']},
  {'name': '11.Set.24', 'values': ['3.794']},
  {'name': '12.Set.24', 'values': ['3.772']},
  {'name': '13.Set.24', 'values': ['3.771']},
  {'name': '16.Set.24', 'values': ['3.788']},
  {'name': '17.Set.24', 'values': ['3.778']},
  {'name': '18.Set.24', 'values': ['3.764']},
  {'name': '19.Set.24', 'values': ['3.751']},
  {'name': '20.Set.24', 'values': ['3.754']},
  {'name': '23.Set.24', 'values': ['3.773']},
  {'name': '24.Set.24', 'values': ['3.768']},
  {'name': '25.Set.24', 'values': ['3.767']},
  {'name': '26.Set.24', 'values': ['3.737']},
  {'name': '27.Set.24', 'values': ['3.722']},
  {'name': '30.Set.24', 'values': ['3.714']},
  {'name': '01.Oct.24', 'values': ['3.718']},
  {'name': '02.Oct.24', 'values': ['3.721']},
  {'name': '03.Oct.24', 'values': ['3.73']},
  {'name': '04.Oct.24', 'values': ['3.734']},
  {'name': '07.Oct.24', 'values': ['3.744']},
  {'name': '09.Oct.24', 'values': ['3.76']},
  {'name': '10.Oct.24', 'values': ['3.767']},
  {'name': '11.Oct.24', 'values': ['3.759']},
  {'name': '14.Oct.24', 'values': ['3.763']},
  {'name': '15.Oct.24', 'values': ['3.77']},
  {'name': '16.Oct.24', 'values': ['3.773']},
  {'name': '17.Oct.24', 'values': ['3.771']},
  {'name': '18.Oct.24', 'values': ['3.759']},
  {'name': '21.Oct.24', 'values': ['3.767']},
  {'name': '22.Oct.24', 'values': ['3.759']},
  {'name': '23.Oct.24', 'values': ['3.757']},
  {'name': '24.Oct.24', 'values': ['3.757']},
  {'name': '25.Oct.24', 'values': ['3.758']},
  {'name': '28.Oct.24', 'values': ['3.775']},
  {'name': '29.Oct.24', 'values': ['3.772']},
  {'name': '30.Oct.24', 'values': ['3.776']},
  {'name': '31.Oct.24', 'values': ['3.775']},
  {'name': '04.Nov.24', 'values': ['3.774']},
  {'name': '05.Nov.24', 'values': ['3.778']},
  {'name': '06.Nov.24', 'values': ['3.787']},
  {'name': '07.Nov.24', 'values': ['3.76']},
  {'name': '08.Nov.24', 'values': ['3.769']},
  {'name': '11.Nov.24', 'values': ['3.781']},
  {'name': '12.Nov.24', 'values': ['3.788']},
  {'name': '13.Nov.24', 'values': ['3.8']},
  {'name': '14.Nov.24', 'values': ['3.805']},
  {'name': '15.Nov.24', 'values': ['3.807']},
  {'name': '18.Nov.24', 'values': ['3.799']},
  {'name': '19.Nov.24', 'values': ['3.798']},
  {'name': '20.Nov.24', 'values': ['3.798']},
  {'name': '21.Nov.24', 'values': ['3.797']},
  {'name': '22.Nov.24', 'values': ['3.798']},
  {'name': '25.Nov.24', 'values': ['3.783']},
  {'name': '26.Nov.24', 'values': ['3.773']},
  {'name': '27.Nov.24', 'values': ['3.762']},
  {'name': '28.Nov.24', 'values': ['3.759']},
  {'name': '29.Nov.24', 'values': ['3.745']},
  {'name': '02.Dic.24', 'values': ['3.766']},
  {'name': '03.Dic.24', 'values': ['3.749']},
  {'name': '04.Dic.24', 'values': ['3.74']},
  {'name': '05.Dic.24', 'values': ['3.735']},
  {'name': '06.Dic.24', 'values': ['3.727']},
  {'name': '10.Dic.24', 'values': ['3.718']},
  {'name': '11.Dic.24', 'values': ['3.722']},
  {'name': '12.Dic.24', 'values': ['3.735']},
  {'name': '13.Dic.24', 'values': ['3.737']},
  {'name': '16.Dic.24', 'values': ['3.74']},
  {'name': '17.Dic.24', 'values': ['3.746']},
  {'name': '18.Dic.24', 'values': ['3.74']},
  {'name': '19.Dic.24', 'values': ['3.743']},
  {'name': '20.Dic.24', 'values': ['3.731']},
  {'name': '23.Dic.24', 'values': ['3.735']},
  {'name': '24.Dic.24', 'values': ['3.731']},
  {'name': '26.Dic.24', 'values': ['3.748']},
  {'name': '27.Dic.24', 'values': ['3.75']},
  {'name': '30.Dic.24', 'values': ['3.77']}]}

In [18]:
import requests

serie_code = "PD04648PD"  # Code for the selling exchange rate
url = f"https://estadisticas.bcrp.gob.pe/estadisticas/series/api/{serie_code}/json"

response = requests.get(url)
print(response.status_code)  # Check the HTTP response code
print(response.text)  # Check the response content

200
{
"config":
{
"title":"Tipo de cambio",
"series":
[
{
"name":"Tipo de cambio - TC Euro (S/ por Euro) - Venta",
"dec":"3"
}]
},
"periods":
[
{
"name":"08.Jul.25",
"values":["4.412"]
},
{
"name":"09.Jul.25",
"values":["4.372"]
},
{
"name":"10.Jul.25",
"values":["4.378"]
},
{
"name":"11.Jul.25",
"values":["4.394"]
},
{
"name":"14.Jul.25",
"values":["4.409"]
},
{
"name":"15.Jul.25",
"values":["4.449"]
},
{
"name":"16.Jul.25",
"values":["4.346"]
},
{
"name":"17.Jul.25",
"values":["4.401"]
},
{
"name":"18.Jul.25",
"values":["4.443"]
},
{
"name":"21.Jul.25",
"values":["4.423"]
},
{
"name":"22.Jul.25",
"values":["4.367"]
},
{
"name":"24.Jul.25",
"values":["4.419"]
},
{
"name":"25.Jul.25",
"values":["4.414"]
},
{
"name":"30.Jul.25",
"values":["4.379"]
},
{
"name":"31.Jul.25",
"values":["4.38"]
},
{
"name":"01.Ago.25",
"values":["4.37"]
},
{
"name":"04.Ago.25",
"values":["4.384"]
},
{
"name":"05.Ago.25",
"values":["4.383"]
},
{
"name":"07.Ago.25",
"values":["4.333"]
},
{
"name":"08.Ago.25",
"values":["4.231"]
},
{
"name":"11.Ago.25",
"values":["4.34"]
},
{
"name":"12.Ago.25",
"values":["4.32"]
},
{
"name":"14.Ago.25",
"values":["4.305"]
},
{
"name":"15.Ago.25",
"values":["4.37"]
},
{
"name":"18.Ago.25",
"values":["4.406"]
},
{
"name":"19.Ago.25",
"values":["4.23"]
},
{
"name":"20.Ago.25",
"values":["4.373"]
},
{
"name":"21.Ago.25",
"values":["4.288"]
},
{
"name":"22.Ago.25",
"values":["4.275"]
},
{
"name":"25.Ago.25",
"values":["4.351"]
}
]
}

In [19]:
def get_exchange_rate(series_code):
    url = f"https://estadisticas.bcrp.gob.pe/estadisticas/series/api/{series_code}/json"
    response = requests.get(url)

    # Check if the response is valid
    if response.status_code != 200:
        print(f"Error: Code {response.status_code} - Data could not be retrieved")
        return None
    
    try:
        data = response.json()
    except requests.exceptions.JSONDecodeError:
        print("Error: The response is not in JSON format")
        print(response.text)  # Show response content for debugging
        return None

    # Extract data from the series
    values = data.get('periods', [])  # Avoid KeyError
    dates = [item['name'] for item in values]
    exchange_rate_values = [float(item['values'][0]) for item in values]

    return pd.DataFrame({'Date': dates, 'TC': exchange_rate_values})

df_purchase = get_exchange_rate("PN01205PM")
df_sale = get_exchange_rate("PN01206PM")

In [20]:
df_sale

        Date        TC
0   Ago.2023  3.698445
1   Sep.2023  3.732010
2   Oct.2023  3.847014
3   Nov.2023  3.762095
4   Dic.2023  3.735089
5   Ene.2024  3.741910
6   Feb.2024  3.828952
7   Mar.2024  3.710037
8   Abr.2024  3.716700
9   May.2024  3.732877
10  Jun.2024  3.788379
11  Jul.2024  3.766110
12  Ago.2024  3.742925
13  Sep.2024  3.769895
14  Oct.2024  3.755814
15  Nov.2024  3.780265
16  Dic.2024  3.736558
17  Ene.2025  3.748255
18  Feb.2025  3.698170
19  Mar.2025  3.653448
20  Abr.2025  3.701260
21  May.2025  3.660862
22  Jun.2025  3.603886
23  Jul.2025  3.557945

In [ ]:
df_purchase

        Date        TC
0   Mar.2023  3.777665
1   Abr.2023  3.763422
2   May.2023  3.686182
3   Jun.2023  3.648733
4   Jul.2023  3.599410
5   Ago.2023  3.695409
6   Sep.2023  3.728876
7   Oct.2023  3.843995
8   Nov.2023  3.758638
9   Dic.2023  3.730868
10  Ene.2024  3.738867
11  Feb.2024  3.825390
12  Mar.2024  3.706579
13  Abr.2024  3.712945
14  May.2024  3.729445
15  Jun.2024  3.784837
16  Jul.2024  3.762020
17  Ago.2024  3.740130
18  Sep.2024  3.766581
19  Oct.2024  3.752959
20  Nov.2024  3.777445
21  Dic.2024  3.733995
22  Ene.2025  3.745550
23  Feb.2025  3.695240

In [21]:
df_sale = df_sale.rename(columns={
    'Date': 'Fecha_Cambio',  # Rename 'Fecha' to 'Fecha_Cambio'
    'TC': 'TC_VENTA',   # Rename 'Tipo de Cambio' to 'TC_VENTA'
})

df_purchase = df_purchase.rename(columns={
    'Date': 'Fecha_Cambio',  # Rename 'Fecha' to 'Fecha_Cambio_1'
    'TC': 'TC_COMPRA',   # Rename 'Tipo de Cambio' to 'TC_COMPRA'
})

In [22]:
df_sale.head()
#df_purchase.head()

  Fecha_Cambio  TC_VENTA
0     Ago.2023  3.698445
1     Sep.2023  3.732010
2     Oct.2023  3.847014
3     Nov.2023  3.762095
4     Dic.2023  3.735089

In [23]:
# Concatenar (en lugar de append) los DataFrames de compra y venta
df = pd.concat([df_purchase, df_sale], axis=1)
#df = df.drop('Fecha_CambiO1', axis=1)
df

   Fecha_Cambio  TC_COMPRA Fecha_Cambio  TC_VENTA
0      Ago.2023   3.695409     Ago.2023  3.698445
1      Sep.2023   3.728876     Sep.2023  3.732010
2      Oct.2023   3.843995     Oct.2023  3.847014
3      Nov.2023   3.758638     Nov.2023  3.762095
4      Dic.2023   3.730868     Dic.2023  3.735089
5      Ene.2024   3.738867     Ene.2024  3.741910
6      Feb.2024   3.825390     Feb.2024  3.828952
7      Mar.2024   3.706579     Mar.2024  3.710037
8      Abr.2024   3.712945     Abr.2024  3.716700
9      May.2024   3.729445     May.2024  3.732877
10     Jun.2024   3.784837     Jun.2024  3.788379
11     Jul.2024   3.762020     Jul.2024  3.766110
12     Ago.2024   3.740130     Ago.2024  3.742925
13     Sep.2024   3.766581     Sep.2024  3.769895
14     Oct.2024   3.752959     Oct.2024  3.755814
15     Nov.2024   3.777445     Nov.2024  3.780265
16     Dic.2024   3.733995     Dic.2024  3.736558
17     Ene.2025   3.745550     Ene.2025  3.748255
18     Feb.2025   3.695240     Feb.2025  3.698170
19     Mar.2025   3.650686     Mar.2025  3.653448
20     Abr.2025   3.697855     Abr.2025  3.701260
21     May.2025   3.657990     May.2025  3.660862
22     Jun.2025   3.600300     Jun.2025  3.603886
23     Jul.2025   3.554875     Jul.2025  3.557945

In [24]:
df = df.loc[:, ~df.columns.duplicated(keep='first')]
df

   Fecha_Cambio  TC_COMPRA  TC_VENTA
0      Ago.2023   3.695409  3.698445
1      Sep.2023   3.728876  3.732010
2      Oct.2023   3.843995  3.847014
3      Nov.2023   3.758638  3.762095
4      Dic.2023   3.730868  3.735089
5      Ene.2024   3.738867  3.741910
6      Feb.2024   3.825390  3.828952
7      Mar.2024   3.706579  3.710037
8      Abr.2024   3.712945  3.716700
9      May.2024   3.729445  3.732877
10     Jun.2024   3.784837  3.788379
11     Jul.2024   3.762020  3.766110
12     Ago.2024   3.740130  3.742925
13     Sep.2024   3.766581  3.769895
14     Oct.2024   3.752959  3.755814
15     Nov.2024   3.777445  3.780265
16     Dic.2024   3.733995  3.736558
17     Ene.2025   3.745550  3.748255
18     Feb.2025   3.695240  3.698170
19     Mar.2025   3.650686  3.653448
20     Abr.2025   3.697855  3.701260
21     May.2025   3.657990  3.660862
22     Jun.2025   3.600300  3.603886
23     Jul.2025   3.554875  3.557945

In [ ]:
df.dtypes

Fecha_Cambio     object
TC_COMPRA       float64
TC_VENTA        float64
dtype: object

In [25]:
df = df.drop('Fecha_Cambio', axis=1)
df

    TC_COMPRA  TC_VENTA
0    3.695409  3.698445
1    3.728876  3.732010
2    3.843995  3.847014
3    3.758638  3.762095
4    3.730868  3.735089
5    3.738867  3.741910
6    3.825390  3.828952
7    3.706579  3.710037
8    3.712945  3.716700
9    3.729445  3.732877
10   3.784837  3.788379
11   3.762020  3.766110
12   3.740130  3.742925
13   3.766581  3.769895
14   3.752959  3.755814
15   3.777445  3.780265
16   3.733995  3.736558
17   3.745550  3.748255
18   3.695240  3.698170
19   3.650686  3.653448
20   3.697855  3.701260
21   3.657990  3.660862
22   3.600300  3.603886
23   3.554875  3.557945

In [26]:
date=['2023-03-01', '2023-04-01', '2023-05-01', '2023-06-01', '2023-07-01', 
 '2023-08-01', '2023-09-01', '2023-10-01', '2023-11-01', '2023-12-01', 
 '2024-01-01', '2024-02-01', '2024-03-01', '2024-04-01', '2024-05-01', 
 '2024-06-01', '2024-07-01', '2024-08-01', '2024-09-01', '2024-10-01', 
 '2024-11-01', '2024-12-01', '2025-01-01', '2025-02-01']

In [27]:
date1 = pd.DataFrame(date, columns=['Fecha'])

In [28]:
df['Fecha'] = date1
print(df.dtypes)
df

TC_COMPRA    float64
TC_VENTA     float64
Fecha         object
dtype: object

    TC_COMPRA  TC_VENTA       Fecha
0    3.695409  3.698445  2023-03-01
1    3.728876  3.732010  2023-04-01
2    3.843995  3.847014  2023-05-01
3    3.758638  3.762095  2023-06-01
4    3.730868  3.735089  2023-07-01
5    3.738867  3.741910  2023-08-01
6    3.825390  3.828952  2023-09-01
7    3.706579  3.710037  2023-10-01
8    3.712945  3.716700  2023-11-01
9    3.729445  3.732877  2023-12-01
10   3.784837  3.788379  2024-01-01
11   3.762020  3.766110  2024-02-01
12   3.740130  3.742925  2024-03-01
13   3.766581  3.769895  2024-04-01
14   3.752959  3.755814  2024-05-01
15   3.777445  3.780265  2024-06-01
16   3.733995  3.736558  2024-07-01
17   3.745550  3.748255  2024-08-01
18   3.695240  3.698170  2024-09-01
19   3.650686  3.653448  2024-10-01
20   3.697855  3.701260  2024-11-01
21   3.657990  3.660862  2024-12-01
22   3.600300  3.603886  2025-01-01
23   3.554875  3.557945  2025-02-01

In [29]:
df['Fecha'] = pd.to_datetime(df['Fecha'])
df.dtypes

TC_COMPRA           float64
TC_VENTA            float64
Fecha        datetime64[ns]
dtype: object

In [30]:
import matplotlib.pyplot as plt

# Create the plot
plt.figure(figsize=(10,6))
plt.plot(df['Fecha'], df['TC_COMPRA'], label='BUY RATE', color='blue', marker='o')
plt.plot(df['Fecha'], df['TC_VENTA'], label='SELL RATE', color='red', marker='x')

# Labels and title
plt.xlabel('Date')
plt.ylabel('Exchange Rate')
plt.title('Evolution of Buy and Sell Exchange Rates')

# Show legend
plt.legend()

# Save the plot as an image file
plt.savefig('plot.png')  # Save the plot as an image

# Display the plot (this might not work if there is no graphic support in your environment)
plt.show()

ModuleNotFoundError: No module named 'matplotlib'

#### APIS PRIVADAS

In [ ]:
api_key = "TU_API_KEY"  #API libre con llave
url = f"https://api.openweathermap.org/data/2.5/weather?q=Lima&appid={api_key}"
response = requests.get(url)
print(response.json())

In [ ]:
url = "https://estadisticas.bcrp.gob.pe/estadisticas/series/api/PD04640PD/json/2024-01-01/2024-12-31/esp"
response = requests.get(url)
data = response.json()
data

{'config': {'title': 'Tipo de cambio',
  'series': [{'name': 'Tipo de cambio - TC Sistema bancario SBS (S/ por US$) - Venta',
    'dec': '3'}]},
 'periods': [{'name': '03.Ene.24', 'values': ['3.738']},
  {'name': '04.Ene.24', 'values': ['3.74']},
  {'name': '05.Ene.24', 'values': ['3.723']},
  {'name': '08.Ene.24', 'values': ['3.719']},
  {'name': '09.Ene.24', 'values': ['3.708']},
  {'name': '10.Ene.24', 'values': ['3.704']},
  {'name': '11.Ene.24', 'values': ['3.703']},
  {'name': '12.Ene.24', 'values': ['3.696']},
  {'name': '15.Ene.24', 'values': ['3.704']},
  {'name': '16.Ene.24', 'values': ['3.718']},
  {'name': '17.Ene.24', 'values': ['3.739']},
  {'name': '18.Ene.24', 'values': ['3.742']},
  {'name': '19.Ene.24', 'values': ['3.743']},
  {'name': '22.Ene.24', 'values': ['3.746']},
  {'name': '23.Ene.24', 'values': ['3.755']},
  {'name': '24.Ene.24', 'values': ['3.76']},
  {'name': '25.Ene.24', 'values': ['3.765']},
  {'name': '26.Ene.24', 'values': ['3.786']},
  {'name': '29.Ene.24', 'values': ['3.807']},
  {'name': '30.Ene.24', 'values': ['3.813']},
  {'name': '31.Ene.24', 'values': ['3.808']},
  {'name': '01.Feb.24', 'values': ['3.808']},
  {'name': '02.Feb.24', 'values': ['3.829']},
  {'name': '05.Feb.24', 'values': ['3.852']},
  {'name': '06.Feb.24', 'values': ['3.858']},
  {'name': '07.Feb.24', 'values': ['3.868']},
  {'name': '08.Feb.24', 'values': ['3.854']},
  {'name': '09.Feb.24', 'values': ['3.868']},
  {'name': '12.Feb.24', 'values': ['3.869']},
  {'name': '13.Feb.24', 'values': ['3.883']},
  {'name': '14.Feb.24', 'values': ['3.877']},
  {'name': '15.Feb.24', 'values': ['3.87']},
  {'name': '16.Feb.24', 'values': ['3.844']},
  {'name': '19.Feb.24', 'values': ['3.807']},
  {'name': '20.Feb.24', 'values': ['3.784']},
  {'name': '21.Feb.24', 'values': ['3.797']},
  {'name': '22.Feb.24', 'values': ['3.807']},
  {'name': '23.Feb.24', 'values': ['3.799']},
  {'name': '26.Feb.24', 'values': ['3.803']},
  {'name': '27.Feb.24', 'values': ['3.793']},
  {'name': '28.Feb.24', 'values': ['3.797']},
  {'name': '29.Feb.24', 'values': ['3.782']},
  {'name': '01.Mar.24', 'values': ['3.773']},
  {'name': '04.Mar.24', 'values': ['3.771']},
  {'name': '05.Mar.24', 'values': ['3.77']},
  {'name': '06.Mar.24', 'values': ['3.736']},
  {'name': '07.Mar.24', 'values': ['3.726']},
  {'name': '08.Mar.24', 'values': ['3.696']},
  {'name': '11.Mar.24', 'values': ['3.692']},
  {'name': '12.Mar.24', 'values': ['3.695']},
  {'name': '13.Mar.24', 'values': ['3.671']},
  {'name': '14.Mar.24', 'values': ['3.677']},
  {'name': '15.Mar.24', 'values': ['3.692']},
  {'name': '18.Mar.24', 'values': ['3.698']},
  {'name': '19.Mar.24', 'values': ['3.703']},
  {'name': '20.Mar.24', 'values': ['3.696']},
  {'name': '21.Mar.24', 'values': ['3.701']},
  {'name': '22.Mar.24', 'values': ['3.694']},
  {'name': '25.Mar.24', 'values': ['3.707']},
  {'name': '26.Mar.24', 'values': ['3.727']},
  {'name': '27.Mar.24', 'values': ['3.721']},
  {'name': '28.Mar.24', 'values': ['n.d.']},
  {'name': '29.Mar.24', 'values': ['n.d.']},
  {'name': '01.Abr.24', 'values': ['3.734']},
  {'name': '02.Abr.24', 'values': ['3.711']},
  {'name': '03.Abr.24', 'values': ['3.694']},
  {'name': '04.Abr.24', 'values': ['3.685']},
  {'name': '05.Abr.24', 'values': ['3.691']},
  {'name': '08.Abr.24', 'values': ['3.681']},
  {'name': '09.Abr.24', 'values': ['3.693']},
  {'name': '10.Abr.24', 'values': ['3.71']},
  {'name': '11.Abr.24', 'values': ['3.711']},
  {'name': '12.Abr.24', 'values': ['3.707']},
  {'name': '15.Abr.24', 'values': ['3.725']},
  {'name': '16.Abr.24', 'values': ['3.755']},
  {'name': '17.Abr.24', 'values': ['3.749']},
  {'name': '18.Abr.24', 'values': ['3.744']},
  {'name': '19.Abr.24', 'values': ['3.702']},
  {'name': '22.Abr.24', 'values': ['3.701']},
  {'name': '23.Abr.24', 'values': ['3.701']},
  {'name': '24.Abr.24', 'values': ['3.724']},
  {'name': '25.Abr.24', 'values': ['3.745']},
  {'name': '26.Abr.24', 'values': ['3.756']},
  {'name': '29.Abr.24', 'values': ['3.734']},
  {'name': '30.Abr.24', 'values': ['3.752']},
  {'name': '01.May.24', 'values': ['n.d.']},
  {'name': '02.May.24', 'values': ['3.757']},
  {'name': '03.May.24', 'values': ['3.726']},
  {'name': '06.May.24', 'values': ['3.73']},
  {'name': '07.May.24', 'values': ['3.728']},
  {'name': '08.May.24', 'values': ['3.724']},
  {'name': '09.May.24', 'values': ['3.713']},
  {'name': '10.May.24', 'values': ['3.708']},
  {'name': '13.May.24', 'values': ['3.723']},
  {'name': '14.May.24', 'values': ['3.728']},
  {'name': '15.May.24', 'values': ['3.718']},
  {'name': '16.May.24', 'values': ['3.728']},
  {'name': '17.May.24', 'values': ['3.742']},
  {'name': '20.May.24', 'values': ['3.736']},
  {'name': '21.May.24', 'values': ['3.733']},
  {'name': '22.May.24', 'values': ['3.743']},
  {'name': '23.May.24', 'values': ['3.746']},
  {'name': '24.May.24', 'values': ['3.739']},
  {'name': '27.May.24', 'values': ['3.748']},
  {'name': '28.May.24', 'values': ['3.75']},
  {'name': '29.May.24', 'values': ['3.762']},
  {'name': '30.May.24', 'values': ['3.753']},
  {'name': '31.May.24', 'values': ['3.741']},
  {'name': '03.Jun.24', 'values': ['3.736']},
  {'name': '04.Jun.24', 'values': ['3.74']},
  {'name': '05.Jun.24', 'values': ['3.747']},
  {'name': '06.Jun.24', 'values': ['3.756']},
  {'name': '07.Jun.24', 'values': ['n.d.']},
  {'name': '10.Jun.24', 'values': ['3.781']},
  {'name': '11.Jun.24', 'values': ['3.787']},
  {'name': '12.Jun.24', 'values': ['3.772']},
  {'name': '13.Jun.24', 'values': ['3.777']},
  {'name': '14.Jun.24', 'values': ['3.776']},
  {'name': '17.Jun.24', 'values': ['3.796']},
  {'name': '18.Jun.24', 'values': ['3.789']},
  {'name': '19.Jun.24', 'values': ['3.818']},
  {'name': '20.Jun.24', 'values': ['3.814']},
  {'name': '21.Jun.24', 'values': ['3.806']},
  {'name': '24.Jun.24', 'values': ['3.805']},
  {'name': '25.Jun.24', 'values': ['3.817']},
  {'name': '26.Jun.24', 'values': ['3.822']},
  {'name': '27.Jun.24', 'values': ['3.825']},
  {'name': '28.Jun.24', 'values': ['3.837']},
  {'name': '01.Jul.24', 'values': ['3.851']},
  {'name': '02.Jul.24', 'values': ['3.833']},
  {'name': '03.Jul.24', 'values': ['3.802']},
  {'name': '04.Jul.24', 'values': ['3.802']},
  {'name': '05.Jul.24', 'values': ['3.797']},
  {'name': '08.Jul.24', 'values': ['3.797']},
  {'name': '09.Jul.24', 'values': ['3.789']},
  {'name': '10.Jul.24', 'values': ['3.785']},
  {'name': '11.Jul.24', 'values': ['3.771']},
  {'name': '12.Jul.24', 'values': ['3.74']},
  {'name': '15.Jul.24', 'values': ['3.733']},
  {'name': '16.Jul.24', 'values': ['3.725']},
  {'name': '17.Jul.24', 'values': ['3.723']},
  {'name': '18.Jul.24', 'values': ['3.735']},
  {'name': '19.Jul.24', 'values': ['3.743']},
  {'name': '22.Jul.24', 'values': ['3.758']},
  {'name': '23.Jul.24', 'values': ['n.d.']},
  {'name': '24.Jul.24', 'values': ['3.778']},
  {'name': '25.Jul.24', 'values': ['3.764']},
  {'name': '26.Jul.24', 'values': ['n.d.']},
  {'name': '29.Jul.24', 'values': ['n.d.']},
  {'name': '30.Jul.24', 'values': ['3.742']},
  {'name': '31.Jul.24', 'values': ['3.722']},
  {'name': '01.Ago.24', 'values': ['3.741']},
  {'name': '02.Ago.24', 'values': ['3.748']},
  {'name': '05.Ago.24', 'values': ['3.754']},
  {'name': '06.Ago.24', 'values': ['n.d.']},
  {'name': '07.Ago.24', 'values': ['3.74']},
  {'name': '08.Ago.24', 'values': ['3.732']},
  {'name': '09.Ago.24', 'values': ['3.731']},
  {'name': '12.Ago.24', 'values': ['3.747']},
  {'name': '13.Ago.24', 'values': ['3.75']},
  {'name': '14.Ago.24', 'values': ['3.744']},
  {'name': '15.Ago.24', 'values': ['3.737']},
  {'name': '16.Ago.24', 'values': ['3.748']},
  {'name': '19.Ago.24', 'values': ['3.74']},
  {'name': '20.Ago.24', 'values': ['3.747']},
  {'name': '21.Ago.24', 'values': ['3.744']},
  {'name': '22.Ago.24', 'values': ['3.76']},
  {'name': '23.Ago.24', 'values': ['3.748']},
  {'name': '26.Ago.24', 'values': ['3.759']},
  {'name': '27.Ago.24', 'values': ['3.748']},
  {'name': '28.Ago.24', 'values': ['3.743']},
  {'name': '29.Ago.24', 'values': ['3.75']},
  {'name': '30.Ago.24', 'values': ['n.d.']},
  {'name': '02.Set.24', 'values': ['3.768']},
  {'name': '03.Set.24', 'values': ['3.781']},
  {'name': '04.Set.24', 'values': ['3.797']},
  {'name': '05.Set.24', 'values': ['3.796']},
  {'name': '06.Set.24', 'values': ['3.781']},
  {'name': '09.Set.24', 'values': ['3.816']},
  {'name': '10.Set.24', 'values': ['3.823']},
  {'name': '11.Set.24', 'values': ['3.794']},
  {'name': '12.Set.24', 'values': ['3.772']},
  {'name': '13.Set.24', 'values': ['3.771']},
  {'name': '16.Set.24', 'values': ['3.788']},
  {'name': '17.Set.24', 'values': ['3.778']},
  {'name': '18.Set.24', 'values': ['3.764']},
  {'name': '19.Set.24', 'values': ['3.751']},
  {'name': '20.Set.24', 'values': ['3.754']},
  {'name': '23.Set.24', 'values': ['3.773']},
  {'name': '24.Set.24', 'values': ['3.768']},
  {'name': '25.Set.24', 'values': ['3.767']},
  {'name': '26.Set.24', 'values': ['3.737']},
  {'name': '27.Set.24', 'values': ['3.722']},
  {'name': '30.Set.24', 'values': ['3.714']},
  {'name': '01.Oct.24', 'values': ['3.718']},
  {'name': '02.Oct.24', 'values': ['3.721']},
  {'name': '03.Oct.24', 'values': ['3.73']},
  {'name': '04.Oct.24', 'values': ['3.734']},
  {'name': '07.Oct.24', 'values': ['3.744']},
  {'name': '08.Oct.24', 'values': ['n.d.']},
  {'name': '09.Oct.24', 'values': ['3.76']},
  {'name': '10.Oct.24', 'values': ['3.767']},
  {'name': '11.Oct.24', 'values': ['3.759']},
  {'name': '14.Oct.24', 'values': ['3.763']},
  {'name': '15.Oct.24', 'values': ['3.77']},
  {'name': '16.Oct.24', 'values': ['3.773']},
  {'name': '17.Oct.24', 'values': ['3.771']},
  {'name': '18.Oct.24', 'values': ['3.759']},
  {'name': '21.Oct.24', 'values': ['3.767']},
  {'name': '22.Oct.24', 'values': ['3.759']},
  {'name': '23.Oct.24', 'values': ['3.757']},
  {'name': '24.Oct.24', 'values': ['3.757']},
  {'name': '25.Oct.24', 'values': ['3.758']},
  {'name': '28.Oct.24', 'values': ['3.775']},
  {'name': '29.Oct.24', 'values': ['3.772']},
  {'name': '30.Oct.24', 'values': ['3.776']},
  {'name': '31.Oct.24', 'values': ['3.775']},
  {'name': '01.Nov.24', 'values': ['n.d.']},
  {'name': '04.Nov.24', 'values': ['3.774']},
  {'name': '05.Nov.24', 'values': ['3.778']},
  {'name': '06.Nov.24', 'values': ['3.787']},
  {'name': '07.Nov.24', 'values': ['3.76']},
  {'name': '08.Nov.24', 'values': ['3.769']},
  {'name': '11.Nov.24', 'values': ['3.781']},
  {'name': '12.Nov.24', 'values': ['3.788']},
  {'name': '13.Nov.24', 'values': ['3.8']},
  {'name': '14.Nov.24', 'values': ['3.805']},
  {'name': '15.Nov.24', 'values': ['3.807']},
  {'name': '18.Nov.24', 'values': ['3.799']},
  {'name': '19.Nov.24', 'values': ['3.798']},
  {'name': '20.Nov.24', 'values': ['3.798']},
  {'name': '21.Nov.24', 'values': ['3.797']},
  {'name': '22.Nov.24', 'values': ['3.798']},
  {'name': '25.Nov.24', 'values': ['3.783']},
  {'name': '26.Nov.24', 'values': ['3.773']},
  {'name': '27.Nov.24', 'values': ['3.762']},
  {'name': '28.Nov.24', 'values': ['3.759']},
  {'name': '29.Nov.24', 'values': ['3.745']},
  {'name': '02.Dic.24', 'values': ['3.766']},
  {'name': '03.Dic.24', 'values': ['3.749']},
  {'name': '04.Dic.24', 'values': ['3.74']},
  {'name': '05.Dic.24', 'values': ['3.735']},
  {'name': '06.Dic.24', 'values': ['3.727']},
  {'name': '09.Dic.24', 'values': ['n.d.']},
  {'name': '10.Dic.24', 'values': ['3.718']},
  {'name': '11.Dic.24', 'values': ['3.722']},
  {'name': '12.Dic.24', 'values': ['3.735']},
  {'name': '13.Dic.24', 'values': ['3.737']},
  {'name': '16.Dic.24', 'values': ['3.74']},
  {'name': '17.Dic.24', 'values': ['3.746']},
  {'name': '18.Dic.24', 'values': ['3.74']},
  {'name': '19.Dic.24', 'values': ['3.743']},
  {'name': '20.Dic.24', 'values': ['3.731']},
  {'name': '23.Dic.24', 'values': ['3.735']},
  {'name': '24.Dic.24', 'values': ['3.731']},
  {'name': '25.Dic.24', 'values': ['n.d.']},
  {'name': '26.Dic.24', 'values': ['3.748']},
  {'name': '27.Dic.24', 'values': ['3.75']},
  {'name': '30.Dic.24', 'values': ['3.77']}]}

# SCRAPING BCRP

In [42]:
import requests
import pandas as pd
import matplotlib.pyplot as plt
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

In [33]:
pip install matplotlib

Collecting matplotlib
  Downloading matplotlib-3.10.5-cp310-cp310-win_amd64.whl.metadata (11 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.2-cp310-cp310-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.59.1-cp310-cp310-win_amd64.whl.metadata (111 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.4.9-cp310-cp310-win_amd64.whl.metadata (6.4 kB)
Requirement already satisfied: numpy>=1.23 in c:\users\atara\anaconda3\envs\yelp_scraper\lib\site-packages (from matplotlib) (2.2.6)
Requirement already satisfied: packaging>=20.0 in c:\users\atara\anaconda3\envs\yelp_scraper\lib\site-packages (from matplotlib) (25.0)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-11.3.0-cp310-cp310-win_amd64.whl.metadata (9.2 kB)
Collecting pyparsing>=2.3.1 (from matplotlib)
  Downloading pyparsing-3.2.3-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\atara\anaconda3\envs\yelp_scraper\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\atara\anaconda3\envs\yelp_scraper\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.10.5-cp310-cp310-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.1 MB 1.1 MB/s eta 0:00:07
   -- ------------------------------------- 0.5/8.1 MB 1.1 MB/s eta 0:00:07
   -- ------------------------------------- 0.5/8.1 MB 1.1 MB/s eta 0:00:07
   -- ------------------------------------- 0.5/8.1 MB 1.1 MB/s eta 0:00:07
   -- ------------------------------------- 0.5/8.1 MB 1.1 MB/s eta 0:00:07
   --- ------------------------------------ 0.8/8.1 MB 360.6 kB/s eta 0:00:21
   --- ------------------------------------ 0.8/8.1 MB 360.6 kB/s eta 0:00:21
   ----- ---------------------------------- 1.0/8.1 MB 437.6 kB/s eta 0:00:17
   ----- ---------------------------------- 1.0/8.1 MB 437.6 kB/s eta 0:00:17
   ----- ---------------------------------- 1.0/8.1 MB 437.6 kB/s eta 0:00:17
   ------ --------------------------------- 1.3/8.1 MB 430.1 kB/s eta 0:00:16
   ------- -------------------------------- 1.6/8.1 MB 505.3 kB/s eta 0:00:13
   --------- ------------------------------ 1.8/8.1 MB 556.0 kB/s eta 0:00:12
   ---------- ----------------------------- 2.1/8.1 MB 599.1 kB/s eta 0:00:11
   ---------- ----------------------------- 2.1/8.1 MB 599.1 kB/s eta 0:00:11
   ----------- ---------------------------- 2.4/8.1 MB 593.8 kB/s eta 0:00:10
   ------------ --------------------------- 2.6/8.1 MB 613.8 kB/s eta 0:00:09
   -------------- ------------------------- 2.9/8.1 MB 655.4 kB/s eta 0:00:08
   --------------- ------------------------ 3.1/8.1 MB 685.9 kB/s eta 0:00:08
   ---------------- ----------------------- 3.4/8.1 MB 713.8 kB/s eta 0:00:07
   ------------------- -------------------- 3.9/8.1 MB 777.7 kB/s eta 0:00:06
   -------------------- ------------------- 4.2/8.1 MB 806.6 kB/s eta 0:00:05
   ---------------------- ----------------- 4.5/8.1 MB 836.2 kB/s eta 0:00:05
   ------------------------ --------------- 5.0/8.1 MB 880.3 kB/s eta 0:00:04
   ------------------------- -------------- 5.2/8.1 MB 903.0 kB/s eta 0:00:04
   ---------------------------- ----------- 5.8/8.1 MB 952.1 kB/s eta 0:00:03
   ----------------------------- ---------- 6.0/8.1 MB 973.9 kB/s eta 0:00:03
   ------------------------------- -------- 6.3/8.1 MB 991.8 kB/s eta 0:00:02
   -------------------------------- ------- 6.6/8.1 MB 1.0 MB/s eta 0:00:02
   --------------------------------- ------ 6.8/8.1 MB 1.0 MB/s eta 0:00:02
   ---------------------------------- ----- 7.1/8.1 MB 1.0 MB/s eta 0:00:02
   ------------------------------------ --- 7.3/8.1 MB 1.0 MB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.1 MB 1.0 MB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 1.0 MB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 1.0 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 994.5 kB/s eta 0:00:00
Downloading contourpy-1.3.2-cp310-cp310-win_amd64.whl (221 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.59.1-cp310-cp310-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.3 MB 1.2 MB/s eta 0:00:02
   ------------- -------------------------- 0.8/2.3 MB 1.1 MB/s eta 0:00:02
   ------------------ --------------------- 1.0/2.3 MB 1.2 MB/s eta 0:00:01
   ----------------------- ---------------- 1.3/2.3 MB 1.1 MB/s eta 0:00:01
   --------------------------- ------------ 1.6/2.3 MB 1.1 MB/s eta 0:00:01
   -------------------------------- ------- 1.8/2.3 MB 1.2 MB/s eta 0:00:01
   ---------------------------------------- 2.3/2.3 MB 1.2 MB/s eta 0:00:00
Downloading kiwisolver-1.4.9-cp310-cp310-win_amd64.whl (73 kB)
Downloading pillow-11.3.0-cp310-cp310-win_amd64.whl (7.0 MB)
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.0 MB ? eta -:--:--
   --- ------------------------------------ 0.5/7.0 MB 1.5 MB/s eta 0:00:05
   ---- ----------------------------------- 0.8/7.0 MB 1.6 MB/s eta 0:00:04
   ------ --------------------------------- 1.0/7.0 MB 1.5 MB/s eta 0:00:04
   ------- -------------------------------- 1.3/7.0 MB 1.3 MB/s eta 0:00:05
   ---------- ----------------------------- 1.8/7.0 MB 1.5 MB/s eta 0:00:04
   ------------ --------------------------- 2.1/7.0 MB 1.5 MB/s eta 0:00:04
   --------------- ------------------------ 2.6/7.0 MB 1.5 MB/s eta 0:00:03
   --------------- ------------------------ 2.6/7.0 MB 1.5 MB/s eta 0:00:03
   ------------------ --------------------- 3.1/7.0 MB 1.5 MB/s eta 0:00:03
   ------------------ --------------------- 3.1/7.0 MB 1.5 MB/s eta 0:00:03
   ------------------- -------------------- 3.4/7.0 MB 1.4 MB/s eta 0:00:03
   ------------------- -------------------- 3.4/7.0 MB 1.4 MB/s eta 0:00:03
   --------------------- ------------------ 3.7/7.0 MB 1.3 MB/s eta 0:00:03
   ---------------------- ----------------- 3.9/7.0 MB 1.3 MB/s eta 0:00:03
   ---------------------- ----------------- 3.9/7.0 MB 1.3 MB/s eta 0:00:03
   ---------------------- ----------------- 3.9/7.0 MB 1.3 MB/s eta 0:00:03
   ---------------------- ----------------- 3.9/7.0 MB 1.3 MB/s eta 0:00:03
   ------------------------- -------------- 4.5/7.0 MB 1.1 MB/s eta 0:00:03
   --------------------------- ------------ 4.7/7.0 MB 1.1 MB/s eta 0:00:03
   ------------------------------ --------- 5.2/7.0 MB 1.2 MB/s eta 0:00:02
   ------------------------------ --------- 5.2/7.0 MB 1.2 MB/s eta 0:00:02
   ------------------------------- -------- 5.5/7.0 MB 1.1 MB/s eta 0:00:02
   ------------------------------- -------- 5.5/7.0 MB 1.1 MB/s eta 0:00:02
   --------------------------------- ------ 5.8/7.0 MB 1.1 MB/s eta 0:00:02
   --------------------------------- ------ 5.8/7.0 MB 1.1 MB/s eta 0:00:02
   ---------------------------------- ----- 6.0/7.0 MB 1.1 MB/s eta 0:00:01
   ------------------------------------ --- 6.3/7.0 MB 1.0 MB/s eta 0:00:01
   ------------------------------------- -- 6.6/7.0 MB 1.0 MB/s eta 0:00:01
   ---------------------------------------  6.8/7.0 MB 1.0 MB/s eta 0:00:01
   ---------------------------------------- 7.0/7.0 MB 1.0 MB/s eta 0:00:00
Downloading pyparsing-3.2.3-py3-none-any.whl (111 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib

   ---------------------------------------- 0/7 [pyparsing]
   ---------------------------------------- 0/7 [pyparsing]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ---------------------- ----------------- 4/7 [cycler]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]Note: you may need to restart the kernel to use updated packages.

   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------------- 7/7 [matplotlib]

Successfully installed contourpy-1.3.2 cycler-0.12.1 fonttools-4.59.1 kiwisolver-1.4.9 matplotlib-3.10.5 pillow-11.3.0 pyparsing-3.2.3

  WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'c:\Users\atara\anaconda3\envs\yelp_scraper\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [45]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup

In [47]:
pip install beautifulsoup4 selenium

Requirement already satisfied: beautifulsoup4 in c:\users\atara\anaconda3\envs\yelp_scraper\lib\site-packages (4.13.5)
Requirement already satisfied: selenium in c:\users\atara\anaconda3\envs\yelp_scraper\lib\site-packages (4.23.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\atara\anaconda3\envs\yelp_scraper\lib\site-packages (from beautifulsoup4) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\atara\anaconda3\envs\yelp_scraper\lib\site-packages (from beautifulsoup4) (4.14.1)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\atara\anaconda3\envs\yelp_scraper\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (2.5.0)
Requirement already satisfied: trio~=0.17 in c:\users\atara\anaconda3\envs\yelp_scraper\lib\site-packages (from selenium) (0.30.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\atara\anaconda3\envs\yelp_scraper\lib\site-packages (from selenium) (0.12.2)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\atara\anaconda3\envs\yelp_scraper\lib\site-packages (from selenium) (2025.8.3)
Requirement already satisfied: websocket-client~=1.8 in c:\users\atara\anaconda3\envs\yelp_scraper\lib\site-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\atara\anaconda3\envs\yelp_scraper\lib\site-packages (from trio~=0.17->selenium) (25.3.0)
Requirement already satisfied: sortedcontainers in c:\users\atara\anaconda3\envs\yelp_scraper\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\atara\anaconda3\envs\yelp_scraper\lib\site-packages (from trio~=0.17->selenium) (3.10)
Requirement already satisfied: outcome in c:\users\atara\anaconda3\envs\yelp_scraper\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\atara\anaconda3\envs\yelp_scraper\lib\site-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\users\atara\anaconda3\envs\yelp_scraper\lib\site-packages (from trio~=0.17->selenium) (1.17.1)
Requirement already satisfied: exceptiongroup in c:\users\atara\anaconda3\envs\yelp_scraper\lib\site-packages (from trio~=0.17->selenium) (1.3.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\atara\anaconda3\envs\yelp_scraper\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\atara\anaconda3\envs\yelp_scraper\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\atara\anaconda3\envs\yelp_scraper\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.22)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\atara\anaconda3\envs\yelp_scraper\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.16.0)
Note: you may need to restart the kernel to use updated packages.

In [46]:
type(resultados)

NameError: name 'resultados' is not defined

In [50]:
# Configurar Selenium (ajusta la ruta del driver)
import time
driver = webdriver.Chrome()
driver.maximize_window()


# URL de la página que contiene los datos
url = "https://estadisticas.bcrp.gob.pe/estadisticas/series/mensuales/"  
driver.get(url)

# Esperar carga completa (puedes aumentar el tiempo si la web es lenta)
time.sleep(5)

# 🔹 Extraer HTML de la página (IMPORTANTE)
html = driver.page_source

# Cerrar el navegador
#driver.quit()

# Verificar que HTML se ha obtenido correctamente
if not html:
    raise ValueError("❌ Error: No se pudo obtener el HTML de la página.")

# Procesar con BeautifulSoup
soup = BeautifulSoup(html, 'html.parser')

# Extraer todos los enlaces con el patrón esperado
links = soup.find_all("a", href=lambda href: href and "/estadisticas/series/mensuales/resultados/" in href)

# 🔹 Extraer todas las categorías
categorias = soup.find_all("h2", class_="categoria_titulo")

# Lista para almacenar los resultados
resultados = []

# Iterar por cada categoría
for categoria in categorias:
    # Extraer el título de la categoría (quitando el contenido adicional)
    titulo_categoria = categoria.text.strip().split("\n")[0]  # Tomamos solo la primera línea del título

    # Buscar la siguiente tabla dentro de la categoría
    tabla = categoria.find_next("table", class_="series")
    
    # Si hay una tabla, extraemos los códigos y descripciones
    if tabla:
        filas = tabla.find_all("tr")[1:]  # Ignorar la cabecera
        for fila in filas:
            columnas = fila.find_all("td")
            if len(columnas) >= 3:  # Aseguramos que haya suficientes columnas
                codigo = columnas[1].text.strip()
                descripcion = columnas[2].text.strip()
                resultados.append((titulo_categoria, codigo, descripcion))

In [51]:
resultados

[('Cuentas monetarias de las sociedades creadoras de depósito',
  'PN00001MM',
  'Activos Externos Netos de Corto Plazo (millones S/)'),
 ('Cuentas monetarias de las sociedades creadoras de depósito',
  'PN00002MM',
  'Activos Externos Netos de Corto Plazo (millones US$)'),
 ('Cuentas monetarias de las sociedades creadoras de depósito',
  'PN00003MM',
  'Activos Externos Netos de Corto Plazo - Activos (millones US$)'),
 ('Cuentas monetarias de las sociedades creadoras de depósito',
  'PN00004MM',
  'Activos Externos Netos de Corto Plazo - Pasivos (millones US$)'),
 ('Cuentas monetarias de las sociedades creadoras de depósito',
  'PN00005MM',
  'Activos Externos Netos de Largo Plazo (millones S/)'),
 ('Cuentas monetarias de las sociedades creadoras de depósito',
  'PN00006MM',
  'Activos Externos Netos de Largo Plazo (millones US$)'),
 ('Cuentas monetarias de las sociedades creadoras de depósito',
  'PN00007MM',
  'Activos Internos Netos (millones S/)'),
 ('Cuentas monetarias de las sociedades creadoras de depósito',
  'PN00008MM',
  'Activos Internos Netos - Sector Público (millones S/)'),
 ('Cuentas monetarias de las sociedades creadoras de depósito',
  'PN00009MM',
  'Activos Internos Netos - Sector Público - MN (millones S/)'),
 ('Cuentas monetarias de las sociedades creadoras de depósito',
  'PN00010MM',
  'Activos Internos Netos - Sector Público - ME (millones S/)'),
 ('Cuentas monetarias de las sociedades creadoras de depósito',
  'PN00011MM',
  'Activos Internos Netos - Sector Público - ME (millones US$)'),
 ('Cuentas monetarias de las sociedades creadoras de depósito',
  'PN00012MM',
  'Activos Internos Netos - Crédito al Sector Privado (millones S/)'),
 ('Cuentas monetarias de las sociedades creadoras de depósito',
  'PN00013MM',
  'Activos Internos Netos - Crédito al Sector Privado - MN (millones S/)'),
 ('Cuentas monetarias de las sociedades creadoras de depósito',
  'PN00014MM',
  'Activos Internos Netos - Crédito al Sector Privado - ME (millones S/)'),
 ('Cuentas monetarias de las sociedades creadoras de depósito',
  'PN00015MM',
  'Activos Internos Netos - Crédito al Sector Privado - ME (millones US$)'),
 ('Cuentas monetarias de las sociedades creadoras de depósito',
  'PN00016MM',
  'Activos Internos Netos - Otras Cuentas (millones S/)'),
 ('Exportaciones por Departamento (Valores FOB en millones US$)',
  'RD38085BM',
  'Amazonas'),
 ('Exportaciones por Departamento (Valores FOB en millones US$)',
  'RD38086BM',
  'Ancash'),
 ('Exportaciones por Departamento (Valores FOB en millones US$)',
  'RD38087BM',
  'Apurimac'),
 ('Exportaciones por Departamento (Valores FOB en millones US$)',
  'RD38088BM',
  'Arequipa'),
 ('Exportaciones por Departamento (Valores FOB en millones US$)',
  'RD38089BM',
  'Ayacucho'),
 ('Exportaciones por Departamento (Valores FOB en millones US$)',
  'RD38090BM',
  'Cajamarca'),
 ('Exportaciones por Departamento (Valores FOB en millones US$)',
  'RD38091BM',
  'Callao'),
 ('Exportaciones por Departamento (Valores FOB en millones US$)',
  'RD38092BM',
  'Cusco'),
 ('Exportaciones por Departamento (Valores FOB en millones US$)',
  'RD38093BM',
  'Huancavelica'),
 ('Exportaciones por Departamento (Valores FOB en millones US$)',
  'RD38094BM',
  'Huánuco'),
 ('Exportaciones por Departamento (Valores FOB en millones US$)',
  'RD38095BM',
  'Ica'),
 ('Exportaciones por Departamento (Valores FOB en millones US$)',
  'RD38096BM',
  'Junín'),
 ('Exportaciones por Departamento (Valores FOB en millones US$)',
  'RD38097BM',
  'La Libertad'),
 ('Exportaciones por Departamento (Valores FOB en millones US$)',
  'RD38098BM',
  'Lambayeque'),
 ('Exportaciones por Departamento (Valores FOB en millones US$)',
  'RD38099BM',
  'Lima'),
 ('Exportaciones por Departamento (Valores FOB en millones US$)',
  'RD38100BM',
  'Loreto'),
 ('Exportaciones por Departamento (Valores FOB en millones US$)',
  'RD38101BM',
  'Madre de Dios'),
 ('Exportaciones por Departamento (Valores FOB en millones US$)',
  'RD38102BM',
  'Moquegua'),
 ('Exportaciones por Departamento (Valores FOB en millones US$)',
  'RD38103BM',
  'Pasco'),
 ('Exportaciones por Departamento (Valores FOB en millones US$)',
  'RD38104BM',
  'Piura'),
 ('Exportaciones por Departamento (Valores FOB en millones US$)',
  'RD38105BM',
  'Puno'),
 ('Exportaciones por Departamento (Valores FOB en millones US$)',
  'RD38106BM',
  'San Martín'),
 ('Exportaciones por Departamento (Valores FOB en millones US$)',
  'RD38107BM',
  'Tacna'),
 ('Exportaciones por Departamento (Valores FOB en millones US$)',
  'RD38108BM',
  'Tumbes'),
 ('Exportaciones por Departamento (Valores FOB en millones US$)',
  'RD38109BM',
  'Ucayali'),
 ('Exportaciones por Departamento (Valores FOB en millones US$)',
  'RD38110BM',
  'No registrado'),
 ('Exportaciones por Departamento (Valores FOB en millones US$)',
  'RD38111BM',
  'Total'),
 ('Liquidez de las sociedades creadoras de depósito (fin de periodo)',
  'PN00178MM',
  'Circulante (millones S/)'),
 ('Liquidez de las sociedades creadoras de depósito (fin de periodo)',
  'PN00181MM',
  'Dinero (millones S/)'),
 ('Liquidez de las sociedades creadoras de depósito (fin de periodo)',
  'PN00184MM',
  'Cuasidinero MN (millones S/)'),
 ('Liquidez de las sociedades creadoras de depósito (fin de periodo)',
  'PN00187MM',
  'Liquidez en Soles (millones S/)'),
 ('Liquidez de las sociedades creadoras de depósito (fin de periodo)',
  'PN00190MM',
  'Liquidez en Dólares (millones US$)'),
 ('Liquidez de las sociedades creadoras de depósito (fin de periodo)',
  'PN00193MM',
  'Liquidez Total a Tipo de Cambio Corriente (millones S/)'),
 ('Liquidez de las sociedades creadoras de depósito (fin de periodo)',
  'PN00196MM',
  'Liquidez Total a Tipo de Cambio Constante (millones S/)'),
 ('Liquidez de las sociedades creadoras de depósito (fin de periodo)',
  'PN00021MM',
  'Liquidez - MN - Dinero - Depósitos a la Vista (millones S/)'),
 ('Liquidez de las sociedades creadoras de depósito (fin de periodo)',
  'PN00023MM',
  'Liquidez - ME (millones S/)'),
 ('Liquidez de las sociedades creadoras de depósito (fin de periodo)',
  'PN00025MM',
  'Coeficiente de Dolarización de la Liquidez (%)'),
 ('Importaciones por Aduana (Valores FOB en millones US$)',
  'RD38112BM',
  'Tumbes'),
 ('Importaciones por Aduana (Valores FOB en millones US$)',
  'RD38113BM',
  'Talara'),
 ('Importaciones por Aduana (Valores FOB en millones US$)',
  'RD38114BM',
  'Paita'),
 ('Importaciones por Aduana (Valores FOB en millones US$)',
  'RD38115BM',
  'Chiclayo'),
 ('Importaciones por Aduana (Valores FOB en millones US$)',
  'RD38116BM',
  'Salaverry'),
 ('Importaciones por Aduana (Valores FOB en millones US$)',
  'RD38117BM',
  'Chimbote'),
 ('Importaciones por Aduana (Valores FOB en millones US$)',
  'RD38118BM',
  'Marítima Del Callao'),
 ('Importaciones por Aduana (Valores FOB en millones US$)',
  'RD38119BM',
  'Pisco'),
 ('Importaciones por Aduana (Valores FOB en millones US$)',
  'RD38120BM',
  'Mollendo Matarani'),
 ('Importaciones por Aduana (Valores FOB en millones US$)',
  'RD38121BM',
  'Arequipa'),
 ('Importaciones por Aduana (Valores FOB en millones US$)',
  'RD38122BM',
  'Ilo'),
 ('Importaciones por Aduana (Valores FOB en millones US$)',
  'RD38123BM',
  'Tacna'),
 ('Importaciones por Aduana (Valores FOB en millones US$)',
  'RD38124BM',
  'Puno'),
 ('Importaciones por Aduana (Valores FOB en millones US$)',
  'RD38125BM',
  'Cuzco'),
 ('Importaciones por Aduana (Valores FOB en millones US$)',
  'RD38126BM',
  'Pucallpa'),
 ('Importaciones por Aduana (Valores FOB en millones US$)',
  'RD38127BM',
  'Iquitos'),
 ('Importaciones por Aduana (Valores FOB en millones US$)',
  'RD38128BM',
  'Aérea Del Callao'),
 ('Importaciones por Aduana (Valores FOB en millones US$)',
  'RD38129BM',
  'Postal De Lima'),
 ('Importaciones por Aduana (Valores FOB en millones US$)',
  'RD38130BM',
  'Desaguadero'),
 ('Importaciones por Aduana (Valores FOB en millones US$)',
  'RD38131BM',
  'Tarapoto'),
 ('Importaciones por Aduana (Valores FOB en millones US$)',
  'RD38132BM',
  'Puerto Maldonado'),
 ('Importaciones por Aduana (Valores FOB en millones US$)',
  'RD38133BM',
  'La Tina'),
 ('Importaciones por Aduana (Valores FOB en millones US$)',
  'RD38134BM',
  'Dependencia Postal Arequipa'),
 ('Importaciones por Aduana (Valores FOB en millones US$)',
  'RD38135BM',
  'Otros'),
 ('Importaciones por Aduana (Valores FOB en millones US$)',
  'RD38136BM',
  'Total'),
 ('Liquidez de las sociedades creadoras de depósito - fin de periodo (var% mensual)',
  'PN00179MM',
  'Circulante'),
 ('Liquidez de las sociedades creadoras de depósito - fin de periodo (var% mensual)',
  'PN00182MM',
  'Dinero'),
 ('Liquidez de las sociedades creadoras de depósito - fin de periodo (var% mensual)',
  'PN00185MM',
  'Cuasidinero MN'),
 ('Liquidez de las sociedades creadoras de depósito - fin de periodo (var% mensual)',
  'PN00188MM',
  'Liquidez en Soles'),
 ('Liquidez de las sociedades creadoras de depósito - fin de periodo (var% mensual)',
  'PN00191MM',
  'Liquidez en Dólares'),
 ('Liquidez de las sociedades creadoras de depósito - fin de periodo (var% mensual)',
  'PN00194MM',
  'Liquidez Total - a Tipo de Cambio Corriente'),
 ('Liquidez de las sociedades creadoras de depósito - fin de periodo (var% mensual)',
  'PN00197MM',
  'Liquidez Total - a Tipo de Cambio Constante'),
 ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)',
  'RD38137BM',
  'Productos tradicionales'),
 ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)',
  'RD38138BM',
  'Productos tradicionales - Pesqueros'),
 ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)',
  'RD38139BM',
  'Productos tradicionales - Agrícolas'),
 ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)',
  'RD38140BM',
  'Productos tradicionales - Mineros'),
 ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)',
  'RD38141BM',
  'Productos tradicionales - Petróleo  y  gas natural'),
 ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)',
  'RD38142BM',
  'Productos no tradicionales'),
 ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)',
  'RD38143BM',
  'Productos no tradicionales - Agropecuarios'),
 ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)',
  'RD38144BM',
  'Productos no tradicionales - Pesqueros'),
 ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)',
  'RD38145BM',
  'Productos no tradicionales - Textiles'),
 ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)',
  'RD38146BM',
  'Productos no tradicionales - Maderas y papeles, y sus manufacturas'),
 ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)',
  'RD38147BM',
  'Productos no tradicionales - Químicos'),
 ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)',
  'RD38148BM',
  'Productos no tradicionales - Minerales  no  metálicos'),
 ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)',
  'RD38149BM',
  'Productos no tradicionales - Sidero-metalúrgicos y joyería'),
 ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)',
  'RD38150BM',
  'Productos no tradicionales - Metal-mecánicos'),
 ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)',
  'RD38151BM',
  'Productos no tradicionales - Otros'),
 ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)',
  'RD38152BM',
  'Otros'),
 ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)',
  'RD38153BM',
  'Total Exportaciones'),
 ('Liquidez de las sociedades creadoras de depósito - fin de periodo (var% 12 meses)',
  'PN00180MM',
  'Circulante'),
 ('Liquidez de las sociedades creadoras de depósito - fin de periodo (var% 12 meses)',
  'PN00183MM',
  'Dinero'),
 ('Liquidez de las sociedades creadoras de depósito - fin de periodo (var% 12 meses)',
  'PN00186MM',
  'Cuasidinero MN'),
 ('Liquidez de las sociedades creadoras de depósito - fin de periodo (var% 12 meses)',
  'PN00189MM',
  'Liquidez en Soles'),
 ('Liquidez de las sociedades creadoras de depósito - fin de periodo (var% 12 meses)',
  'PN00192MM',
  'Liquidez en Dólares'),
 ('Liquidez de las sociedades creadoras de depósito - fin de periodo (var% 12 meses)',
  'PN00195MM',
  'Liquidez Total - a Tipo de Cambio Corriente'),
 ('Liquidez de las sociedades creadoras de depósito - fin de periodo (var% 12 meses)',
  'PN00198MM',
  'Liquidez Total - a Tipo de Cambio Constante'),
 ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)',
  'RD38154BM',
  'Productos tradicionales'),
 ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)',
  'RD38155BM',
  'Productos tradicionales - Pesqueros'),
 ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)',
  'RD38156BM',
  'Productos tradicionales - Agrícolas'),
 ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)',
  'RD38157BM',
  'Productos tradicionales - Mineros'),
 ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)',
  'RD38158BM',
  'Productos tradicionales - Petróleo  y  gas natural'),
 ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)',
  'RD38159BM',
  'Productos no tradicionales'),
 ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)',
  'RD38160BM',
  'Productos no tradicionales - Agropecuarios'),
 ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)',
  'RD38161BM',
  'Productos no tradicionales - Pesqueros'),
 ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)',
  'RD38162BM',
  'Productos no tradicionales - Textiles'),
 ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)',
  'RD38163BM',
  'Productos no tradicionales - Maderas y papeles, y sus manufacturas'),
 ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)',
  'RD38164BM',
  'Productos no tradicionales - Químicos'),
 ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)',
  'RD38165BM',
  'Productos no tradicionales - Minerales  no  metálicos'),
 ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)',
  'RD38166BM',
  'Productos no tradicionales - Sidero-metalúrgicos y joyería'),
 ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)',
  'RD38167BM',
  'Productos no tradicionales - Metal-mecánicos'),
 ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)',
  'RD38168BM',
  'Productos no tradicionales - Otros'),
 ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)',
  'RD38169BM',
  'Otros'),
 ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)',
  'RD38170BM',
  'Total Exportaciones'),
 ('Crédito de las sociedades creadoras de depósito al sector privado (fin de periodo)',
  'PN00496MM',
  'Crédito MN (millones S/)'),
 ('Crédito de las sociedades creadoras de depósito al sector privado (fin de periodo)',
  'PN00499MM',
  'Crédito ME (millones US$)'),
 ('Crédito de las sociedades creadoras de depósito al sector privado (fin de periodo)',
  'PN00502MM',
  'Total a Tipo de Cambio Corriente (millones S/)'),
 ('Crédito de las sociedades creadoras de depósito al sector privado (fin de periodo)',
  'PN00505MM',
  'Total a Tipo de Cambio Constante (millones S/)'),
 ('Crédito de las sociedades creadoras de depósito al sector privado (fin de periodo)',
  'PN00508MM',
  'Total más Créditos de Sucursales en el Exterior a Tipo de Cambio Constante (millones S/)'),
 ('Crédito de las sociedades creadoras de depósito al sector privado (fin de periodo)',
  'PN00511MM',
  'Coeficiente de Dolarización (%)'),
 ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)',
  'RD38171BM',
  'Productos tradicionales'),
 ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)',
  'RD38172BM',
  'Productos tradicionales - Pesqueros'),
 ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)',
  'RD38173BM',
  'Productos tradicionales - Agrícolas'),
 ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)',
  'RD38174BM',
  'Productos tradicionales - Mineros'),
 ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)',
  'RD38175BM',
  'Productos tradicionales - Petróleo  y  gas natural'),
 ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)',
  'RD38176BM',
  'Productos no tradicionales'),
 ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)',
  'RD38177BM',
  'Productos no tradicionales - Agropecuarios'),
 ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)',
  'RD38178BM',
  'Productos no tradicionales - Pesqueros'),
 ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)',
  'RD38179BM',
  'Productos no tradicionales - Textiles'),
 ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)',
  'RD38180BM',
  'Productos no tradicionales - Maderas y papeles, y sus manufacturas'),
 ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)',
  'RD38181BM',
  'Productos no tradicionales - Químicos'),
 ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)',
  'RD38182BM',
  'Productos no tradicionales - Minerales  no  metálicos'),
 ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)',
  'RD38183BM',
  'Productos no tradicionales - Sidero-metalúrgicos y joyería'),
 ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)',
  'RD38184BM',
  'Productos no tradicionales - Metal-mecánicos'),
 ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)',
  'RD38185BM',
  'Productos no tradicionales - Otros'),
 ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)',
  'RD38186BM',
  'Otros'),
 ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)',
  'RD38187BM',
  'Total Exportaciones'),
 ('Crédito de las sociedades creadoras de depósito al sector privado - fin de periodo (var% mensual)',
  'PN00497MM',
  'Crédito MN'),
 ('Crédito de las sociedades creadoras de depósito al sector privado - fin de periodo (var% mensual)',
  'PN00500MM',
  'Crédito ME'),
 ('Crédito de las sociedades creadoras de depósito al sector privado - fin de periodo (var% mensual)',
  'PN00503MM',
  'Total a Tipo de Cambio Corriente'),
 ('Crédito de las sociedades creadoras de depósito al sector privado - fin de periodo (var% mensual)',
  'PN00506MM',
  'Total a Tipo de Cambio Constante'),
 ('Crédito de las sociedades creadoras de depósito al sector privado - fin de periodo (var% mensual)',
  'PN00509MM',
  'Total más Créditos de Sucursales en el Exterior a Tipo de Cambio Constante'),
 ('Exportaciones por grupo de productos de Arequipa (Valores FOB en millones US$)',
  'RD38188BM',
  'Productos tradicionales'),
 ('Exportaciones por grupo de productos de Arequipa (Valores FOB en millones US$)',
  'RD38189BM',
  'Productos tradicionales - Pesqueros'),
 ('Exportaciones por grupo de productos de Arequipa (Valores FOB en millones US$)',
  'RD38190BM',
  'Productos tradicionales - Agrícolas'),
 ('Exportaciones por grupo de productos de Arequipa (Valores FOB en millones US$)',
  'RD38191BM',
  'Productos tradicionales - Mineros'),
 ('Exportaciones por grupo de productos de Arequipa (Valores FOB en millones US$)',
  'RD38192BM',
  'Productos tradicionales - Petróleo  y  gas natural'),

In [52]:
# ✅ Convertir a DataFrame de Pandas
df1 = pd.DataFrame(resultados, columns=["Title","Código", "Descripción"])
df1

,Title,Código,Descripción
0,Cuentas monetarias de las sociedades creadoras...,PN00001MM,Activos Externos Netos de Corto Plazo (millone...
1,Cuentas monetarias de las sociedades creadoras...,PN00002MM,Activos Externos Netos de Corto Plazo (millone...
2,Cuentas monetarias de las sociedades creadoras...,PN00003MM,Activos Externos Netos de Corto Plazo - Activo...
3,Cuentas monetarias de las sociedades creadoras...,PN00004MM,Activos Externos Netos de Corto Plazo - Pasivo...
4,Cuentas monetarias de las sociedades creadoras...,PN00005MM,Activos Externos Netos de Largo Plazo (millone...
...,...,...,...
7100,Permanencia promedio en los establecimientos d...,RD13555DM,Tumbes - Nacionales
7101,Permanencia promedio en los establecimientos d...,RD13556DM,Tumbes - Extranjeros
7102,Permanencia promedio en los establecimientos d...,RD13557DM,Ucayali
7103,Permanencia promedio en los establecimientos d...,RD13558DM,Ucayali - Nacionales
7104,Permanencia promedio en los establecimientos d...,RD13559DM,Ucayali - Extranjeros

In [ ]:
#df1.to_excel("series_bcrp1.xlsx", index=False)
#df1

In [53]:
print(resultados)

[('Cuentas monetarias de las sociedades creadoras de depósito', 'PN00001MM', 'Activos Externos Netos de Corto Plazo (millones S/)'), ('Cuentas monetarias de las sociedades creadoras de depósito', 'PN00002MM', 'Activos Externos Netos de Corto Plazo (millones US$)'), ('Cuentas monetarias de las sociedades creadoras de depósito', 'PN00003MM', 'Activos Externos Netos de Corto Plazo - Activos (millones US$)'), ('Cuentas monetarias de las sociedades creadoras de depósito', 'PN00004MM', 'Activos Externos Netos de Corto Plazo - Pasivos (millones US$)'), ('Cuentas monetarias de las sociedades creadoras de depósito', 'PN00005MM', 'Activos Externos Netos de Largo Plazo (millones S/)'), ('Cuentas monetarias de las sociedades creadoras de depósito', 'PN00006MM', 'Activos Externos Netos de Largo Plazo (millones US$)'), ('Cuentas monetarias de las sociedades creadoras de depósito', 'PN00007MM', 'Activos Internos Netos (millones S/)'), ('Cuentas monetarias de las sociedades creadoras de depósito', 'PN00008MM', 'Activos Internos Netos - Sector Público (millones S/)'), ('Cuentas monetarias de las sociedades creadoras de depósito', 'PN00009MM', 'Activos Internos Netos - Sector Público - MN (millones S/)'), ('Cuentas monetarias de las sociedades creadoras de depósito', 'PN00010MM', 'Activos Internos Netos - Sector Público - ME (millones S/)'), ('Cuentas monetarias de las sociedades creadoras de depósito', 'PN00011MM', 'Activos Internos Netos - Sector Público - ME (millones US$)'), ('Cuentas monetarias de las sociedades creadoras de depósito', 'PN00012MM', 'Activos Internos Netos - Crédito al Sector Privado (millones S/)'), ('Cuentas monetarias de las sociedades creadoras de depósito', 'PN00013MM', 'Activos Internos Netos - Crédito al Sector Privado - MN (millones S/)'), ('Cuentas monetarias de las sociedades creadoras de depósito', 'PN00014MM', 'Activos Internos Netos - Crédito al Sector Privado - ME (millones S/)'), ('Cuentas monetarias de las sociedades creadoras de depósito', 'PN00015MM', 'Activos Internos Netos - Crédito al Sector Privado - ME (millones US$)'), ('Cuentas monetarias de las sociedades creadoras de depósito', 'PN00016MM', 'Activos Internos Netos - Otras Cuentas (millones S/)'), ('Exportaciones por Departamento (Valores FOB en millones US$)', 'RD38085BM', 'Amazonas'), ('Exportaciones por Departamento (Valores FOB en millones US$)', 'RD38086BM', 'Ancash'), ('Exportaciones por Departamento (Valores FOB en millones US$)', 'RD38087BM', 'Apurimac'), ('Exportaciones por Departamento (Valores FOB en millones US$)', 'RD38088BM', 'Arequipa'), ('Exportaciones por Departamento (Valores FOB en millones US$)', 'RD38089BM', 'Ayacucho'), ('Exportaciones por Departamento (Valores FOB en millones US$)', 'RD38090BM', 'Cajamarca'), ('Exportaciones por Departamento (Valores FOB en millones US$)', 'RD38091BM', 'Callao'), ('Exportaciones por Departamento (Valores FOB en millones US$)', 'RD38092BM', 'Cusco'), ('Exportaciones por Departamento (Valores FOB en millones US$)', 'RD38093BM', 'Huancavelica'), ('Exportaciones por Departamento (Valores FOB en millones US$)', 'RD38094BM', 'Huánuco'), ('Exportaciones por Departamento (Valores FOB en millones US$)', 'RD38095BM', 'Ica'), ('Exportaciones por Departamento (Valores FOB en millones US$)', 'RD38096BM', 'Junín'), ('Exportaciones por Departamento (Valores FOB en millones US$)', 'RD38097BM', 'La Libertad'), ('Exportaciones por Departamento (Valores FOB en millones US$)', 'RD38098BM', 'Lambayeque'), ('Exportaciones por Departamento (Valores FOB en millones US$)', 'RD38099BM', 'Lima'), ('Exportaciones por Departamento (Valores FOB en millones US$)', 'RD38100BM', 'Loreto'), ('Exportaciones por Departamento (Valores FOB en millones US$)', 'RD38101BM', 'Madre de Dios'), ('Exportaciones por Departamento (Valores FOB en millones US$)', 'RD38102BM', 'Moquegua'), ('Exportaciones por Departamento (Valores FOB en millones US$)', 'RD38103BM', 'Pasco'), ('Exportaciones por Departamento (Valores FOB en millones US$)', 'RD38104BM', 'Piura'), ('Exportaciones por Departamento (Valores FOB en millones US$)', 'RD38105BM', 'Puno'), ('Exportaciones por Departamento (Valores FOB en millones US$)', 'RD38106BM', 'San Martín'), ('Exportaciones por Departamento (Valores FOB en millones US$)', 'RD38107BM', 'Tacna'), ('Exportaciones por Departamento (Valores FOB en millones US$)', 'RD38108BM', 'Tumbes'), ('Exportaciones por Departamento (Valores FOB en millones US$)', 'RD38109BM', 'Ucayali'), ('Exportaciones por Departamento (Valores FOB en millones US$)', 'RD38110BM', 'No registrado'), ('Exportaciones por Departamento (Valores FOB en millones US$)', 'RD38111BM', 'Total'), ('Liquidez de las sociedades creadoras de depósito (fin de periodo)', 'PN00178MM', 'Circulante (millones S/)'), ('Liquidez de las sociedades creadoras de depósito (fin de periodo)', 'PN00181MM', 'Dinero (millones S/)'), ('Liquidez de las sociedades creadoras de depósito (fin de periodo)', 'PN00184MM', 'Cuasidinero MN (millones S/)'), ('Liquidez de las sociedades creadoras de depósito (fin de periodo)', 'PN00187MM', 'Liquidez en Soles (millones S/)'), ('Liquidez de las sociedades creadoras de depósito (fin de periodo)', 'PN00190MM', 'Liquidez en Dólares (millones US$)'), ('Liquidez de las sociedades creadoras de depósito (fin de periodo)', 'PN00193MM', 'Liquidez Total a Tipo de Cambio Corriente (millones S/)'), ('Liquidez de las sociedades creadoras de depósito (fin de periodo)', 'PN00196MM', 'Liquidez Total a Tipo de Cambio Constante (millones S/)'), ('Liquidez de las sociedades creadoras de depósito (fin de periodo)', 'PN00021MM', 'Liquidez - MN - Dinero - Depósitos a la Vista (millones S/)'), ('Liquidez de las sociedades creadoras de depósito (fin de periodo)', 'PN00023MM', 'Liquidez - ME (millones S/)'), ('Liquidez de las sociedades creadoras de depósito (fin de periodo)', 'PN00025MM', 'Coeficiente de Dolarización de la Liquidez (%)'), ('Importaciones por Aduana (Valores FOB en millones US$)', 'RD38112BM', 'Tumbes'), ('Importaciones por Aduana (Valores FOB en millones US$)', 'RD38113BM', 'Talara'), ('Importaciones por Aduana (Valores FOB en millones US$)', 'RD38114BM', 'Paita'), ('Importaciones por Aduana (Valores FOB en millones US$)', 'RD38115BM', 'Chiclayo'), ('Importaciones por Aduana (Valores FOB en millones US$)', 'RD38116BM', 'Salaverry'), ('Importaciones por Aduana (Valores FOB en millones US$)', 'RD38117BM', 'Chimbote'), ('Importaciones por Aduana (Valores FOB en millones US$)', 'RD38118BM', 'Marítima Del Callao'), ('Importaciones por Aduana (Valores FOB en millones US$)', 'RD38119BM', 'Pisco'), ('Importaciones por Aduana (Valores FOB en millones US$)', 'RD38120BM', 'Mollendo Matarani'), ('Importaciones por Aduana (Valores FOB en millones US$)', 'RD38121BM', 'Arequipa'), ('Importaciones por Aduana (Valores FOB en millones US$)', 'RD38122BM', 'Ilo'), ('Importaciones por Aduana (Valores FOB en millones US$)', 'RD38123BM', 'Tacna'), ('Importaciones por Aduana (Valores FOB en millones US$)', 'RD38124BM', 'Puno'), ('Importaciones por Aduana (Valores FOB en millones US$)', 'RD38125BM', 'Cuzco'), ('Importaciones por Aduana (Valores FOB en millones US$)', 'RD38126BM', 'Pucallpa'), ('Importaciones por Aduana (Valores FOB en millones US$)', 'RD38127BM', 'Iquitos'), ('Importaciones por Aduana (Valores FOB en millones US$)', 'RD38128BM', 'Aérea Del Callao'), ('Importaciones por Aduana (Valores FOB en millones US$)', 'RD38129BM', 'Postal De Lima'), ('Importaciones por Aduana (Valores FOB en millones US$)', 'RD38130BM', 'Desaguadero'), ('Importaciones por Aduana (Valores FOB en millones US$)', 'RD38131BM', 'Tarapoto'), ('Importaciones por Aduana (Valores FOB en millones US$)', 'RD38132BM', 'Puerto Maldonado'), ('Importaciones por Aduana (Valores FOB en millones US$)', 'RD38133BM', 'La Tina'), ('Importaciones por Aduana (Valores FOB en millones US$)', 'RD38134BM', 'Dependencia Postal Arequipa'), ('Importaciones por Aduana (Valores FOB en millones US$)', 'RD38135BM', 'Otros'), ('Importaciones por Aduana (Valores FOB en millones US$)', 'RD38136BM', 'Total'), ('Liquidez de las sociedades creadoras de depósito - fin de periodo (var% mensual)', 'PN00179MM', 'Circulante'), ('Liquidez de las sociedades creadoras de depósito - fin de periodo (var% mensual)', 'PN00182MM', 'Dinero'), ('Liquidez de las sociedades creadoras de depósito - fin de periodo (var% mensual)', 'PN00185MM', 'Cuasidinero MN'), ('Liquidez de las sociedades creadoras de depósito - fin de periodo (var% mensual)', 'PN00188MM', 'Liquidez en Soles'), ('Liquidez de las sociedades creadoras de depósito - fin de periodo (var% mensual)', 'PN00191MM', 'Liquidez en Dólares'), ('Liquidez de las sociedades creadoras de depósito - fin de periodo (var% mensual)', 'PN00194MM', 'Liquidez Total - a Tipo de Cambio Corriente'), ('Liquidez de las sociedades creadoras de depósito - fin de periodo (var% mensual)', 'PN00197MM', 'Liquidez Total - a Tipo de Cambio Constante'), ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)', 'RD38137BM', 'Productos tradicionales'), ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)', 'RD38138BM', 'Productos tradicionales - Pesqueros'), ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)', 'RD38139BM', 'Productos tradicionales - Agrícolas'), ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)', 'RD38140BM', 'Productos tradicionales - Mineros'), ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)', 'RD38141BM', 'Productos tradicionales - Petróleo  y  gas natural'), ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)', 'RD38142BM', 'Productos no tradicionales'), ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)', 'RD38143BM', 'Productos no tradicionales - Agropecuarios'), ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)', 'RD38144BM', 'Productos no tradicionales - Pesqueros'), ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)', 'RD38145BM', 'Productos no tradicionales - Textiles'), ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)', 'RD38146BM', 'Productos no tradicionales - Maderas y papeles, y sus manufacturas'), ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)', 'RD38147BM', 'Productos no tradicionales - Químicos'), ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)', 'RD38148BM', 'Productos no tradicionales - Minerales  no  metálicos'), ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)', 'RD38149BM', 'Productos no tradicionales - Sidero-metalúrgicos y joyería'), ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)', 'RD38150BM', 'Productos no tradicionales - Metal-mecánicos'), ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)', 'RD38151BM', 'Productos no tradicionales - Otros'), ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)', 'RD38152BM', 'Otros'), ('Exportaciones por grupo de productos de Amazonas (Valores FOB en millones US$)', 'RD38153BM', 'Total Exportaciones'), ('Liquidez de las sociedades creadoras de depósito - fin de periodo (var% 12 meses)', 'PN00180MM', 'Circulante'), ('Liquidez de las sociedades creadoras de depósito - fin de periodo (var% 12 meses)', 'PN00183MM', 'Dinero'), ('Liquidez de las sociedades creadoras de depósito - fin de periodo (var% 12 meses)', 'PN00186MM', 'Cuasidinero MN'), ('Liquidez de las sociedades creadoras de depósito - fin de periodo (var% 12 meses)', 'PN00189MM', 'Liquidez en Soles'), ('Liquidez de las sociedades creadoras de depósito - fin de periodo (var% 12 meses)', 'PN00192MM', 'Liquidez en Dólares'), ('Liquidez de las sociedades creadoras de depósito - fin de periodo (var% 12 meses)', 'PN00195MM', 'Liquidez Total - a Tipo de Cambio Corriente'), ('Liquidez de las sociedades creadoras de depósito - fin de periodo (var% 12 meses)', 'PN00198MM', 'Liquidez Total - a Tipo de Cambio Constante'), ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)', 'RD38154BM', 'Productos tradicionales'), ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)', 'RD38155BM', 'Productos tradicionales - Pesqueros'), ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)', 'RD38156BM', 'Productos tradicionales - Agrícolas'), ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)', 'RD38157BM', 'Productos tradicionales - Mineros'), ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)', 'RD38158BM', 'Productos tradicionales - Petróleo  y  gas natural'), ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)', 'RD38159BM', 'Productos no tradicionales'), ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)', 'RD38160BM', 'Productos no tradicionales - Agropecuarios'), ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)', 'RD38161BM', 'Productos no tradicionales - Pesqueros'), ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)', 'RD38162BM', 'Productos no tradicionales - Textiles'), ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)', 'RD38163BM', 'Productos no tradicionales - Maderas y papeles, y sus manufacturas'), ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)', 'RD38164BM', 'Productos no tradicionales - Químicos'), ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)', 'RD38165BM', 'Productos no tradicionales - Minerales  no  metálicos'), ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)', 'RD38166BM', 'Productos no tradicionales - Sidero-metalúrgicos y joyería'), ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)', 'RD38167BM', 'Productos no tradicionales - Metal-mecánicos'), ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)', 'RD38168BM', 'Productos no tradicionales - Otros'), ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)', 'RD38169BM', 'Otros'), ('Exportaciones por grupo de productos de Ancash (Valores FOB en millones US$)', 'RD38170BM', 'Total Exportaciones'), ('Crédito de las sociedades creadoras de depósito al sector privado (fin de periodo)', 'PN00496MM', 'Crédito MN (millones S/)'), ('Crédito de las sociedades creadoras de depósito al sector privado (fin de periodo)', 'PN00499MM', 'Crédito ME (millones US$)'), ('Crédito de las sociedades creadoras de depósito al sector privado (fin de periodo)', 'PN00502MM', 'Total a Tipo de Cambio Corriente (millones S/)'), ('Crédito de las sociedades creadoras de depósito al sector privado (fin de periodo)', 'PN00505MM', 'Total a Tipo de Cambio Constante (millones S/)'), ('Crédito de las sociedades creadoras de depósito al sector privado (fin de periodo)', 'PN00508MM', 'Total más Créditos de Sucursales en el Exterior a Tipo de Cambio Constante (millones S/)'), ('Crédito de las sociedades creadoras de depósito al sector privado (fin de periodo)', 'PN00511MM', 'Coeficiente de Dolarización (%)'), ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)', 'RD38171BM', 'Productos tradicionales'), ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)', 'RD38172BM', 'Productos tradicionales - Pesqueros'), ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)', 'RD38173BM', 'Productos tradicionales - Agrícolas'), ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)', 'RD38174BM', 'Productos tradicionales - Mineros'), ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)', 'RD38175BM', 'Productos tradicionales - Petróleo  y  gas natural'), ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)', 'RD38176BM', 'Productos no tradicionales'), ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)', 'RD38177BM', 'Productos no tradicionales - Agropecuarios'), ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)', 'RD38178BM', 'Productos no tradicionales - Pesqueros'), ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)', 'RD38179BM', 'Productos no tradicionales - Textiles'), ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)', 'RD38180BM', 'Productos no tradicionales - Maderas y papeles, y sus manufacturas'), ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)', 'RD38181BM', 'Productos no tradicionales - Químicos'), ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)', 'RD38182BM', 'Productos no tradicionales - Minerales  no  metálicos'), ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)', 'RD38183BM', 'Productos no tradicionales - Sidero-metalúrgicos y joyería'), ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)', 'RD38184BM', 'Productos no tradicionales - Metal-mecánicos'), ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)', 'RD38185BM', 'Productos no tradicionales - Otros'), ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)', 'RD38186BM', 'Otros'), ('Exportaciones por grupo de productos de Apurimac (Valores FOB en millones US$)', 'RD38187BM', 'Total Exportaciones'), ('Crédito de las sociedades creadoras de depósito al sector privado - fin de periodo (var% mensual)', 'PN00497MM', 'Crédito MN'), ('Crédito de las sociedades creadoras de depósito al sector privado - fin de periodo (var% mensual)', 'PN00500MM', 'Crédito ME'), ('Crédito de las sociedades creadoras de depósito al sector privado - fin de periodo (var% mensual)', 'PN00503MM', 'Total a Tipo de Cambio Corriente'), ('Crédito de las sociedades creadoras de depósito al sector privado - fin de periodo (var% mensual)', 'PN00506MM', 'Total a Tipo de Cambio Constante'), ('Crédito de las sociedades creadoras de depósito al sector privado - fin de periodo (var% mensual)', 'PN00509MM', 'Total más Créditos de Sucursales en el Exterior a Tipo de Cambio Constante'), ('Exportaciones por grupo de productos de Arequipa (Valores FOB en millones US$)', 'RD38188BM', 'Productos tradicionales'), ('Exportaciones por grupo de productos de Arequipa (Valores FOB en millones US$)', 'RD38189BM', 'Productos tradicionales - Pesqueros'), ('Exportaciones por grupo de productos de Arequipa (Valores FOB en millones US$)', 'RD38190BM', 'Productos tradicionales - Agrícolas'), ('Exportaciones por grupo de productos de Arequipa (Valores FOB en millones US$)', 'RD38191BM', 'Productos tradicionales - Mineros'), ('Exportaciones por grupo de productos de Arequipa (Valores FOB en millones US$)', 'RD38192BM', 'Productos tradicionales - Petróleo  y  gas natural'), ('Exportaciones por grupo de productos de Arequipa (Valores FOB en millones US$)', 'RD38193BM', 'Productos no tradicionales'), ('Exportaciones por grupo de productos de Arequipa (Valores FOB en millones US$)', 'RD38194BM', 'Productos no tradicionales - Agropecuarios'), ('Exportaciones por grupo de productos de Arequipa (Valores FOB en millones US$)', 'RD38195BM', 'Productos no tradicionales - Pesqueros'), ('Exportaciones por grupo de productos de Arequipa (Valores FOB en millones US$)', 'RD38196BM', 'Productos no tradicionales - Textiles'), ('Exportaciones por grupo de productos de Arequipa (Valores FOB en millones US$)', 'RD38197BM', 'Productos no tradicionales - Maderas y papeles, y sus manufacturas'), ('Exportaciones por grupo de productos de Arequipa (Valores FOB en millones US$)', 'RD38198BM', 'Productos no tra

In [ ]:
https://estadisticas.bcrp.gob.pe/estadisticas/series/mensuales/resultados/PN00001MM/html

In [ ]:
https://estadisticas.bcrp.gob.pe/estadisticas/series/api/RD38099BM/json/2000-7/2025-2

In [ ]:
https://estadisticas.bcrp.gob.pe/estadisticas/series/api/PN01288PM-PN01289PM/json/2016-1/2022-5

In [ ]:
import requests
import pandas as pd

class BCRPAPI:
    BASE_URL = "https://estadisticas.bcrp.gob.pe/estadisticas/series/api/"
    
    def __init__(self, series_code):
        self.series_code = series_code
    
    def get_data(self):
        url = f"{self.BASE_URL}{self.series_code}/json/"
        response = requests.get(url)
        
        if response.status_code == 200:
            try:
                data = response.json()
            except requests.exceptions.JSONDecodeError:
                print("Error: La respuesta de la API no es un JSON válido.")
                print("Contenido de la respuesta:", response.text)
                return None
            
            if "periods" in data and isinstance(data["periods"], list):
                fechas = [item["name"] for item in data["periods"]]
                valores = [float(item["values"][0]) if item["values"] else None for item in data["periods"]]
                df = pd.DataFrame({"Fecha": fechas, "Valor": valores})
                df = df.sort_values(by="Fecha", ascending=True).reset_index(drop=True)  # Ordenar por fecha
                return df
            else:
                print("No se encontraron datos para la serie.")
                return None
        else:
            print("Error al obtener datos, código:", response.status_code)
            print("Respuesta:", response.text)
            return None

# Ejemplo de uso con PN00001MM
bcrp = BCRPAPI("RD38099BM")
data = bcrp.get_data()
if data is not None:
    print(data)

       Fecha        Valor
0   Abr.2021   939.310600
1   Abr.2022  1412.030918
2   Ago.2021   944.104852
3   Ago.2022  1365.175863
4   Dic.2021  1606.840010
5   Dic.2022  1111.582786
6   Ene.2021   856.234324
7   Ene.2022  1426.617969
8   Feb.2021   817.736355
9   Feb.2022  1385.373690
10  Jul.2021  1037.907537
11  Jul.2022   934.385254
12  Jun.2021   939.950209
13  Jun.2022  1314.284147
14  Mar.2021   838.413670
15  Mar.2022  1696.535373
16  May.2021   968.769342
17  May.2022  1201.654759
18  Nov.2021  1526.271448
19  Nov.2022   965.991694
20  Oct.2021  1352.888938
21  Oct.2022   973.071690
22  Sep.2021  1283.096379
23  Sep.2022  1244.326950

In [ ]:
import requests
import pandas as pd

class BCRPAPI:
    BASE_URL = "https://estadisticas.bcrp.gob.pe/estadisticas/series/api/"
    
    def __init__(self, series_code):
        self.series_code = series_code
    
    def get_data(self):
        url = f"{self.BASE_URL}{self.series_code}/json"
        response = requests.get(url)
        
        if response.status_code == 200:
            data = response.json()
            print("Respuesta de la API:", data)  # Debug: Imprimir JSON recibido
            
            if "periods" in data:
                fechas = [item["name"] for item in data["periods"]]
                valores = [float(item["values"][0] or 0) for item in data["periods"]]
                return pd.DataFrame({"Fecha": fechas, "Valor": valores})
            else:
                print("La clave 'periods' no está en la respuesta")
                return None
        else:
            print("Error al obtener datos, código:", response.status_code)
            return None

# Ejemplo de uso
bcrp = BCRPAPI("RD13558DM")
data = bcrp.get_data()
print(data)

Respuesta de la API: {'config': {'title': 'Permanencia promedio en los establecimientos de hospedaje (número de días)', 'series': [{'name': 'Permanencia promedio en los establecimientos de hospedaje (número de días) - Ucayali - Nacionales', 'dec': '1'}]}, 'periods': [{'name': 'Ene.2018', 'values': ['1.89']}, {'name': 'Feb.2018', 'values': ['2.02']}, {'name': 'Mar.2018', 'values': ['1.92']}, {'name': 'Abr.2018', 'values': ['1.94']}, {'name': 'May.2018', 'values': ['1.83']}, {'name': 'Jun.2018', 'values': ['1.83']}, {'name': 'Jul.2018', 'values': ['1.83']}, {'name': 'Ago.2018', 'values': ['1.74']}, {'name': 'Sep.2018', 'values': ['1.95']}, {'name': 'Oct.2018', 'values': ['1.89']}, {'name': 'Nov.2018', 'values': ['1.85']}, {'name': 'Dic.2018', 'values': ['1.74']}, {'name': 'Ene.2019', 'values': ['1.81']}, {'name': 'Feb.2019', 'values': ['1.82']}, {'name': 'Mar.2019', 'values': ['1.66']}, {'name': 'Abr.2019', 'values': ['1.69']}, {'name': 'May.2019', 'values': ['1.72']}, {'name': 'Jun.2019', 'values': ['1.64']}, {'name': 'Jul.2019', 'values': ['1.79']}, {'name': 'Ago.2019', 'values': ['1.61']}, {'name': 'Sep.2019', 'values': ['1.72']}, {'name': 'Oct.2019', 'values': ['1.78']}, {'name': 'Nov.2019', 'values': ['1.93']}, {'name': 'Dic.2019', 'values': ['1.72']}]}
       Fecha  Valor
0   Ene.2018   1.89
1   Feb.2018   2.02
2   Mar.2018   1.92
3   Abr.2018   1.94
4   May.2018   1.83
5   Jun.2018   1.83
6   Jul.2018   1.83
7   Ago.2018   1.74
8   Sep.2018   1.95
9   Oct.2018   1.89
10  Nov.2018   1.85
11  Dic.2018   1.74
12  Ene.2019   1.81
13  Feb.2019   1.82
14  Mar.2019   1.66
15  Abr.2019   1.69
16  May.2019   1.72
17  Jun.2019   1.64
18  Jul.2019   1.79
19  Ago.2019   1.61
20  Sep.2019   1.72
21  Oct.2019   1.78
22  Nov.2019   1.93
23  Dic.2019   1.72

In [ ]:
import requests
import pandas as pd

class BCRPAPI:
    BASE_URL = "https://estadisticas.bcrp.gob.pe/estadisticas/series/api/"
    
    def __init__(self, series_code):
        self.series_code = series_code
    
    def get_data(self):
        url = f"{self.BASE_URL}{self.series_code}/json"
        response = requests.get(url)
        
        if response.status_code == 200:
            data = response.json()
            print("Respuesta de la API:", data)  # Debug: Imprimir JSON recibido
            
            if "periods" in data:
                fechas = [item["name"] for item in data["periods"]]
                valores = [float(item["values"][0] or 0) for item in data["periods"]]
                return pd.DataFrame({"Fecha": fechas, "Valor": valores})
            else:
                print("La clave 'periods' no está en la respuesta")
                return None
        else:
            print("Error al obtener datos, código:", response.status_code)
            return None

# Ejemplo de uso
bcrp = BCRPAPI("PN00001MM")
data = bcrp.get_data()
print(data)

Respuesta de la API: {'config': {'title': 'Cuentas monetarias de las sociedades creadoras de depósito', 'series': [{'name': 'Cuentas monetarias de las sociedades creadoras de depósito - Activos Externos Netos de Corto Plazo (millones S/)', 'dec': '0'}]}, 'periods': [{'name': 'Mar.2023', 'values': ['274537.77464472']}, {'name': 'Abr.2023', 'values': ['274617.3552437']}, {'name': 'May.2023', 'values': ['277354.2908576']}, {'name': 'Jun.2023', 'values': ['263737.45400541']}, {'name': 'Jul.2023', 'values': ['265295.72503027']}, {'name': 'Ago.2023', 'values': ['267470.4587845']}, {'name': 'Sep.2023', 'values': ['267489.80430483']}, {'name': 'Oct.2023', 'values': ['272150.53930752']}, {'name': 'Nov.2023', 'values': ['268667.45812126']}, {'name': 'Dic.2023', 'values': ['263454.52353934']}, {'name': 'Ene.2024', 'values': ['279911.9920216']}, {'name': 'Feb.2024', 'values': ['277342.77817386']}, {'name': 'Mar.2024', 'values': ['277605.58002984']}, {'name': 'Abr.2024', 'values': ['278321.1366825']}, {'name': 'May.2024', 'values': ['273042.96702455']}, {'name': 'Jun.2024', 'values': ['275010.31215767']}, {'name': 'Jul.2024', 'values': ['275096.13103548']}, {'name': 'Ago.2024', 'values': ['300956.898255']}, {'name': 'Sep.2024', 'values': ['301585.92198917']}, {'name': 'Oct.2024', 'values': ['313619.39355604']}, {'name': 'Nov.2024', 'values': ['313000.685745']}, {'name': 'Dic.2024', 'values': ['304429.39217808']}, {'name': 'Ene.2025', 'values': ['305596.75876992']}, {'name': 'Feb.2025', 'values': ['309757.1019136']}]}
       Fecha          Valor
0   Mar.2023  274537.774645
1   Abr.2023  274617.355244
2   May.2023  277354.290858
3   Jun.2023  263737.454005
4   Jul.2023  265295.725030
5   Ago.2023  267470.458785
6   Sep.2023  267489.804305
7   Oct.2023  272150.539308
8   Nov.2023  268667.458121
9   Dic.2023  263454.523539
10  Ene.2024  279911.992022
11  Feb.2024  277342.778174
12  Mar.2024  277605.580030
13  Abr.2024  278321.136683
14  May.2024  273042.967025
15  Jun.2024  275010.312158
16  Jul.2024  275096.131035
17  Ago.2024  300956.898255
18  Sep.2024  301585.921989
19  Oct.2024  313619.393556
20  Nov.2024  313000.685745
21  Dic.2024  304429.392178
22  Ene.2025  305596.758770
23  Feb.2025  309757.101914

In [ ]:
import requests
import pandas as pd

class BCRPAPI:
    BASE_URL = "https://estadisticas.bcrp.gob.pe/estadisticas/series/api/"
    
    def __init__(self, series_code, start_date=None, end_date=None):
        self.series_code = series_code
        self.start_date = start_date
        self.end_date = end_date
    
    def get_data(self):
        # Si se proporcionan fechas, incluirlas en la URL
        if self.start_date and self.end_date:
            url = f"{self.BASE_URL}{self.series_code}/json/{self.start_date}/{self.end_date}"
        else:
            url = f"{self.BASE_URL}{self.series_code}/json/"
        
        response = requests.get(url)
        
        if response.status_code == 200:
            try:
                data = response.json()
            except requests.exceptions.JSONDecodeError:
                print("Error: La respuesta de la API no es un JSON válido.")
                print("Contenido de la respuesta:", response.text)
                return None
            
            if "periods" in data and isinstance(data["periods"], list):
                fechas = [item["name"] for item in data["periods"]]
                valores = [float(item["values"][0]) if item["values"] else None for item in data["periods"]]
                df = pd.DataFrame({"Fecha": fechas, "Valor": valores})
                df = df.sort_values(by="Fecha", ascending=True).reset_index(drop=True)  # Ordenar por fecha
                return df
            else:
                print("No se encontraron datos para la serie.")
                return None
        else:
            print("Error al obtener datos, código:", response.status_code)
            print("Respuesta:", response.text)
            return None

# Ejemplo de uso con rango de fechas
bcrp = BCRPAPI("PN00026MM", start_date="2016-1", end_date="2022-5")
data = bcrp.get_data()
if data is not None:
    print(data)

       Fecha          Valor
0   Abr.2016  200977.035064
1   Abr.2017  204112.585260
2   Abr.2018  195618.972673
3   Abr.2019  214760.557020
4   Abr.2020  248877.254908
..       ...            ...
72  Sep.2017  210456.149513
73  Sep.2018  191203.685607
74  Sep.2019  229367.244728
75  Sep.2020  260474.001247
76  Sep.2021  314740.804367

[77 rows x 2 columns]

In [ ]:
import requests
import pandas as pd

class BCRPAPI:
    BASE_URL = "https://estadisticas.bcrp.gob.pe/estadisticas/series/api/"
    
    def __init__(self, series_code, start_date=None, end_date=None):
        self.series_code = series_code
        self.start_date = start_date
        self.end_date = end_date
    
    def get_data(self):
        # Si se proporcionan fechas, incluirlas en la URL
        if self.start_date and self.end_date:
            url = f"{self.BASE_URL}{self.series_code}/json/{self.start_date}/{self.end_date}"
        else:
            url = f"{self.BASE_URL}{self.series_code}/json/"
        
        response = requests.get(url)
        
        if response.status_code == 200:
            try:
                data = response.json()
            except requests.exceptions.JSONDecodeError:
                print("Error: La respuesta de la API no es un JSON válido.")
                print("Contenido de la respuesta:", response.text)
                return None
            
            if "periods" in data and isinstance(data["periods"], list):
                fechas = [item["name"] for item in data["periods"]]
                valores = [float(item["values"][0]) if item["values"] else None for item in data["periods"]]

                # Convertir fechas a un formato estándar (año-mes) para asegurar orden correcto
                df = pd.DataFrame({"Fecha": fechas, "Valor": valores})
                df["Fecha"] = pd.to_datetime(df["Fecha"], format="%b.%Y", errors="coerce")
                df = df.dropna(subset=["Fecha"])  # Eliminar valores inválidos
                df = df.sort_values(by="Fecha", ascending=True).reset_index(drop=True)  # Ordenar por fecha
                return df
            else:
                print("No se encontraron datos para la serie.")
                return None
        else:
            print("Error al obtener datos, código:", response.status_code)
            print("Respuesta:", response.text)
            return None

# Ejemplo de uso sin rango de fechas para obtener toda la data posible
bcrp = BCRPAPI("PN00026MM")
data = bcrp.get_data()
if data is not None:
    print(data)

        Fecha          Valor
0  2023-03-01  273481.368925
1  2023-05-01  280577.595901
2  2023-06-01  264782.406756
3  2023-07-01  264521.150243
4  2023-09-01  269975.756688
5  2023-10-01  273207.503458
6  2023-11-01  268349.854206
7  2024-02-01  279504.664135
8  2024-03-01  274639.893617
9  2024-05-01  275721.609663
10 2024-06-01  273520.985729
11 2024-07-01  276313.523584
12 2024-09-01  298153.419020
13 2024-10-01  314075.225696
14 2024-11-01  312104.188697
15 2025-02-01  307872.011939

In [ ]:
import requests
import pandas as pd
from datetime import datetime

class BCRPAPI:
    BASE_URL = "https://estadisticas.bcrp.gob.pe/estadisticas/series/api/"
    
    def __init__(self, series_code, start_year=1994):
        self.series_code = series_code
        self.start_year = start_year
        self.end_year = datetime.now().year  # Año actual
    
    def get_data(self):
        all_data = []
        
        for year in range(self.start_year, self.end_year + 1):
            url = f"{self.BASE_URL}{self.series_code}/json/{year}-1/{year}-12"
            response = requests.get(url)
            
            if response.status_code == 200:
                try:
                    data = response.json()
                except requests.exceptions.JSONDecodeError:
                    print(f"Error: JSON inválido para el año {year}.")
                    continue
                
                if "periods" in data and isinstance(data["periods"], list):
                    fechas = [item["name"] for item in data["periods"]]
                    valores = [float(item["values"][0]) if item["values"] else None for item in data["periods"]]
                    df = pd.DataFrame({"Fecha": fechas, "Valor": valores})
                    all_data.append(df)
            else:
                print(f"Error al obtener datos para el año {year}, código:", response.status_code)
        
        if all_data:
            final_df = pd.concat(all_data, ignore_index=True)
            final_df["Fecha"] = pd.to_datetime(final_df["Fecha"], format="%b.%Y", errors="coerce")
            final_df = final_df.dropna(subset=["Fecha"])  # Eliminar valores inválidos
            final_df = final_df.sort_values(by="Fecha", ascending=True).reset_index(drop=True)
            return final_df
        else:
            print("No se encontraron datos.")
            return None

# Ejemplo de uso: Obtener toda la data desde 1994
bcrp = BCRPAPI("PN00026MM")
data = bcrp.get_data()
if data is not None:
    print(data)

Error al obtener datos para el año 1996, código: 403
Error al obtener datos para el año 1998, código: 403
Error al obtener datos para el año 1999, código: 403
Error al obtener datos para el año 2000, código: 403
Error al obtener datos para el año 2001, código: 403
Error al obtener datos para el año 2002, código: 403
Error al obtener datos para el año 2003, código: 403
Error al obtener datos para el año 2004, código: 403
Error al obtener datos para el año 2005, código: 403
Error al obtener datos para el año 2006, código: 403
Error al obtener datos para el año 2008, código: 403
Error al obtener datos para el año 2009, código: 403
Error al obtener datos para el año 2010, código: 403
Error al obtener datos para el año 2011, código: 403
Error al obtener datos para el año 2012, código: 403
Error al obtener datos para el año 2013, código: 403
Error al obtener datos para el año 2014, código: 403
Error al obtener datos para el año 2015, código: 403
Error al obtener datos para el año 2016, código: 403
Error al obtener datos para el año 2017, código: 403
Error al obtener datos para el año 2018, código: 403
Error al obtener datos para el año 2019, código: 403
Error al obtener datos para el año 2021, código: 403
Error al obtener datos para el año 2022, código: 403
Error al obtener datos para el año 2023, código: 403
Error al obtener datos para el año 2024, código: 403
Error al obtener datos para el año 2025, código: 403
        Fecha          Valor
0  1995-02-01   12758.602400
1  1995-03-01   12823.096400
2  1995-05-01   12719.707600
3  1995-06-01   13492.098900
4  1995-07-01   13360.511399
5  1995-09-01   13792.225700
6  1995-10-01   13768.054601
7  1995-11-01   14503.087999
8  1997-02-01   24111.801201
9  1997-03-01   24307.448001
10 1997-05-01   25515.603499
11 1997-06-01   25634.739601
12 1997-07-01   25984.277700
13 1997-09-01   25885.474400
14 1997-10-01   27603.267298
15 1997-11-01   27748.808198
16 2007-02-01   57853.164805
17 2007-03-01   58598.069403
18 2007-05-01   67428.696511
19 2007-06-01   68243.719995
20 2007-07-01   73732.315898
21 2007-09-01   70536.648202
22 2007-10-01   74669.101320
23 2007-11-01   79042.781490
24 2020-02-01  233256.769756
25 2020-03-01  233995.773255
26 2020-05-01  251896.225532
27 2020-06-01  252931.980599
28 2020-07-01  262405.096053
29 2020-09-01  260474.001247
30 2020-10-01  261610.326219
31 2020-11-01  258921.607491

In [ ]:
import requests
import pandas as pd
from datetime import datetime

class BCRPAPI:
    BASE_URL = "https://estadisticas.bcrp.gob.pe/estadisticas/series/api/"
    
    def __init__(self, series_code, start_year=1994):
        self.series_code = series_code
        self.start_year = start_year
        self.end_year = datetime.now().year  # Año actual
    
    def get_data(self):
        all_data = []
        
        for year in range(self.start_year, self.end_year + 1):
            url = f"{self.BASE_URL}{self.series_code}/json/{year}-1/{year}-12"
            response = requests.get(url)
            
            if response.status_code == 200:
                try:
                    data = response.json()
                except requests.exceptions.JSONDecodeError:
                    print(f"Error: JSON inválido para el año {year}.")
                    continue
                
                if "periods" in data and isinstance(data["periods"], list):
                    fechas = [item["name"] for item in data["periods"]]
                    valores = [float(item["values"][0]) if item["values"] else None for item in data["periods"]]
                    df = pd.DataFrame({"Fecha": fechas, "Valor": valores})
                    all_data.append(df)
            else:
                print(f"Error al obtener datos para el año {year}, código:", response.status_code)
        
        if all_data:
            final_df = pd.concat(all_data, ignore_index=True)
            final_df["Fecha"] = pd.to_datetime(final_df["Fecha"], format="%b.%Y", errors="coerce")
            final_df = final_df.dropna(subset=["Fecha"])  # Eliminar valores inválidos
            final_df = final_df.sort_values(by="Fecha", ascending=True).reset_index(drop=True)
            return final_df
        else:
            print("No se encontraron datos.")
            return None

# Ejemplo de uso: Obtener toda la data desde 1994
bcrp = BCRPAPI("PN01062MM")
data = bcrp.get_data()
if data is not None:
    print(data)

Error: JSON inválido para el año 1994.
Error: JSON inválido para el año 1995.
Error: JSON inválido para el año 1996.
Error: JSON inválido para el año 1997.
Error: JSON inválido para el año 1998.
Error: JSON inválido para el año 1999.
Error al obtener datos para el año 2002, código: 403
Error al obtener datos para el año 2003, código: 403
Error al obtener datos para el año 2004, código: 403
Error al obtener datos para el año 2005, código: 403
Error al obtener datos para el año 2006, código: 403
Error al obtener datos para el año 2007, código: 403
Error al obtener datos para el año 2008, código: 403
Error al obtener datos para el año 2009, código: 403
Error al obtener datos para el año 2011, código: 403
Error al obtener datos para el año 2012, código: 403
Error al obtener datos para el año 2013, código: 403
Error al obtener datos para el año 2014, código: 403
Error al obtener datos para el año 2015, código: 403
Error al obtener datos para el año 2016, código: 403
Error al obtener datos para el año 2017, código: 403
Error al obtener datos para el año 2018, código: 403
Error al obtener datos para el año 2019, código: 403
Error al obtener datos para el año 2020, código: 403
Error al obtener datos para el año 2021, código: 403
Error al obtener datos para el año 2023, código: 403
Error al obtener datos para el año 2024, código: 403
Error al obtener datos para el año 2025, código: 403
        Fecha      Valor
0  2000-07-01   8.511000
1  2000-09-01   9.243317
2  2000-10-01  10.225000
3  2000-11-01  11.800000
4  2001-02-01   1.175513
5  2001-03-01   1.124882
6  2001-05-01   0.250597
7  2001-06-01   0.483090
8  2001-07-01   0.169080
9  2001-09-01  -0.090471
10 2001-10-01   0.062540
11 2001-11-01  -0.041999
12 2010-02-01   0.000000
13 2010-03-01   0.000000
14 2010-05-01   0.000000
15 2010-06-01   0.000000
16 2010-07-01   0.000000
17 2010-09-01   0.000000
18 2010-10-01   0.000000
19 2010-11-01   0.000000
20 2022-02-01   0.001844
21 2022-03-01   0.005512
22 2022-05-01   0.001651
23 2022-06-01   0.355811
24 2022-07-01   0.001214
25 2022-09-01   0.298105
26 2022-10-01   0.298176
27 2022-11-01   0.002759

| **Characteristic**        | **Class**                                           | **Function**                                        |
|---------------------------|-----------------------------------------------------|----------------------------------------------------|
| **Definition**            | Defined using the `class` keyword.                  | Defined using the `def` keyword.                   |
| **Purpose**               | Used to create objects and encapsulate data and methods. | Used to execute a block of code.                   |
| **Main Use**              | Model complex entities and behaviors.              | Perform a specific task or calculation.            |
| **Instantiation**         | An instance (object) of the class is created.      | Called directly to execute its code.               |
| **Methods**               | Can contain multiple methods (functions) that operate on the class's data. | Does not contain methods inside itself.            |
| **Scope**                 | Has attributes that can be accessed from different methods within the class. | Variables defined within a function are only accessible inside it. |
| **Example**               | `class Person:`<br>`    def __init__(self, name):`<br>`        self.name = name` | `def greet():`<br>`    print("Hello World")`       |
| **Advantages**            | Allows code reuse and organization.                | Simple and quick for small tasks.                  |
| **Return**                | Can return values, but is not limited to that.     | Returns values using `return`.                     |
| **State**                 | Can maintain state through attributes.             | Does not maintain state between executions.        |

In [ ]:
import requests
import pandas as pd

class BCRPAPI:
    BASE_URL = "https://estadisticas.bcrp.gob.pe/estadisticas/series/api/"
    
    def __init__(self, series_code, start_date=None, end_date=None):
        self.series_code = series_code
        self.start_date = start_date
        self.end_date = end_date
    
    def get_data(self):
        # Construcción de la URL con rango de fechas si se proporciona
        if self.start_date and self.end_date:
            url = f"{self.BASE_URL}{self.series_code}/json/{self.start_date}/{self.end_date}"
        else:
            url = f"{self.BASE_URL}{self.series_code}/json/"
        
        response = requests.get(url)
        
        if response.status_code == 200:
            try:
                data = response.json()
            except requests.exceptions.JSONDecodeError:
                print("Error: La respuesta de la API no es un JSON válido.")
                print("Contenido de la respuesta:", response.text)
                return None
            
            if "periods" in data and isinstance(data["periods"], list):
                fechas = [item["name"] for item in data["periods"]]
                valores = [float(item["values"][0]) if item["values"] else None for item in data["periods"]]
                df = pd.DataFrame({"Fecha": fechas, "Valor": valores})
                df = df.sort_values(by="Fecha", ascending=True).reset_index(drop=True)  # Ordenar por fecha
                return df
            else:
                print("No se encontraron datos para la serie.")
                return None
        else:
            print("Error al obtener datos, código:", response.status_code)
            print("Respuesta:", response.text)
            return None

# Ejemplo de uso con RD38099BM y rango de fechas especificado
bcrp = BCRPAPI("RD38099BM", "2000-7", "2025-2")
data = bcrp.get_data()
if data is not None:
    print(data)

        Fecha        Valor
0    Abr.2005   319.048883
1    Abr.2006   442.997451
2    Abr.2007   577.695348
3    Abr.2008   728.428707
4    Abr.2009   526.474612
..        ...          ...
211  Sep.2018   985.304779
212  Sep.2019   987.619627
213  Sep.2020   845.802330
214  Sep.2021  1283.096379
215  Sep.2022  1244.326950

[216 rows x 2 columns]

# FRED

FRED (Federal Reserve Economic Data) is a platform provided by the Federal Reserve Bank of St. Louis that offers access to a wide range of economic and financial data. FRED contains more than 765,000 time series data from various areas, such as:

Macroeconomic indicators (GDP, inflation, interest rates)

Labor market data

Trade and industry information

Exchange rates and commodity prices

Financial and banking statistics

🔗 Register and get an API key:
👉 https://fred.stlouisfed.org/FredLogin/register

login in
https://fredaccount.stlouisfed.org/login/secure/

📌 Are there any limitations?

You can make up to 120,000 requests per day for free.

No subscription or payment is required to access the data.

API FRED
https://fred.stlouisfed.org/docs/api/fred/

In [34]:
import requests
import json

# Clave API de FRED (reemplaza con tu clave real)
API_KEY = "994cf22ef3b66e95185459d4e8e1ef6c"

# URL de la API con el indicador del PIB (GDPC1)
url = f"https://api.stlouisfed.org/fred/series/observations?series_id=GDPC1&api_key={API_KEY}&file_type=json"

# Hacer la solicitud GET
response = requests.get(url)

# Convertir la respuesta a JSON
data = response.json()

In [35]:
#print(data)
# Mostrar datos obtenidos
print(json.dumps(data, indent=4))

{
    "realtime_start": "2025-08-21",
    "realtime_end": "2025-08-21",
    "observation_start": "1600-01-01",
    "observation_end": "9999-12-31",
    "units": "lin",
    "output_type": 1,
    "file_type": "json",
    "order_by": "observation_date",
    "sort_order": "asc",
    "count": 314,
    "offset": 0,
    "limit": 100000,
    "observations": [
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1947-01-01",
            "value": "2182.681"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1947-04-01",
            "value": "2176.892"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1947-07-01",
            "value": "2172.432"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1947-10-01",
            "value": "2206.452"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1948-01-01",
            "value": "2239.682"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1948-04-01",
            "value": "2276.69"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1948-07-01",
            "value": "2289.77"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1948-10-01",
            "value": "2292.364"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1949-01-01",
            "value": "2260.807"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1949-04-01",
            "value": "2253.128"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1949-07-01",
            "value": "2276.424"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1949-10-01",
            "value": "2257.352"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1950-01-01",
            "value": "2346.104"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1950-04-01",
            "value": "2417.682"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1950-07-01",
            "value": "2511.127"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1950-10-01",
            "value": "2559.214"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1951-01-01",
            "value": "2593.967"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1951-04-01",
            "value": "2638.898"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1951-07-01",
            "value": "2693.259"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1951-10-01",
            "value": "2699.156"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1952-01-01",
            "value": "2727.954"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1952-04-01",
            "value": "2733.8"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1952-07-01",
            "value": "2753.517"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1952-10-01",
            "value": "2843.941"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1953-01-01",
            "value": "2896.811"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1953-04-01",
            "value": "2919.206"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1953-07-01",
            "value": "2902.785"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1953-10-01",
            "value": "2858.845"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1954-01-01",
            "value": "2845.192"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1954-04-01",
            "value": "2848.305"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1954-07-01",
            "value": "2880.482"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1954-10-01",
            "value": "2936.852"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1955-01-01",
            "value": "3020.746"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1955-04-01",
            "value": "3069.91"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1955-07-01",
            "value": "3111.379"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1955-10-01",
            "value": "3130.068"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1956-01-01",
            "value": "3117.922"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1956-04-01",
            "value": "3143.694"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1956-07-01",
            "value": "3140.874"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1956-10-01",
            "value": "3192.57"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1957-01-01",
            "value": "3213.011"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1957-04-01",
            "value": "3205.97"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1957-07-01",
            "value": "3237.386"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1957-10-01",
            "value": "3203.894"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1958-01-01",
            "value": "3120.724"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1958-04-01",
            "value": "3141.224"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1958-07-01",
            "value": "3213.884"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1958-10-01",
            "value": "3289.032"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1959-01-01",
            "value": "3352.129"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1959-04-01",
            "value": "3427.667"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1959-07-01",
            "value": "3430.057"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1959-10-01",
            "value": "3439.832"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1960-01-01",
            "value": "3517.181"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1960-04-01",
            "value": "3498.246"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1960-07-01",
            "value": "3515.385"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1960-10-01",
            "value": "3470.278"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1961-01-01",
            "value": "3493.703"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1961-04-01",
            "value": "3553.021"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1961-07-01",
            "value": "3621.252"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1961-10-01",
            "value": "3692.289"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1962-01-01",
            "value": "3758.147"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1962-04-01",
            "value": "3792.149"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1962-07-01",
            "value": "3838.776"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1962-10-01",
            "value": "3851.421"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1963-01-01",
            "value": "3893.482"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1963-04-01",
            "value": "3937.183"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1963-07-01",
            "value": "4023.755"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1963-10-01",
            "value": "4050.147"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1964-01-01",
            "value": "4135.553"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1964-04-01",
            "value": "4180.592"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1964-07-01",
            "value": "4245.918"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1964-10-01",
            "value": "4259.046"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1965-01-01",
            "value": "4362.111"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1965-04-01",
            "value": "4417.225"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1965-07-01",
            "value": "4515.427"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1965-10-01",
            "value": "4619.458"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1966-01-01",
            "value": "4731.888"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1966-04-01",
            "value": "4748.046"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1966-07-01",
            "value": "4788.254"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1966-10-01",
            "value": "4827.537"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1967-01-01",
            "value": "4870.299"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1967-04-01",
            "value": "4873.287"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1967-07-01",
            "value": "4919.392"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1967-10-01",
            "value": "4956.477"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1968-01-01",
            "value": "5057.553"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1968-04-01",
            "value": "5142.033"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1968-07-01",
            "value": "5181.859"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1968-10-01",
            "value": "5202.212"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1969-01-01",
            "value": "5283.597"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1969-04-01",
            "value": "5299.625"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1969-07-01",
            "value": "5334.6"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1969-10-01",
            "value": "5308.556"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1970-01-01",
            "value": "5300.652"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1970-04-01",
            "value": "5308.164"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1970-07-01",
            "value": "5357.077"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1970-10-01",
            "value": "5299.672"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1971-01-01",
            "value": "5443.619"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1971-04-01",
            "value": "5473.059"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1971-07-01",
            "value": "5518.072"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1971-10-01",
            "value": "5531.032"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1972-01-01",
            "value": "5632.649"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1972-04-01",
            "value": "5760.47"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1972-07-01",
            "value": "5814.854"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1972-10-01",
            "value": "5912.22"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1973-01-01",
            "value": "6058.544"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1973-04-01",
            "value": "6124.506"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1973-07-01",
            "value": "6092.301"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1973-10-01",
            "value": "6150.131"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1974-01-01",
            "value": "6097.258"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1974-04-01",
            "value": "6111.751"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1974-07-01",
            "value": "6053.978"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1974-10-01",
            "value": "6030.464"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",
            "date": "1975-01-01",
            "value": "5957.035"
        },
        {
            "realtime_start": "2025-08-21",
            "realtime_end": "2025-08-21",

In [36]:
import requests
import json

# Clave API de FRED (reemplaza con tu clave real)
API_KEY = "6687ceecb17e83ae9bfa3e60d708a5f3"

# URL de la API con el indicador del PIB (GDPC1)
url = f"https://api.stlouisfed.org/fred/series/observations?series_id=GDPC1&api_key={API_KEY}&file_type=json"

# Hacer la solicitud GET
response = requests.get(url)

# Convertir la respuesta a JSON
data = response.json()

# Convertir la lista de observaciones en un DataFrame
df = pd.DataFrame(data["observations"])

# Seleccionar solo las columnas necesarias y convertir el valor a numérico
df = df[["date", "value"]]
df["value"] = pd.to_numeric(df["value"], errors="coerce")

# Renombrar columnas
df.columns = ["Fecha", "Valor"]

# Convertir la columna de fecha a formato datetime
df["Fecha"] = pd.to_datetime(df["Fecha"])

In [37]:
df

         Fecha      Valor
0   1947-01-01   2182.681
1   1947-04-01   2176.892
2   1947-07-01   2172.432
3   1947-10-01   2206.452
4   1948-01-01   2239.682
..         ...        ...
309 2024-04-01  23223.906
310 2024-07-01  23400.294
311 2024-10-01  23542.349
312 2025-01-01  23512.717
313 2025-04-01  23685.287

[314 rows x 2 columns]

In [38]:
https://api.stlouisfed.org/fred/series/categories?series_id=EXJPUS&api_key=abcdefghijklmnopqrstuvwxyz123456&file_type=json

SyntaxError: invalid syntax (3353880036.py, line 1)

In [ ]:
57f808beac766cf2600be1f7f00aa328

In [ ]:
https://api.stlouisfed.org/fred/series/search?api_key=abcdefghijklmnopqrstuvwxyz123456&search_text=canada

SyntaxError: invalid syntax (1316569115.py, line 1)

In [39]:
# Clave API de FRED (reemplaza con tu clave real)
API_KEY = "994cf22ef3b66e95185459d4e8e1ef6c"

# URL de la API con el indicador del PIB (GDPC1)
url = f"https://api.stlouisfed.org/fred/series/observations?series_id=GDPC1&api_key={API_KEY}&file_type=json"

# Hacer la solicitud GET
response = requests.get(url)

# Convertir la respuesta a JSON
data = response.json()
data

{'realtime_start': '2025-08-21',
 'realtime_end': '2025-08-21',
 'observation_start': '1600-01-01',
 'observation_end': '9999-12-31',
 'units': 'lin',
 'output_type': 1,
 'file_type': 'json',
 'order_by': 'observation_date',
 'sort_order': 'asc',
 'count': 314,
 'offset': 0,
 'limit': 100000,
 'observations': [{'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1947-01-01',
   'value': '2182.681'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1947-04-01',
   'value': '2176.892'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1947-07-01',
   'value': '2172.432'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1947-10-01',
   'value': '2206.452'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1948-01-01',
   'value': '2239.682'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1948-04-01',
   'value': '2276.69'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1948-07-01',
   'value': '2289.77'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1948-10-01',
   'value': '2292.364'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1949-01-01',
   'value': '2260.807'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1949-04-01',
   'value': '2253.128'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1949-07-01',
   'value': '2276.424'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1949-10-01',
   'value': '2257.352'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1950-01-01',
   'value': '2346.104'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1950-04-01',
   'value': '2417.682'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1950-07-01',
   'value': '2511.127'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1950-10-01',
   'value': '2559.214'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1951-01-01',
   'value': '2593.967'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1951-04-01',
   'value': '2638.898'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1951-07-01',
   'value': '2693.259'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1951-10-01',
   'value': '2699.156'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1952-01-01',
   'value': '2727.954'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1952-04-01',
   'value': '2733.8'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1952-07-01',
   'value': '2753.517'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1952-10-01',
   'value': '2843.941'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1953-01-01',
   'value': '2896.811'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1953-04-01',
   'value': '2919.206'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1953-07-01',
   'value': '2902.785'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1953-10-01',
   'value': '2858.845'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1954-01-01',
   'value': '2845.192'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1954-04-01',
   'value': '2848.305'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1954-07-01',
   'value': '2880.482'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1954-10-01',
   'value': '2936.852'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1955-01-01',
   'value': '3020.746'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1955-04-01',
   'value': '3069.91'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1955-07-01',
   'value': '3111.379'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1955-10-01',
   'value': '3130.068'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1956-01-01',
   'value': '3117.922'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1956-04-01',
   'value': '3143.694'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1956-07-01',
   'value': '3140.874'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1956-10-01',
   'value': '3192.57'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1957-01-01',
   'value': '3213.011'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1957-04-01',
   'value': '3205.97'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1957-07-01',
   'value': '3237.386'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1957-10-01',
   'value': '3203.894'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1958-01-01',
   'value': '3120.724'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1958-04-01',
   'value': '3141.224'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1958-07-01',
   'value': '3213.884'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1958-10-01',
   'value': '3289.032'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1959-01-01',
   'value': '3352.129'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1959-04-01',
   'value': '3427.667'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1959-07-01',
   'value': '3430.057'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1959-10-01',
   'value': '3439.832'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1960-01-01',
   'value': '3517.181'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1960-04-01',
   'value': '3498.246'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1960-07-01',
   'value': '3515.385'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1960-10-01',
   'value': '3470.278'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1961-01-01',
   'value': '3493.703'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1961-04-01',
   'value': '3553.021'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1961-07-01',
   'value': '3621.252'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1961-10-01',
   'value': '3692.289'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1962-01-01',
   'value': '3758.147'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1962-04-01',
   'value': '3792.149'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1962-07-01',
   'value': '3838.776'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1962-10-01',
   'value': '3851.421'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1963-01-01',
   'value': '3893.482'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1963-04-01',
   'value': '3937.183'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1963-07-01',
   'value': '4023.755'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1963-10-01',
   'value': '4050.147'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1964-01-01',
   'value': '4135.553'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1964-04-01',
   'value': '4180.592'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1964-07-01',
   'value': '4245.918'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1964-10-01',
   'value': '4259.046'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1965-01-01',
   'value': '4362.111'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1965-04-01',
   'value': '4417.225'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1965-07-01',
   'value': '4515.427'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1965-10-01',
   'value': '4619.458'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1966-01-01',
   'value': '4731.888'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1966-04-01',
   'value': '4748.046'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1966-07-01',
   'value': '4788.254'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1966-10-01',
   'value': '4827.537'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1967-01-01',
   'value': '4870.299'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1967-04-01',
   'value': '4873.287'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1967-07-01',
   'value': '4919.392'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1967-10-01',
   'value': '4956.477'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1968-01-01',
   'value': '5057.553'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1968-04-01',
   'value': '5142.033'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1968-07-01',
   'value': '5181.859'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1968-10-01',
   'value': '5202.212'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1969-01-01',
   'value': '5283.597'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1969-04-01',
   'value': '5299.625'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1969-07-01',
   'value': '5334.6'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1969-10-01',
   'value': '5308.556'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1970-01-01',
   'value': '5300.652'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1970-04-01',
   'value': '5308.164'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1970-07-01',
   'value': '5357.077'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1970-10-01',
   'value': '5299.672'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1971-01-01',
   'value': '5443.619'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1971-04-01',
   'value': '5473.059'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1971-07-01',
   'value': '5518.072'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1971-10-01',
   'value': '5531.032'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1972-01-01',
   'value': '5632.649'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1972-04-01',
   'value': '5760.47'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1972-07-01',
   'value': '5814.854'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1972-10-01',
   'value': '5912.22'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1973-01-01',
   'value': '6058.544'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1973-04-01',
   'value': '6124.506'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1973-07-01',
   'value': '6092.301'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1973-10-01',
   'value': '6150.131'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1974-01-01',
   'value': '6097.258'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1974-04-01',
   'value': '6111.751'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1974-07-01',
   'value': '6053.978'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1974-10-01',
   'value': '6030.464'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1975-01-01',
   'value': '5957.035'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1975-04-01',
   'value': '5999.61'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1975-07-01',
   'value': '6102.326'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1975-10-01',
   'value': '6184.53'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1976-01-01',
   'value': '6323.649'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1976-04-01',
   'value': '6370.025'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1976-07-01',
   'value': '6404.895'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1976-10-01',
   'value': '6451.177'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1977-01-01',
   'value': '6527.703'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1977-04-01',
   'value': '6654.466'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1977-07-01',
   'value': '6774.457'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1977-10-01',
   'value': '6774.592'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1978-01-01',
   'value': '6796.26'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1978-04-01',
   'value': '7058.92'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1978-07-01',
   'value': '7129.915'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1978-10-01',
   'value': '7225.75'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1979-01-01',
   'value': '7238.727'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1979-04-01',
   'value': '7246.454'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1979-07-01',
   'value': '7300.281'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1979-10-01',
   'value': '7318.535'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1980-01-01',
   'value': '7341.557'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1980-04-01',
   'value': '7190.289'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1980-07-01',
   'value': '7181.743'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1980-10-01',
   'value': '7315.677'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1981-01-01',
   'value': '7459.022'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1981-04-01',
   'value': '7403.745'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1981-07-01',
   'value': '7492.405'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1981-10-01',
   'value': '7410.768'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1982-01-01',
   'value': '7295.631'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1982-04-01',
   'value': '7328.912'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1982-07-01',
   'value': '7300.896'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1982-10-01',
   'value': '7303.817'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1983-01-01',
   'value': '7400.066'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1983-04-01',
   'value': '7568.456'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1983-07-01',
   'value': '7719.746'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1983-10-01',
   'value': '7880.794'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1984-01-01',
   'value': '8034.847'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1984-04-01',
   'value': '8173.67'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1984-07-01',
   'value': '8252.465'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1984-10-01',
   'value': '8320.199'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1985-01-01',
   'value': '8400.82'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1985-04-01',
   'value': '8474.787'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1985-07-01',
   'value': '8604.22'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1985-10-01',
   'value': '8668.188'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1986-01-01',
   'value': '8749.127'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1986-04-01',
   'value': '8788.524'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1986-07-01',
   'value': '8872.601'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1986-10-01',
   'value': '8920.193'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1987-01-01',
   'value': '8986.367'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1987-04-01',
   'value': '9083.256'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1987-07-01',
   'value': '9162.024'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1987-10-01',
   'value': '9319.332'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1988-01-01',
   'value': '9367.502'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1988-04-01',
   'value': '9490.594'},
  {'realtime_start': '2025-08-21',
   'realtime_end': '2025-08-21',
   'date': '1988-07-01',
   'value': '9546.206'},

In [40]:
import requests
import pandas as pd

# Tu API Key de FRED (Reemplázala con tu clave real)
API_KEY = "57f808beac766cf2600be1f7f00aa328"

# Término de búsqueda
SEARCH_TERM = "peru"

# URL de la API de FRED con el término de búsqueda
URL = f"https://api.stlouisfed.org/fred/series/search?api_key={API_KEY}&search_text={SEARCH_TERM}&file_type=json"

# Hacer la solicitud a la API
response = requests.get(URL)

# Verificar si la solicitud fue exitosa
if response.status_code == 200:
    data = response.json()
    
    # Extraer la lista de series
    series_list = data.get("seriess", [])

    if series_list:
        # Convertir a un DataFrame de Pandas
        df = pd.DataFrame(series_list)

        # Seleccionar solo las columnas más importantes
        df = df[["id", "title", "frequency", "units", "last_updated"]]

        # Mostrar los primeros resultados
        print(df.head())

        # Guardar en un archivo Excel
        #file_path = "FRED_Canada_Search.xlsx"
        #df.to_excel(file_path, index=False)
        #print(f"Datos exportados a {file_path}")

    else:
        print("No se encontraron resultados para 'Canada'.")

else:
    print("Error en la solicitud:", response.status_code)

                 id                                title frequency  \
0    FPCPITOTLZGPER  Inflation, consumer prices for Peru    Annual
1      SIPOVGINIPER                  GINI Index for Peru    Annual
2  MKTGDPPEA646NWDB      Gross Domestic Product for Peru    Annual
3       PERNGDPRPCH      Gross Domestic Product for Peru    Annual
4    NYGDPPCAPKDPER     Constant GDP per capita for Peru    Annual

                  units            last_updated
0               Percent  2025-04-16 13:53:08-05
1                 Index  2025-06-05 15:11:12-05
2  Current U.S. Dollars  2025-07-02 13:56:14-05
3        Percent Change  2025-04-30 15:07:25-05
4     2010 U.S. Dollars  2025-07-02 13:56:26-05

In [41]:
df

,id,title,frequency,units,last_updated
0,FPCPITOTLZGPER,"Inflation, consumer prices for Peru",Annual,Percent,2025-04-16 13:53:08-05
1,SIPOVGINIPER,GINI Index for Peru,Annual,Index,2025-06-05 15:11:12-05
2,MKTGDPPEA646NWDB,Gross Domestic Product for Peru,Annual,Current U.S. Dollars,2025-07-02 13:56:14-05
3,PERNGDPRPCH,Gross Domestic Product for Peru,Annual,Percent Change,2025-04-30 15:07:25-05
4,NYGDPPCAPKDPER,Constant GDP per capita for Peru,Annual,2010 U.S. Dollars,2025-07-02 13:56:26-05
...,...,...,...,...,...
579,AVELISPRIYY36860,Housing Inventory: Average Listing Price Year-...,Monthly,Percent,2022-09-01 17:23:30-05
580,AVELISPRIMM36860,Housing Inventory: Average Listing Price Month...,Monthly,Percent,2022-09-01 17:23:34-05
581,MEDLISPRIPERSQUFEEYY36860,Housing Inventory: Median Listing Price per Sq...,Monthly,Percent,2022-09-01 17:22:39-05
582,MEDLISPRIPERSQUFEEMM36860,Housing Inventory: Median Listing Price per Sq...,Monthly,Percent,2022-09-01 17:22:21-05
583,MEDAONMAMSA36860,Market Hotness: Median Days on Market in Ottaw...,Monthly,Days,2022-09-01 16:16:12-05

# WORLD BANK

In [ ]:
import requests
import pandas as pd

class WorldBankAPI:
    """
    Clase para interactuar con la API del Banco Mundial.
    Permite buscar indicadores y obtener datos económicos por país.
    """
    
    BASE_URL = "https://api.worldbank.org/v2"
    
    def __init__(self, format_type="json", per_page=1000):
        """
        Inicializa la API con formato de datos y cantidad de resultados por página.
        """
        self.format_type = format_type
        self.per_page = per_page

    def search_indicators(self, search_term):
        """
        Busca indicadores en la API del Banco Mundial según un término de búsqueda.
        :param search_term: (str) Palabra clave del indicador (Ej: "GDP", "Inflation")
        :return: DataFrame con los indicadores encontrados.
        """
        url = f"{self.BASE_URL}/indicator?format={self.format_type}&per_page={self.per_page}"
        response = requests.get(url)

        if response.status_code == 200:
            data = response.json()[1]  # La data está en la segunda posición del JSON
            
            # Filtrar indicadores que contengan el término de búsqueda en su nombre
            filtered_data = [item for item in data if search_term.lower() in item["name"].lower()]
            
            # Convertir a DataFrame
            df = pd.DataFrame(filtered_data)
            df = df[["id", "name", "unit", "source"]]
            return df
        else:
            print("Error en la solicitud:", response.status_code)
            return None

    def get_indicator_data(self, indicator_id, country_code="ALL", start_year=2000, end_year=2024):
        """
        Obtiene datos históricos de un indicador para un país o todos los países.
        :param indicator_id: (str) Código del indicador (Ej: "NY.GDP.MKTP.CD" para PIB)
        :param country_code: (str) Código del país (Ej: "PE" para Perú, "ALL" para todos)
        :param start_year: (int) Año de inicio
        :param end_year: (int) Año de fin
        :return: DataFrame con los datos del indicador
        """
        url = f"{self.BASE_URL}/country/{country_code}/indicator/{indicator_id}?date={start_year}:{end_year}&format={self.format_type}&per_page={self.per_page}"
        response = requests.get(url)

        if response.status_code == 200:
            data = response.json()[1]  # La data está en la segunda posición del JSON
            
            # Convertir a DataFrame
            df = pd.DataFrame(data)
            df = df[["country", "date", "value"]]
            
            # Extraer solo el nombre del país
            df["country"] = df["country"].apply(lambda x: x["value"])
            
            return df
        else:
            print("Error en la solicitud:", response.status_code)
            return None

    def export_to_excel(self, df, filename="world_bank_data.xlsx"):
        """
        Exporta un DataFrame a un archivo Excel.
        :param df: (DataFrame) Datos a exportar.
        :param filename: (str) Nombre del archivo.
        """
        if df is not None:
            df.to_excel(filename, index=False)
            print(f"Datos exportados a {filename}")
        else:
            print("No hay datos para exportar.")

# ========== EJEMPLO DE USO ==========
if __name__ == "__main__":
    wb_api = WorldBankAPI()

    # Buscar indicadores que contienen "GDP"
    indicadores_gdp = wb_api.search_indicators("GDP")
    print(indicadores_gdp.head())

    # Obtener datos del PIB de Perú desde el 2000 hasta 2024
    data_pib_peru = wb_api.get_indicator_data("NY.GDP.MKTP.CD", "PE", 2000, 2024)
    print(data_pib_peru.head())

    # Exportar los datos a un archivo Excel
    wb_api.export_to_excel(data_pib_peru, "PIB_Peru.xlsx")

                   id                                               name unit  \
0     6.0.GDP_current                                    GDP (current $)
1      6.0.GDP_growth                              GDP growth (annual %)
2         6.0.GDP_usd                              GDP (constant 2005 $)
3  6.0.GDPpc_constant  GDP per capita, PPP (constant 2011 internation...

                                    source
0  {'id': '37', 'value': 'LAC Equity Lab'}
1  {'id': '37', 'value': 'LAC Equity Lab'}
2  {'id': '37', 'value': 'LAC Equity Lab'}
3  {'id': '37', 'value': 'LAC Equity Lab'}
  country  date         value
0    Peru  2023  2.676032e+11
1    Peru  2022  2.464888e+11
2    Peru  2021  2.263543e+11
3    Peru  2020  2.014097e+11
4    Peru  2019  2.283460e+11
Datos exportados a PIB_Peru.xlsx

In [ ]:
data_pib_peru

   country  date         value
0     Peru  2023  2.676032e+11
1     Peru  2022  2.464888e+11
2     Peru  2021  2.263543e+11
3     Peru  2020  2.014097e+11
4     Peru  2019  2.283460e+11
5     Peru  2018  2.225970e+11
6     Peru  2017  2.110080e+11
7     Peru  2016  1.918981e+11
8     Peru  2015  1.898030e+11
9     Peru  2014  2.007863e+11
10    Peru  2013  2.011755e+11
11    Peru  2012  1.926500e+11
12    Peru  2011  1.717617e+11
13    Peru  2010  1.475276e+11
14    Peru  2009  1.208230e+11
15    Peru  2008  1.205506e+11
16    Peru  2007  1.021710e+11
17    Peru  2006  8.864319e+10
18    Peru  2005  7.606061e+10
19    Peru  2004  6.676870e+10
20    Peru  2003  5.873103e+10
21    Peru  2002  5.477755e+10
22    Peru  2001  5.203016e+10
23    Peru  2000  5.174475e+10

In [ ]:
data_pib_peru = wb_api.get_indicator_data("NY.GDP.MKTP.CD", "PE", 2000, 2024)
#print(data_pib_peru.head())

data_pib_peru
#data_pib_peru.dtypes
#wb_api.export_to_excel(data_pib_peru, "PIB_Peru.xlsx")

   country  date         value
0     Peru  2023  2.676032e+11
1     Peru  2022  2.464888e+11
2     Peru  2021  2.263543e+11
3     Peru  2020  2.014097e+11
4     Peru  2019  2.283460e+11
5     Peru  2018  2.225970e+11
6     Peru  2017  2.110080e+11
7     Peru  2016  1.918981e+11
8     Peru  2015  1.898030e+11
9     Peru  2014  2.007863e+11
10    Peru  2013  2.011755e+11
11    Peru  2012  1.926500e+11
12    Peru  2011  1.717617e+11
13    Peru  2010  1.475276e+11
14    Peru  2009  1.208230e+11
15    Peru  2008  1.205506e+11
16    Peru  2007  1.021710e+11
17    Peru  2006  8.864319e+10
18    Peru  2005  7.606061e+10
19    Peru  2004  6.676870e+10
20    Peru  2003  5.873103e+10
21    Peru  2002  5.477755e+10
22    Peru  2001  5.203016e+10
23    Peru  2000  5.174475e+10

In [ ]:
data_unemployment_usa = wb_api.get_indicator_data("SL.UEM.TOTL.ZS", "US", 2000, 2024)
print(data_unemployment_usa.head())

#wb_api.export_to_excel(data_unemployment_usa, "Desempleo_USA.xlsx")

         country  date  value
0  United States  2023  3.638
1  United States  2022  3.650
2  United States  2021  5.349
3  United States  2020  8.055
4  United States  2019  3.669

In [ ]:
paises_latam = ["AR", "BO", "BR", "CL", "CO", "EC", "MX", "PE", "VE"]
data_life_expectancy = pd.concat(
    [wb_api.get_indicator_data("SP.DYN.LE00.IN", country, 2020, 2024) for country in paises_latam]
)

print(data_life_expectancy.head())
#wb_api.export_to_excel(data_life_expectancy, "EsperanzaVida_Latam.xlsx")

     country  date   value
0  Argentina  2023     NaN
1  Argentina  2022  76.064
2  Argentina  2021  75.390
3  Argentina  2020  75.892
0    Bolivia  2023     NaN

In [ ]:
data_energy = wb_api.get_indicator_data("EG.USE.PCAP.KG.OE", "ALL", 2010, 2024)
#print(data_energy.head())

#wb_api.export_to_excel(data_energy, "ConsumoEnergia_Mundial.xlsx")
data_energy.head(20)

                        country  date       value
0   Africa Eastern and Southern  2023         NaN
1   Africa Eastern and Southern  2022         NaN
2   Africa Eastern and Southern  2021         NaN
3   Africa Eastern and Southern  2020         NaN
4   Africa Eastern and Southern  2019         NaN
5   Africa Eastern and Southern  2018         NaN
6   Africa Eastern and Southern  2017         NaN
7   Africa Eastern and Southern  2016         NaN
8   Africa Eastern and Southern  2015         NaN
9   Africa Eastern and Southern  2014  724.721156
10  Africa Eastern and Southern  2013  709.181147
11  Africa Eastern and Southern  2012  712.404050
12  Africa Eastern and Southern  2011  733.176327
13  Africa Eastern and Southern  2010  738.795379
14   Africa Western and Central  2023         NaN
15   Africa Western and Central  2022         NaN
16   Africa Western and Central  2021         NaN
17   Africa Western and Central  2020         NaN
18   Africa Western and Central  2019         NaN
19   Africa Western and Central  2018         NaN

In [ ]:
import requests
import json

# URL de la API del Banco Mundial
url = "https://api.worldbank.org/v2/country/PE/indicator/NY.GDP.MKTP.CD?format=json"

# Hacer la solicitud GET
response = requests.get(url)

# Convertir la respuesta a JSON
data = response.json()

# Extraer los valores
for record in data[1]:  # Los datos están en la segunda lista del JSON
    print(f"Año: {record['date']}, PIB: {record['value']}")

Año: 2023, PIB: 267603248655.253
Año: 2022, PIB: 246488757636.211
Año: 2021, PIB: 226354278280.885
Año: 2020, PIB: 201409694755.934
Año: 2019, PIB: 228346006003.648
Año: 2018, PIB: 222597009739.235
Año: 2017, PIB: 211007984080.911
Año: 2016, PIB: 191898104390.379
Año: 2015, PIB: 189802976285.619
Año: 2014, PIB: 200786250582.943
Año: 2013, PIB: 201175543571.392
Año: 2012, PIB: 192650021648.583
Año: 2011, PIB: 171761737046.585
Año: 2010, PIB: 147527631520.729
Año: 2009, PIB: 120822986521.479
Año: 2008, PIB: 120550599815.441
Año: 2007, PIB: 102170981144.136
Año: 2006, PIB: 88643193061.748
Año: 2005, PIB: 76060606060.6061
Año: 2004, PIB: 66768703497.5687
Año: 2003, PIB: 58731030121.8671
Año: 2002, PIB: 54777553515.0809
Año: 2001, PIB: 52030158775.4055
Año: 2000, PIB: 51744749133.213
Año: 1999, PIB: 50187324567.883
Año: 1998, PIB: 55501467877.381
Año: 1997, PIB: 58147522522.5225
Año: 1996, PIB: 55252414130.3019
Año: 1995, PIB: 53312793687.3836
Año: 1994, PIB: 44882079766.8913
Año: 1993, PIB: 34832077220.8537
Año: 1992, PIB: 35966302303.263
Año: 1991, PIB: 34341465998.2003
Año: 1990, PIB: 26410386962.8019
Año: 1989, PIB: 22499558526.3682
Año: 1988, PIB: 15439408447.2
Año: 1987, PIB: 36889706592.6843
Año: 1986, PIB: 21859448586.485
Año: 1985, PIB: 15078736875.387
Año: 1984, PIB: 17600400384.5073
Año: 1983, PIB: 17345260564.4824
Año: 1982, PIB: 21794535621.216
Año: 1981, PIB: 21648214892.8828
Año: 1980, PIB: 18136838537.725
Año: 1979, PIB: 15954012439.1662
Año: 1978, PIB: 12491876742.9708
Año: 1977, PIB: 14544913960.5062
Año: 1976, PIB: 16131958850.6444
Año: 1975, PIB: 16931162355.4802
Año: 1974, PIB: 13858441211.4692