In [ ]:
# Transformers installation
! pip install datasets -qU
# To install from source instead of the last release, comment the command above and uncomment the following one.
! pip install git+https://github.com/huggingface/transformers.git
# Transformers comes pre-installed in the Colab environment
# !pip install transformers

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.5/491.5 kB 13.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.6/193.6 kB 4.5 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2025.3.2 requires fsspec==2025.3.2, but you have fsspec 2025.3.0 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cublas-cu12==12.4.5.8; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu12 12.5.3.2 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-cupti-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-cupti-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-nvrtc-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-nvrtc-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-runtime-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-runtime-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cudnn-cu12==9.1.0.70; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cudnn-cu12 9.3.0.75 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cufft-cu12==11.2.1.3; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cufft-cu12 11.2.3.61 which is incompatible.
torch 2.6.0+cu124 requires nvidia-curand-cu12==10.3.5.147; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-curand-cu12 10.3.6.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cusolver-cu12==11.6.1.9; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusolver-cu12 11.6.3.83 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cusparse-cu12==12.3.1.170; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusparse-cu12 12.5.1.3 which is incompatible.
torch 2.6.0+cu124 requires nvidia-nvjitlink-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-nvjitlink-cu12 12.5.82 which is incompatible.
Collecting git+https://github.com/huggingface/transformers.git
  Cloning https://github.com/huggingface/transformers.git to /tmp/pip-req-build-0mr46blf
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers.git /tmp/pip-req-build-0mr46blf
  Resolved https://github.com/huggingface/transformers.git to commit 8cb96787a6bd87f43ff651b8ac40974c1fe75a7c
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers==4.53.0.dev0) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.11/dist-packages (from transformers==4.53.0.dev0) (0.31.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers==4.53.0.dev0) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers==4.53.0.dev0) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers==4.53.0.dev0) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers==4.53.0.dev0) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers==4.53.0.dev0) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers==4.53.0.dev0) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers==4.53.0.dev0) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers==4.53.0.dev0) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers==4.53.0.dev0) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers==4.53.0.dev0) (4.13.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.53.0.dev0) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.53.0.dev0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.53.0.dev0) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.53.0.dev0) (2025.4.26)
Building wheels for collected packages: transformers
  Building wheel for transformers (pyproject.toml) ... done
  Created wheel for transformers: filename=transformers-4.53.0.dev0-py3-none-any.whl size=11382826 sha256=72ac74a62affb90758655a5353ef200fbe1e31434313c253bfd43991c82a8a34
  Stored in directory: /tmp/pip-ephem-wheel-cache-5uwlrpcn/wheels/32/4b/78/f195c684dd3a9ed21f3b39fe8f85b48df7918581b6437be143
Successfully built transformers
Installing collected packages: transformers
  Attempting uninstall: transformers
    Found existing installation: transformers 4.52.2
    Uninstalling transformers-4.52.2:
      Successfully uninstalled transformers-4.52.2
Successfully installed transformers-4.53.0.dev0

# Using Open-Source Models with HuggingFace

Hugging Face is an AI company and an open-source platform that provides tools, models, and datasets for machine learning, particularly in **natural language processing (NLP)** and **computer vision**. It is best known for hosting **pre-trained transformer models**, including **BERT, GPT, T5, LLaMA, and Stable Diffusion**, and for developing the **🤗 Transformers** library, which makes it easy to use these models. Whenever you see the 🤗 emoji, this means we are referring to a library provided by Hugging Face

### Key Components of Hugging Face:
1. **🤗 Transformers Library** - Provides pre-trained models for NLP (text generation, classification, translation, etc.), vision, and audio.
2. **🤗 Datasets** - A collection of thousands of datasets for ML, accessible via the `datasets` library.
3. **Tokenizers** - Efficient tokenization for text processing.
4. **Hugging Face Hub** - A repository where users can share and download pre-trained models, datasets, and scripts.
5. **AutoTrain & Spaces** - Tools for no-code model training and hosting machine-learning demos.

HuggingFace is a great resource for working in the open-source space, as they provide useful tools to facilitate data processing, model inference and fine-tuning, and deployment.

## Choosing a model

We will start by exploring the pre-trained models that HuggingFace makes available through the Hugging Face Hub

### The Hugging Face Hub

The Hugging Face Hub is an online repository and collaboration platform for sharing and discovering pre-trained AI models, datasets, and ML applications It's like GitHub for machine learning, providing a centralized space where researchers and developers can upload, download, and collaborate on machine learning models and datasets.

### Key Features of the Hugging Face Hub
1. **Pre-Trained Models** - Thousands of models for NLP, computer vision, audio, reinforcement learning, etc.
2. **Datasets** - A collection of open-source datasets ready to use with the `datasets` library.
3. **Model Training & Fine-Tuning** - Users can fine-tune models and upload their custom versions.
4. **Spaces** - A place to host interactive ML applications using **Gradio or Streamlit**.
5. **API & Integrations** - Easily load models via `from_pretrained()` in the `transformers` library.
6. **Version Control & Collaboration** - Works like GitHub, with versioning, pull requests, and community contributions.

You can enter the Hugging Face Hub [here](https://huggingface.co)

After clicking on the "Models" tab, you will see a screen like the following
image

![hf-hub-models](https://raw.githubusercontent.com/RodrigoGrijalba/qlab_2025_examples/main/images/7/hf-hub-models.PNG)

There is a very large amount of models, which may be overwhelming at first. However, the hub gives us the ability to search for models made for specific tasks. For example, we may want to translate to and from Quechua. We can first choose the "Translation" task on the left.

![models-filter-tl](https://raw.githubusercontent.com/RodrigoGrijalba/qlab_2025_examples/main/images/7/models-filter-tl.PNG)


Then we can search for Quechua in the "Languages" tab

![models-filter-qc](https://raw.githubusercontent.com/RodrigoGrijalba/qlab_2025_examples/main/images/7/models-filter-qc.PNG)

Finally, we may want a model with a more permisive license, like Apache 2.0 or MIT

![models-filter-qc](https://raw.githubusercontent.com/RodrigoGrijalba/qlab_2025_examples/main/images/7/models-filter-lic.PNG)

After filtering for these parameters, the number of results is way lower. Once we find a model that interests us, we should take a look at its model card. This card is like a README that will give us information about the features and background of the model.

# Summary NLP tasks available

We will take a look at some of the most frequent use-cases when using the 🤗 Transformers library. The models available allow for many different
configurations and a great versatility in use-cases. The most simple ones are presented here, showcasing usage for
tasks such as image classification, question answering, sequence classification, named entity recognition and others.

These examples leverage auto-models, which are classes that will instantiate a model according to a given checkpoint,
automatically selecting the correct model architecture. Check the [AutoModel](https://huggingface.co/docs/transformers/main/en/model_doc/auto#transformers.AutoModel) documentation
for more information. However, it is possible to modify this code and make it
more specific for our use cases.

In order for a model to perform well on a task, **it must be loaded from a checkpoint corresponding to that task**. These
checkpoints are usually pre-trained on a large corpus of data and fine-tuned on a specific task. This means that not all models were fine-tuned on all tasks. We will introduce how to fine-tune a model for a specific task on next class. We should also keep in mind that fine-tuned models were fine-tuned on a specific dataset, and this dataset may or may not overlap with our use-case and  domain.

In order to do an inference on a task, several mechanisms are made available by the library:

- Pipelines: very easy-to-use abstractions, which require as little as two lines of code.
- Direct model use: Less abstractions, but more flexibility and power via a direct access to a tokenizer
  (PyTorch/TensorFlow) and full inference capacity.

We will take a look at both approaches here.

<Tip>

All tasks presented here leverage pre-trained checkpoints that were fine-tuned on specific tasks. **Loading a
checkpoint that was not fine-tuned on a specific task** would load only the base transformer layers and not the
additional head that is used for the task, initializing the weights of that head randomly.

This would **produce random output**.

</Tip>

## Sequence Classification

Sequence classification is the task of classifying sequences according to a given number of classes. An example of
sequence classification is the GLUE dataset, which is entirely based on that task. If you would like to fine-tune a
model on a GLUE sequence classification task, you may leverage the [run_glue.py](https://github.com/huggingface/transformers/tree/main/examples/pytorch/text-classification/run_glue.py), [run_tf_glue.py](https://github.com/huggingface/transformers/tree/main/examples/tensorflow/text-classification/run_tf_glue.py), [run_tf_text_classification.py](https://github.com/huggingface/transformers/tree/main/examples/tensorflow/text-classification/run_tf_text_classification.py) or [run_xnli.py](https://github.com/huggingface/transformers/tree/main/examples/pytorch/text-classification/run_xnli.py) scripts.

Here is an example of using pipelines to do sentiment analysis: identifying if a sequence is positive or negative. It
leverages a fine-tuned model on sst2, which is a GLUE task.

This returns a label ("POSITIVE" or "NEGATIVE") alongside a score, as follows:

In [ ]:
from datasets import load_dataset

# Cargar un dataset, por ejemplo 'imdb' (puedes cambiarlo por el dataset que desees)
dataset = load_dataset("imdb")

# Convertir a DataFrame
df_train = pd.DataFrame(dataset["train"])
df_test = pd.DataFrame(dataset["test"])

# Mostrar las primeras filas
print(df_train.head())

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md:   0%|          | 0.00/7.81k [00:00<?, ?B/s]

train-00000-of-00001.parquet:   0%|          | 0.00/21.0M [00:00<?, ?B/s]

test-00000-of-00001.parquet:   0%|          | 0.00/20.5M [00:00<?, ?B/s]

unsupervised-00000-of-00001.parquet:   0%|          | 0.00/42.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating unsupervised split:   0%|          | 0/50000 [00:00<?, ? examples/s]

                                                text  label
0  I rented I AM CURIOUS-YELLOW from my video sto...      0
1  "I Am Curious: Yellow" is a risible and preten...      0
2  If only to avoid making this type of film in t...      0
3  This film was probably inspired by Godard's Ma...      0
4  Oh, brother...after hearing about this ridicul...      0

In [ ]:
from datasets import load_dataset

# Load the simplified 3-class GoEmotions dataset
dataset = load_dataset("go_emotions", "simplified")

# Convert to DataFrames (optional)
import pandas as pd
df_train = pd.DataFrame(dataset["train"])
df_test = pd.DataFrame(dataset["test"])

# Preview
print(df_train.head())

README.md:   0%|          | 0.00/9.40k [00:00<?, ?B/s]

train-00000-of-00001.parquet:   0%|          | 0.00/2.77M [00:00<?, ?B/s]

validation-00000-of-00001.parquet:   0%|          | 0.00/350k [00:00<?, ?B/s]

test-00000-of-00001.parquet:   0%|          | 0.00/347k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/43410 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/5426 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/5427 [00:00<?, ? examples/s]

                                                text labels       id
0  My favourite food is anything I didn't have to...   [27]  eebbqej
1  Now if he does off himself, everyone will thin...   [27]  ed00q6i
2                     WHY THE FUCK IS BAYLESS ISOING    [2]  eezlygj
3                        To make her feel threatened   [14]  ed7ypvh
4                             Dirty Southern Wankers    [3]  ed0bdzj

In [ ]:
df_sample = df_train.sample(20)
df_sample

                                                    text    labels       id
7689                       HOWS THIS HOWS THIS HOWS THIS      [27]  ed88ypx
1604                      Don't forget fluent in sarcasm      [27]  edjpfac
16839  Sitting here, waiting for the price to drop so...       [9]  edc59b3
42352                                     I do avoid it.      [27]  ef2a4r4
23581  Yeah, that's why I'm not feeling like there's ...       [9]  eekwv92
37820  OMG this is gaming history in the making. Lol ...  [13, 26]  ee2gx3e
3910   Yea true , it sucks that theater mode doesn’t ...    [3, 9]  eetyj22
34542                          She raided [NAME] closet.      [27]  edfpeh9
33223  Looks like you got it bad. How soon till you c...      [25]  eeuga53
6073   Fond memories of one guy having a tub of ice c...      [27]  efb5v0b
34211                                      He said fr*ck      [27]  ed9p5by
40884  Dallas should feel absolutely horrible this is...       [3]  ed4h3e7
9771   Oh sorry if I seemed dishonest. I hope you can...  [20, 24]  ee359hq
17834  I tried it that way first and thought this was...  [15, 22]  ef9uazv
21863  A beautiful poem for a beautiful thing. Happy ...      [17]  effs1ed
41303  I don’t understand why he’s being considered b...    [6, 7]  ed7y9gz
21753             Which state? It's actually quite rare.      [27]  ee56qxq
20315  I knooooow. I’m expecting more water splashes ...      [27]  edrzs62
18                   that is what retardation looks like      [27]  eeb9aft
27292  Play stupid games, win stupid prizes... looks ...   [2, 27]  ef6bt46

In [ ]:
df_train= df_train.rename(columns={'labels': 'label'})
df_train

                                                    text label       id
0      My favourite food is anything I didn't have to...  [27]  eebbqej
1      Now if he does off himself, everyone will thin...  [27]  ed00q6i
2                         WHY THE FUCK IS BAYLESS ISOING   [2]  eezlygj
3                            To make her feel threatened  [14]  ed7ypvh
4                                 Dirty Southern Wankers   [3]  ed0bdzj
...                                                  ...   ...      ...
43405  Added you mate well I’ve just got the bow and ...  [18]  edsb738
43406  Always thought that was funny but is it a refe...   [6]  ee7fdou
43407  What are you talking about? Anything bad that ...   [3]  efgbhks
43408            More like a baptism, with sexy results!  [13]  ed1naf8
43409                                    Enjoy the ride!  [17]  eecwmbq

[43410 rows x 3 columns]

In [ ]:
import pandas as pd
from transformers import pipeline

# Set up the sentiment analysis pipeline
classifier = pipeline("sentiment-analysis")

# Assuming df_train is already loaded and you've created df_sample
# If you need to recreate the sample:
df_sample = df_train.sample(20)

# Create a function to get sentiment results
def get_sentiment(text):
    result = classifier(text)[0]
    return result['label']

def get_sentiment_score(text):
    result = classifier(text)[0]
    return round(result['score'], 4)

# Add sentiment label and score columns
df_sample['sentiment'] = df_sample['text'].apply(get_sentiment)
df_sample['sentiment_score'] = df_sample['text'].apply(get_sentiment_score)

# Display the updated dataframe
print(df_sample[['text', 'label', 'sentiment', 'sentiment_score']])

# Example on how the classifier works with a single text
example_result = classifier("I do like living in peru")[0]
print(f"Example - label: {example_result['label']}, with score: {round(example_result['score'], 4)}")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cuda:0

                                                    text    label sentiment  \
21699       I liked it better when [NAME] was half naked     [18]  NEGATIVE
15294  [NAME] pays big. He bought out Hot Doug’s so h...     [27]  NEGATIVE
187                      By [NAME]! That’s [NAME] music!     [17]  POSITIVE
4256   No, no, Amazon! Ripping is painful! ‍♀️ Be *ge...     [10]  NEGATIVE
24106  Great snap. Try again in a week when the light...      [0]  POSITIVE
1156                         His time will come for that     [20]  POSITIVE
11078  [NAME] was an awesome Chief. Wish we would've ...   [0, 8]  POSITIVE
41548                          Confound your toll Troll!     [26]  NEGATIVE
8443   I'd almost rather a criminal have a gun than t...     [27]  NEGATIVE
21026  Everyone hates these posts but when we do post...     [21]  POSITIVE
25880  should've rolled into battle with a sword brad...  [2, 27]  NEGATIVE
24329                                    Calm down satan     [27]  NEGATIVE
348       Good news: this is shark tale not finding Nemo      [0]  NEGATIVE
9989   Its whatever you make of it. No one can tell y...      [4]  POSITIVE
2754               [NAME] and [NAME]. I can't stand them     [27]  NEGATIVE
6103        "Figured you might like to learn something."     [27]  POSITIVE
34825  Yes. One of her fingers is getting a sore on i...      [5]  NEGATIVE
8346   At least the shots we're getting are counting....     [27]  NEGATIVE
31962                                 for sure not natty     [27]  NEGATIVE
19741  With punctuation like that I'm surprised you'r...     [26]  POSITIVE

       sentiment_score
21699           0.9795
15294           0.8516
187             0.9955
4256            0.6884
24106           0.9911
1156            0.9681
11078           0.8085
41548           0.9817
8443            0.9977
21026           0.9993
25880           0.9946
24329           0.9784
348             0.9613
9989            0.6058
2754            0.9981
6103            0.9824
34825           0.9912
8346            0.6066
31962           0.8546
19741           0.7880
Example - label: POSITIVE, with score: 0.9954

In [ ]:
from transformers import pipeline

classifier = pipeline("sentiment-analysis")

test_phrases = [
    """Objetivos de Desarrollo Sostenible Las mujeres en Ecatepec
    restauran el tejido social de su comunidad a través del deporte, la resiliencia y la solidaridad.
     Cancha Violeta es un espacio que contribuye a la igualdad de género y trabaja a favor de la salud mental infantil,
     brindando acompañamiento y servicios de prevención contra la violencia de genero."""
]

classifier(test_phrases)
#for phrase in test_phrases:
#    result = classifier(phrase)[0]
#    print(f"'{phrase}' → label: {result['label']}, score: {round(result['score'], 4)}")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cuda:0

[{'label': 'NEGATIVE', 'score': 0.952548623085022}]

In [ ]:
from transformers import pipeline

classifier = pipeline("sentiment-analysis")

test_phrases = [
    "I like eating ceviche in peru",
    "I enjoy eating ceviche in peru",
    "I do like peru",
    "I like peru",
    "Eating ceviche is enjoyable",
    "Peru is a great place"
]

for phrase in test_phrases:
    result = classifier(phrase)[0]
    print(f"'{phrase}' → label: {result['label']}, score: {round(result['score'], 4)}")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cuda:0

'I like eating ceviche in peru' → label: NEGATIVE, score: 0.8528
'I enjoy eating ceviche in peru' → label: POSITIVE, score: 0.9927
'I do like peru' → label: POSITIVE, score: 0.9987
'I like peru' → label: POSITIVE, score: 0.9989
'Eating ceviche is enjoyable' → label: POSITIVE, score: 0.9999
'Peru is a great place' → label: POSITIVE, score: 0.9998

In [ ]:
from transformers import pipeline

classifier = pipeline("sentiment-analysis")

result = classifier("I like eating ceviche in peru")[0]
print(f"label: {result['label']}, with score: {round(result['score'], 4)}")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cuda:0

label: NEGATIVE, with score: 0.8528

In [ ]:
result = classifier("I do not love you")[0]
print(f"label: {result['label']}, with score: {round(result['score'], 4)}")

label: NEGATIVE, with score: 0.9991

Now we will see an example of doing a sequence classification using a model to determine if two sequences are paraphrases of
each other. In this class, we will showcase how to run these models using both PyTorch and TensorFlow, which are libraries widely used for working on neural networks. There are some slight differences in the way we will use these libraries to conduct inference with the 🤗 Transformers library, but the overall logic and framework is the same.

### Using PyTorch

Instantiate a tokenizer and a model from the checkpoint name. The model is identified as a BERT model and loads it with the weights stored in the checkpoint.

In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased-finetuned-mrpc")
model = AutoModelForSequenceClassification.from_pretrained("bert-base-cased-finetuned-mrpc")

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/433 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
WARNING:huggingface_hub.file_download:Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/433M [00:00<?, ?B/s]

Build a sequence from the two sentences, with the correct model-specific separators, token type ids and attention masks (which will be created automatically by the tokenizer). Notice that we specify the `return_tensors="pt"` option, because we are working with PyTorch so we want
the model to return PyTorch-compatible tensors.

In [ ]:
classes = ["not paraphrase", "is paraphrase"]

sequence_0 = "The company HuggingFace is based in New York City"
sequence_1 = "Apples are especially bad for your health"
sequence_2 = "HuggingFace's headquarters are situated in Manhattan"

# The tokenizer will automatically add any model specific separators (i.e. <CLS> and <SEP>) and tokens to
# the sequence, as well as compute the attention masks.
# Como economistas trabajamos en 2D, Los economistas no necesitaamos , Tensor es una colección de matrices - Pytorch
paraphrase = tokenizer(sequence_0, sequence_2, return_tensors="pt")
not_paraphrase = tokenizer(sequence_0, sequence_1, return_tensors="pt")

Pass this sequence through the model so that it is classified in one of the two available classes: 0 (not a paraphrase) and 1 (is a paraphrase).

In [ ]:
paraphrase_classification_logits = model(**paraphrase).logits
not_paraphrase_classification_logits = model(**not_paraphrase).logits

Compute the softmax of the result to get probabilities over the classes.

In [ ]:
paraphrase_results = torch.softmax(paraphrase_classification_logits, dim=1).tolist()[0]
not_paraphrase_results = torch.softmax(not_paraphrase_classification_logits, dim=1).tolist()[0]

Print the results.

In [ ]:
# Should be paraphrase
for i in range(len(classes)):
    print(f"{classes[i]}: {int(round(paraphrase_results[i] * 100))}%")

not paraphrase: 10%
is paraphrase: 90%

In [ ]:
# Should not be paraphrase
for i in range(len(classes)):
    print(f"{classes[i]}: {int(round(not_paraphrase_results[i] * 100))}%")

not paraphrase: 94%
is paraphrase: 6%

### Using TensofFlow

The steps are the same as for PyTorch, just with slightly adjusted code

In [ ]:
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification
import tensorflow as tf

Now we specify the `return_tensors="tf"` option to get TensorFlow tensors

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased-finetuned-mrpc")
model = TFAutoModelForSequenceClassification.from_pretrained("bert-base-cased-finetuned-mrpc")

classes = ["not paraphrase", "is paraphrase"]

sequence_0 = "The company HuggingFace is based in New York City"
sequence_1 = "Apples are especially bad for your health"
sequence_2 = "HuggingFace's headquarters are situated in Manhattan"

# The tokenizer will automatically add any model specific separators (i.e. <CLS> and <SEP>) and tokens to
# the sequence, as well as compute the attention masks.
paraphrase = tokenizer(sequence_0, sequence_2, return_tensors="tf")
not_paraphrase = tokenizer(sequence_0, sequence_1, return_tensors="tf")

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

All the weights of TFBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.

In [ ]:
paraphrase_classification_logits = model(paraphrase).logits
not_paraphrase_classification_logits = model(not_paraphrase).logits

In [ ]:
paraphrase_results = tf.nn.softmax(paraphrase_classification_logits, axis=1).numpy()[0]
not_paraphrase_results = tf.nn.softmax(not_paraphrase_classification_logits, axis=1).numpy()[0]

In [ ]:
# Should be paraphrase
for i in range(len(classes)):
    print(f"{classes[i]}: {int(round(paraphrase_results[i] * 100))}%")

not paraphrase: 10%
is paraphrase: 90%

In [ ]:
# Should not be paraphrase
for i in range(len(classes)):
    print(f"{classes[i]}: {int(round(not_paraphrase_results[i] * 100))}%")

not paraphrase: 94%
is paraphrase: 6%

## Extractive Question Answering

Extractive Question Answering is the task of extracting an answer from a text given a question. An example of a
question answering dataset is the SQuAD dataset, which is entirely based on that task.

Here is an example of using pipelines to do question answering: extracting an answer from a text given a question. It
leverages a fine-tuned model on SQuAD.

In [ ]:
dina_context = r"""
La exasistenta de la presidenta, Patricia Muriano, señaló que la mandataria no fue
operada de la nariz por Mario Cabani, sino por otro especialista, el cirujano y otorrino Javier
 Sánchez e Ingunza, según reveló un audio difundido por el semanario Hildebrandt en sus trece.
 En la grabación, Muriano también detalla que Boluarte se sometió a otros procedimientos estéticos,
  lo que contradice la versión oficial de que la intervención quirúrgica a la que fue sometida en
  junio de 2023 tenía solo fines médicos por temas de salud de la jefa de Estado.
De acuerdo con el testimonio de Muriano, la mandataria habría recibido una pequeña extracción
 de grasa del abdomen, aplicación de hilos tensores en el rostro y eliminación de bolsas en los
 ojos, además de la presunta rinoplastia. Sobre la operación de nariz, precisó que esta fue realizada
  por el cirujano Sánchez e Ingunza, ya que Cabani "no toca nariz".
  """

In [ ]:
result = question_answerer(question="como se llama la exasistenta de la presidenta", context=dina_context)
print(
    f"Answer: '{result['answer']}', score: {round(result['score'], 4)}, start: {result['start']}, end: {result['end']}"
)

Answer: 'Patricia Muriano', score: 0.0001, start: 34, end: 50

In [ ]:
from transformers import pipeline

question_answerer = pipeline("question-answering")

context = r"""
Extractive Question Answering is the task of extracting an answer from a text given a question. An example of a
question answering dataset is the SQuAD dataset, which is entirely based on that task. If you would like to fine-tune
a model on a SQuAD task, you may leverage the examples/pytorch/question-answering/run_squad.py script.
"""

No model was supplied, defaulted to distilbert/distilbert-base-cased-distilled-squad and revision 564e9b5 (https://huggingface.co/distilbert/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/473 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
WARNING:huggingface_hub.file_download:Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/261M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

Device set to use cuda:0

This returns an answer extracted from the text, a confidence score, alongside "start" and "end" values, which are the
positions of the extracted answer in the text.

In [ ]:
result = question_answerer(question="What is extractive question answering?", context=context)
print(
    f"Answer: '{result['answer']}', score: {round(result['score'], 4)}, start: {result['start']}, end: {result['end']}"
)

Answer: 'the task of extracting an answer from a text given a question', score: 0.6177, start: 34, end: 95

In [ ]:
result = question_answerer(question="What is a good example of a question answering dataset?", context=context)
print(
    f"Answer: '{result['answer']}', score: {round(result['score'], 4)}, start: {result['start']}, end: {result['end']}"
)

Answer: 'SQuAD dataset', score: 0.5152, start: 147, end: 160

### PyTorch

Instantiate a tokenizer and a model from the checkpoint name. The model is identified as a BERT model and loads it with the weights stored in the checkpoint.

In [ ]:
from transformers import AutoTokenizer, AutoModelForQuestionAnswering
import torch

tokenizer = AutoTokenizer.from_pretrained("bert-large-uncased-whole-word-masking-finetuned-squad")
model = AutoModelForQuestionAnswering.from_pretrained("bert-large-uncased-whole-word-masking-finetuned-squad")

Some weights of the model checkpoint at bert-large-uncased-whole-word-masking-finetuned-squad were not used when initializing BertForQuestionAnswering: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForQuestionAnswering from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForQuestionAnswering from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

Define a text and a few questions.

In [ ]:
text = r"""
🤗 Transformers (formerly known as pytorch-transformers and pytorch-pretrained-bert) provides general-purpose
architectures (BERT, GPT-2, RoBERTa, XLM, DistilBert, XLNet…) for Natural Language Understanding (NLU) and Natural
Language Generation (NLG) with over 32+ pretrained models in 100+ languages and deep interoperability between
TensorFlow 2.0 and PyTorch.
"""

questions = [
    "How many pretrained models are available in 🤗 Transformers?",
    "What does 🤗 Transformers provide?",
    "🤗 Transformers provides interoperability between which frameworks?",
]

Build a sequence from the text and the question, with the correct model-specific separators, token type ids and attention masks.

In [ ]:
question = questions[0]
inputs = tokenizer(question, text, add_special_tokens=True, return_tensors="pt")
input_ids = inputs["input_ids"].tolist()[0]

Pass this sequence through the model. This outputs a range of scores across the entire sequence tokens (question and text), for both the start and end positions.

In [ ]:
outputs = model(**inputs)
answer_start_scores = outputs.start_logits
answer_end_scores = outputs.end_logits

Compute the softmax of the result to get probabilities over the tokens.

In [ ]:
# Get the most likely beginning of answer with the argmax of the score
answer_start = torch.argmax(answer_start_scores)
# Get the most likely end of answer with the argmax of the score
answer_end = torch.argmax(answer_end_scores) + 1

Fetch the tokens from the identified start and stop values, convert those tokens to a string.

In [ ]:
answer = tokenizer.convert_tokens_to_string(
    tokenizer.convert_ids_to_tokens(input_ids[answer_start:answer_end])
)

Print the results.

In [ ]:
print(f"Question: {question}")
print(f"Answer: {answer}")

Question: How many pretrained models are available in 🤗 Transformers?
Answer: over 32 +

We can iterate over all questions now

In [ ]:
for question in questions:
    inputs = tokenizer(question, text, add_special_tokens=True, return_tensors="pt")
    input_ids = inputs["input_ids"].tolist()[0]

    outputs = model(**inputs)
    answer_start_scores = outputs.start_logits
    answer_end_scores = outputs.end_logits

    # Get the most likely beginning of answer with the argmax of the score
    answer_start = torch.argmax(answer_start_scores)
    # Get the most likely end of answer with the argmax of the score
    answer_end = torch.argmax(answer_end_scores) + 1

    answer = tokenizer.convert_tokens_to_string(
        tokenizer.convert_ids_to_tokens(input_ids[answer_start:answer_end])
    )

### TensorFlow

In [ ]:
from transformers import AutoTokenizer, TFAutoModelForQuestionAnswering
import tensorflow as tf

tokenizer = AutoTokenizer.from_pretrained("bert-large-uncased-whole-word-masking-finetuned-squad")
model = TFAutoModelForQuestionAnswering.from_pretrained("bert-large-uncased-whole-word-masking-finetuned-squad")

All PyTorch model weights were used when initializing TFBertForQuestionAnswering.

All the weights of TFBertForQuestionAnswering were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForQuestionAnswering for predictions without further training.

In [ ]:
text = r"""
🤗 Transformers (formerly known as pytorch-transformers and pytorch-pretrained-bert) provides general-purpose
architectures (BERT, GPT-2, RoBERTa, XLM, DistilBert, XLNet…) for Natural Language Understanding (NLU) and Natural
Language Generation (NLG) with over 32+ pretrained models in 100+ languages and deep interoperability between
TensorFlow 2.0 and PyTorch.
"""

questions = [
    "How many pretrained models are available in 🤗 Transformers?",
    "What does 🤗 Transformers provide?",
    "🤗 Transformers provides interoperability between which frameworks?",
]

In [ ]:
for question in questions:
    inputs = tokenizer(question, text, add_special_tokens=True, return_tensors="tf")
    input_ids = inputs["input_ids"].numpy()[0]

    outputs = model(inputs)
    answer_start_scores = outputs.start_logits
    answer_end_scores = outputs.end_logits

    # Get the most likely beginning of answer with the argmax of the score
    answer_start = tf.argmax(answer_start_scores, axis=1).numpy()[0]
    # Get the most likely end of answer with the argmax of the score
    answer_end = tf.argmax(answer_end_scores, axis=1).numpy()[0] + 1

    answer = tokenizer.convert_tokens_to_string(
        tokenizer.convert_ids_to_tokens(input_ids[answer_start:answer_end])
    )

    print(f"Question: {question}")
    print(f"Answer: {answer}")

Question: How many pretrained models are available in 🤗 Transformers?
Answer: over 32 +
Question: What does 🤗 Transformers provide?
Answer: general - purpose architectures
Question: 🤗 Transformers provides interoperability between which frameworks?
Answer: tensorflow 2. 0 and pytorch

## Language Modeling

Language modeling is the task of fitting a model to a corpus, which can be domain specific. All popular
transformer-based models are trained using a variant of language modeling, e.g. BERT with masked language modeling,
GPT-2 with causal language modeling.

Language modeling can be useful outside of pretraining as well, for example to shift the model distribution to be
domain-specific: using a language model trained over a very large corpus, and then fine-tuning it to a news dataset or
on scientific papers e.g. [LysandreJik/arxiv-nlp](https://huggingface.co/lysandre/arxiv-nlp).

### Masked Language Modeling

Masked language modeling is the task of masking tokens in a sequence with a masking token, and prompting the model to
fill that mask with an appropriate token. This allows the model to attend to both the right context (tokens on the
right of the mask) and the left context (tokens on the left of the mask). Such a training creates a strong basis for
downstream tasks requiring bi-directional context, such as SQuAD (question answering, see [Lewis, Lui, Goyal et al.](https://arxiv.org/abs/1910.13461), part 4.2).

Here is an example of using pipelines to replace a mask from a sequence:

In [ ]:
from transformers import pipeline
# Propio de trasnformers, cual es la palabra que debe haber ido
unmasker = pipeline("fill-mask")

No model was supplied, defaulted to distilbert/distilroberta-base and revision fb53ab8 (https://huggingface.co/distilbert/distilroberta-base).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/480 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
WARNING:huggingface_hub.file_download:Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/331M [00:00<?, ?B/s]

Some weights of the model checkpoint at distilbert/distilroberta-base were not used when initializing RobertaForMaskedLM: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Device set to use cuda:0

This outputs the sequences with the mask filled, the confidence score, and the token id in the tokenizer vocabulary:

In [ ]:
from pprint import pprint

pprint(
    unmasker(
        f"HuggingFace is creating a {unmasker.tokenizer.mask_token} that the community uses to solve NLP tasks."
    )
)

[{'score': 0.1792750507593155,
  'sequence': 'HuggingFace is creating a tool that the community uses to solve '
              'NLP tasks.',
  'token': 3944,
  'token_str': ' tool'},
 {'score': 0.11349441111087799,
  'sequence': 'HuggingFace is creating a framework that the community uses to '
              'solve NLP tasks.',
  'token': 7208,
  'token_str': ' framework'},
 {'score': 0.052435584366321564,
  'sequence': 'HuggingFace is creating a library that the community uses to '
              'solve NLP tasks.',
  'token': 5560,
  'token_str': ' library'},
 {'score': 0.03493529185652733,
  'sequence': 'HuggingFace is creating a database that the community uses to '
              'solve NLP tasks.',
  'token': 8503,
  'token_str': ' database'},
 {'score': 0.028602521866559982,
  'sequence': 'HuggingFace is creating a prototype that the community uses to '
              'solve NLP tasks.',
  'token': 17715,
  'token_str': ' prototype'}]

Here is an example of doing masked language modeling using a model and a tokenizer.

### PyTorch

Instantiate a tokenizer and a model from the checkpoint name. The model is identified as a DistilBERT model and loads it with the weights stored in the checkpoint.

In [ ]:
from transformers import AutoModelForMaskedLM, AutoTokenizer
import torch

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-cased")
model = AutoModelForMaskedLM.from_pretrained("distilbert-base-cased")

Define a sequence with a masked token, placing the tokenizer.mask_token instead of a word.

In [ ]:
sequence = (
    "Distilled models are smaller than the models they mimic. Using them instead of the large "
    f"versions would help {tokenizer.mask_token} our carbon footprint."
)

Encode that sequence into a list of IDs and find the position of the masked token in that list.

In [ ]:
inputs = tokenizer(sequence, return_tensors="pt")
mask_token_index = torch.where(inputs["input_ids"] == tokenizer.mask_token_id)[1]

Retrieve the predictions at the index of the mask token: this tensor has the same size as the vocabulary, and the values are the scores attributed to each token. The model gives higher score to tokens it deems probable in that context.

In [ ]:
token_logits = model(**inputs).logits
mask_token_logits = token_logits[0, mask_token_index, :]

Retrieve the top 5 tokens using the PyTorch topk or TensorFlow top_k methods.

In [ ]:
top_5_tokens = torch.topk(mask_token_logits, 5, dim=1).indices[0].tolist()

Replace the mask token by the tokens and print the results

In [ ]:
for token in top_5_tokens:
    print(sequence.replace(tokenizer.mask_token, tokenizer.decode([token])))

Distilled models are smaller than the models they mimic. Using them instead of the large versions would help reduce our carbon footprint.
Distilled models are smaller than the models they mimic. Using them instead of the large versions would help increase our carbon footprint.
Distilled models are smaller than the models they mimic. Using them instead of the large versions would help decrease our carbon footprint.
Distilled models are smaller than the models they mimic. Using them instead of the large versions would help offset our carbon footprint.
Distilled models are smaller than the models they mimic. Using them instead of the large versions would help improve our carbon footprint.

### TensorFlow

In [ ]:
from transformers import TFAutoModelForMaskedLM, AutoTokenizer
import tensorflow as tf

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-cased")
model = TFAutoModelForMaskedLM.from_pretrained("distilbert-base-cased")

sequence = (
    "Distilled models are smaller than the models they mimic. Using them instead of the large "
    f"versions would help {tokenizer.mask_token} our carbon footprint."
)

inputs = tokenizer(sequence, return_tensors="tf")
mask_token_index = tf.where(inputs["input_ids"] == tokenizer.mask_token_id)[0, 1]

token_logits = model(**inputs).logits
mask_token_logits = token_logits[0, mask_token_index, :]

top_5_tokens = tf.math.top_k(mask_token_logits, 5).indices.numpy()

for token in top_5_tokens:
    print(sequence.replace(tokenizer.mask_token, tokenizer.decode([token])))

All PyTorch model weights were used when initializing TFDistilBertForMaskedLM.

All the weights of TFDistilBertForMaskedLM were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForMaskedLM for predictions without further training.

Distilled models are smaller than the models they mimic. Using them instead of the large versions would help reduce our carbon footprint.
Distilled models are smaller than the models they mimic. Using them instead of the large versions would help increase our carbon footprint.
Distilled models are smaller than the models they mimic. Using them instead of the large versions would help decrease our carbon footprint.
Distilled models are smaller than the models they mimic. Using them instead of the large versions would help offset our carbon footprint.
Distilled models are smaller than the models they mimic. Using them instead of the large versions would help improve our carbon footprint.

This prints five sequences, with the top 5 tokens predicted by the model.

### Text Generation

In text generation (*a.k.a* *open-ended text generation*) the goal is to create a coherent portion of text that is a
continuation from the given context. The following example shows how *GPT-2* can be used in pipelines to generate text.
As a default all models apply *Top-K* sampling when used in pipelines, as configured in their respective configurations
(see [gpt-2 config](https://huggingface.co/gpt2/blob/main/config.json) for example). The reason we are using `GPT-2` specifically is because that is the last model OpenAI released that remained open-source. However, this is generally how the newer GPT models work.

In [ ]:
from transformers import pipeline

text_generator = pipeline("text-generation")

No model was supplied, defaulted to openai-community/gpt2 and revision 607a30d (https://huggingface.co/openai-community/gpt2).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
WARNING:huggingface_hub.file_download:Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Device set to use cuda:0

In [ ]:
print(text_generator("As far as I am concerned, I will not play", max_length=50, do_sample=False))

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[{'generated_text': 'As far as I am concerned, I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I will not play the game. I'}]

In [ ]:
print(text_generator("As far as I am concerned, I will cold all day", max_length=50, do_sample=False))

The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[{'generated_text': 'As far as I am concerned, I will cold all day. I will be back in the hospital for a few days. I will be back in the hospital for a few days. I will be back in the hospital for a few days. I will be back in the hospital for a few days. I will be back in the hospital for a few days. I will be back in the hospital for a few days. I will be back in the hospital for a few days. I will be back in the hospital for a few days. I will be back in the hospital for a few days. I will be back in the hospital for a few days. I will be back in the hospital for a few days. I will be back in the hospital for a few days. I will be back in the hospital for a few days. I will be back in the hospital for a few days. I will be back in the hospital for a few days. I will be back in the hospital for a few days. I will be back in the hospital for a few days. I will be back in the hospital for a few days. I will be back in the hospital for a few days. I will be back in the hospital for a few days. I will be back in the hospital for a few days. I will be'}]

Here, the model generates a random text with a total maximal length of *50* tokens from context *"As far as I am
concerned, I will"*. Behind the scenes, the pipeline object calls the method
[PreTrainedModel.generate()](https://huggingface.co/docs/transformers/main/en/main_classes/text_generation#transformers.GenerationMixin.generate) to generate text. The default arguments for this method can be
overridden in the pipeline, as is shown above for the arguments `max_length` and `do_sample`. `max_length` sets the maximum amount of tokens to generate. `do_sample` chooses whether to sample from the probability distribution of tokens, or just choose the one with the highest probability.

Below is an example of text generation using `XLNet` and its tokenizer, which includes calling `generate()` directly:

### PyTorch

Instantiate the model and tokenizer

In [ ]:
from transformers import AutoModelForCausalLM, AutoTokenizer

model = AutoModelForCausalLM.from_pretrained("xlnet-base-cased")
tokenizer = AutoTokenizer.from_pretrained("xlnet-base-cased")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/760 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/467M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/137 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/798k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/467M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.38M [00:00<?, ?B/s]

Create padding text. This helps XLNet with short prompts - proposed by Aman Rusia in https://github.com/rusiaaman/XLNet-gen#methodology

In [ ]:
# Padding text helps XLNet with short prompts - proposed by Aman Rusia in https://github.com/rusiaaman/XLNet-gen#methodology
PADDING_TEXT = """In 1991, the remains of Russian Tsar Nicholas II and his family
(except for Alexei and Maria) are discovered.
The voice of Nicholas's young son, Tsarevich Alexei Nikolaevich, narrates the
remainder of the story. 1883 Western Siberia,
a young Grigori Rasputin is asked by his father and a group of men to perform magic.
Rasputin has a vision and denounces one of the men as a horse thief. Although his
father initially slaps him for making such an accusation, Rasputin watches as the
man is chased outside and beaten. Twenty years later, Rasputin sees a vision of
the Virgin Mary, prompting him to become a priest. Rasputin quickly becomes famous,
with people, even a bishop, begging for his blessing. <eod> </s> <eos>"""

Now we run the model and add the generated (decoded) text to our original prompt. The `top_p` argument makes sure that the model only considers a top percentile (in this case, 95) when choosing the next token to generate. Similar with the `top_k` argument, which sets the algorithm to only consider the top k (in this case, 60) tokens.

In [ ]:
prompt = "Today the weather is really nice and I am planning on "
inputs = tokenizer(PADDING_TEXT + prompt, add_special_tokens=False, return_tensors="pt")["input_ids"]

prompt_length = len(tokenizer.decode(inputs[0]))
outputs = model.generate(inputs, max_length=250, do_sample=True, top_p=0.95, top_k=60)
generated = prompt + tokenizer.decode(outputs[0])[prompt_length + 1 :]

print(generated)

This is a friendly reminder - the current text generation call will exceed the model's predefined maximum length (-1). Depending on the model, you may observe exceptions, performance degradation, or nothing at all.

Today the weather is really nice and I am planning on hiking for a while. I also plan on biking for a bit of time. But I am not doing that much hiking right now because I don’t want to do a lot of climbing. I want to enjoy myself and take care of myself. I’m not going to have to be able to hike a lot more or spend a lot of time hiking at the

TensorFlow

In [ ]:
from transformers import TFAutoModelForCausalLM, AutoTokenizer

model = TFAutoModelForCausalLM.from_pretrained("xlnet-base-cased")
tokenizer = AutoTokenizer.from_pretrained("xlnet-base-cased")

tf_model.h5:   0%|          | 0.00/565M [00:00<?, ?B/s]

/usr/local/lib/python3.11/dist-packages/tf_keras/src/initializers/initializers.py:121: UserWarning: The initializer TruncatedNormal is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initializer instance more than once.
  warnings.warn(
All model checkpoint layers were used when initializing TFXLNetLMHeadModel.

All the layers of TFXLNetLMHeadModel were initialized from the model checkpoint at xlnet-base-cased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFXLNetLMHeadModel for predictions without further training.

In [ ]:
# Padding text helps XLNet with short prompts - proposed by Aman Rusia in https://github.com/rusiaaman/XLNet-gen#methodology
PADDING_TEXT = """In 1991, the remains of Russian Tsar Nicholas II and his family
(except for Alexei and Maria) are discovered.
The voice of Nicholas's young son, Tsarevich Alexei Nikolaevich, narrates the
remainder of the story. 1883 Western Siberia,
a young Grigori Rasputin is asked by his father and a group of men to perform magic.
Rasputin has a vision and denounces one of the men as a horse thief. Although his
father initially slaps him for making such an accusation, Rasputin watches as the
man is chased outside and beaten. Twenty years later, Rasputin sees a vision of
the Virgin Mary, prompting him to become a priest. Rasputin quickly becomes famous,
with people, even a bishop, begging for his blessing. <eod> </s> <eos>"""

prompt = "Today the weather is really nice and I am planning on "
inputs = tokenizer(PADDING_TEXT + prompt, add_special_tokens=False, return_tensors="tf")["input_ids"]

prompt_length = len(tokenizer.decode(inputs[0]))
outputs = model.generate(inputs, max_length=250, do_sample=True, top_p=0.95, top_k=60)
generated = prompt + tokenizer.decode(outputs[0])[prompt_length + 1 :]

print(generated)

Today the weather is really nice and I am planning on walking as much as possible. As you can see above the map above from the photo above, as far as I can see, it is the "south " in which the town is located, it is a two-lane road.<eop> I am not going to drive and the road is two-lane or not, or at all. I will decide on

Text generation is currently possible with *GPT-2*, *OpenAi-GPT*, *CTRL*, *XLNet*, *Transfo-XL* and *Reformer* in
PyTorch and for most models in Tensorflow as well. As can be seen in the example above *XLNet* and *Transfo-XL* often
need to be padded to work well. GPT-2 is usually a good choice for *open-ended text generation* because it was trained
on millions of webpages with a causal language modeling objective.

For more information on how to apply different decoding strategies for text generation, refer to HuggingFace's text
generation blog post [here](https://huggingface.co/blog/how-to-generate).

## Named Entity Recognition

Named Entity Recognition (NER) is the task of classifying tokens according to a class, for example, identifying a token
as a person, an organisation or a location. An example of a named entity recognition dataset is the CoNLL-2003 dataset,
which is entirely based on that task.

Here is an example of using pipelines to do named entity recognition, specifically, trying to identify tokens as
belonging to one of 9 classes:

- O, Outside of a named entity
- B-MIS, Beginning of a miscellaneous entity right after another miscellaneous entity
- I-MIS, Miscellaneous entity
- B-PER, Beginning of a person's name right after another person's name
- I-PER, Person's name
- B-ORG, Beginning of an organisation right after another organisation
- I-ORG, Organisation
- B-LOC, Beginning of a location right after another location
- I-LOC, Location

It leverages a fine-tuned model on CoNLL-2003, fine-tuned by [@stefan-it](https://github.com/stefan-it) from [dbmdz](https://github.com/dbmdz).

Te ayuda a reconocer el tipo de texto que es, hasta 9 clases

In [ ]:
from transformers import pipeline

ner_pipe = pipeline("ner")

sequence = """Hugging Face Inc. is a company based in New York City. Its headquarters are in DUMBO,
therefore very close to the Manhattan Bridge which is visible from the window."""

No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision 4c53496 (https://huggingface.co/dbmdz/bert-large-cased-finetuned-conll03-english).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/998 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
WARNING:huggingface_hub.file_download:Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

Some weights of the model checkpoint at dbmdz/bert-large-cased-finetuned-conll03-english were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

tokenizer_config.json:   0%|          | 0.00/60.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

Device set to use cuda:0

This outputs a list of all words that have been identified as one of the entities from the 9 classes defined above.
Here are the expected results:

In [ ]:
for entity in ner_pipe(sequence):
    print(entity)

{'entity': 'I-ORG', 'score': np.float32(0.99957865), 'index': 1, 'word': 'Hu', 'start': 0, 'end': 2}
{'entity': 'I-ORG', 'score': np.float32(0.9909764), 'index': 2, 'word': '##gging', 'start': 2, 'end': 7}
{'entity': 'I-ORG', 'score': np.float32(0.9982224), 'index': 3, 'word': 'Face', 'start': 8, 'end': 12}
{'entity': 'I-ORG', 'score': np.float32(0.9994879), 'index': 4, 'word': 'Inc', 'start': 13, 'end': 16}
{'entity': 'I-LOC', 'score': np.float32(0.9994344), 'index': 11, 'word': 'New', 'start': 40, 'end': 43}
{'entity': 'I-LOC', 'score': np.float32(0.99931955), 'index': 12, 'word': 'York', 'start': 44, 'end': 48}
{'entity': 'I-LOC', 'score': np.float32(0.9993794), 'index': 13, 'word': 'City', 'start': 49, 'end': 53}
{'entity': 'I-LOC', 'score': np.float32(0.98625827), 'index': 19, 'word': 'D', 'start': 79, 'end': 80}
{'entity': 'I-LOC', 'score': np.float32(0.951427), 'index': 20, 'word': '##UM', 'start': 80, 'end': 82}
{'entity': 'I-LOC', 'score': np.float32(0.93365926), 'index': 21, 'word': '##BO', 'start': 82, 'end': 84}
{'entity': 'I-LOC', 'score': np.float32(0.9761654), 'index': 28, 'word': 'Manhattan', 'start': 114, 'end': 123}
{'entity': 'I-LOC', 'score': np.float32(0.9914629), 'index': 29, 'word': 'Bridge', 'start': 124, 'end': 130}

In [ ]:
congress_context = r"""
La Subcomisión de Acusaciones Constitucionales (SAC)
del Congreso declaró improcedente la denuncia constitucional
549, que implicaba a los congresistas José Williams, Jorge Montoya,
Roberto Chiabra, José Cueto, Alfredo Azurín, Hamlet Echevarría,
Américo Gonza, Patricia Juárez, Juan Lizarzaburu, Pedro Martínez y
Lucinda Vásquez por haber promovido y aprobado una norma que permitió
a cinco de ellos recibir doble remuneración mientras ejercían su función parlamentaria.


Con 13 votos a favor, 0 en contra y 2 abstenciones, el informe de
calificación que desestima la denuncia fue aprobado por mayoría.
La argumentación respaldada por la SAC señala que "no se puede
penalizar el ejercicio de la función legislativa cuando está
acorde con la Constitución" y que hacerlo "significaría disminuir
los derechos de los congresistas". Con esta decisión, la SAC
rechazó la solicitud del Ministerio Público y cerró la posibilidad
de investigar a los legisladores involucrados.
"""

for entity in ner_pipe(congress_context):
  print(entity)

{'entity': 'I-ORG', 'score': np.float32(0.79895353), 'index': 1, 'word': 'La', 'start': 1, 'end': 3}
{'entity': 'I-ORG', 'score': np.float32(0.97861665), 'index': 2, 'word': 'Sub', 'start': 4, 'end': 7}
{'entity': 'I-ORG', 'score': np.float32(0.9272096), 'index': 3, 'word': '##com', 'start': 7, 'end': 10}
{'entity': 'I-ORG', 'score': np.float32(0.90203035), 'index': 4, 'word': '##isi', 'start': 10, 'end': 13}
{'entity': 'I-ORG', 'score': np.float32(0.9942048), 'index': 5, 'word': '##ón', 'start': 13, 'end': 15}
{'entity': 'I-ORG', 'score': np.float32(0.9970798), 'index': 6, 'word': 'de', 'start': 16, 'end': 18}
{'entity': 'I-ORG', 'score': np.float32(0.99558455), 'index': 7, 'word': 'A', 'start': 19, 'end': 20}
{'entity': 'I-ORG', 'score': np.float32(0.94030386), 'index': 8, 'word': '##cus', 'start': 20, 'end': 23}
{'entity': 'I-ORG', 'score': np.float32(0.98973876), 'index': 9, 'word': '##ac', 'start': 23, 'end': 25}
{'entity': 'I-ORG', 'score': np.float32(0.99156606), 'index': 10, 'word': '##ione', 'start': 25, 'end': 29}
{'entity': 'I-ORG', 'score': np.float32(0.9970692), 'index': 11, 'word': '##s', 'start': 29, 'end': 30}
{'entity': 'I-ORG', 'score': np.float32(0.99795216), 'index': 12, 'word': 'Con', 'start': 31, 'end': 34}
{'entity': 'I-ORG', 'score': np.float32(0.9401786), 'index': 13, 'word': '##st', 'start': 34, 'end': 36}
{'entity': 'I-ORG', 'score': np.float32(0.5197999), 'index': 14, 'word': '##it', 'start': 36, 'end': 38}
{'entity': 'I-ORG', 'score': np.float32(0.93627673), 'index': 15, 'word': '##uc', 'start': 38, 'end': 40}
{'entity': 'I-ORG', 'score': np.float32(0.975466), 'index': 16, 'word': '##ional', 'start': 40, 'end': 45}
{'entity': 'I-ORG', 'score': np.float32(0.98456144), 'index': 17, 'word': '##es', 'start': 45, 'end': 47}
{'entity': 'I-ORG', 'score': np.float32(0.9969212), 'index': 19, 'word': 'SA', 'start': 49, 'end': 51}
{'entity': 'I-ORG', 'score': np.float32(0.99653816), 'index': 20, 'word': '##C', 'start': 51, 'end': 52}
{'entity': 'I-ORG', 'score': np.float32(0.95073116), 'index': 22, 'word': 'del', 'start': 54, 'end': 57}
{'entity': 'I-ORG', 'score': np.float32(0.96991986), 'index': 23, 'word': 'Con', 'start': 58, 'end': 61}
{'entity': 'I-ORG', 'score': np.float32(0.71036136), 'index': 24, 'word': '##g', 'start': 61, 'end': 62}
{'entity': 'I-ORG', 'score': np.float32(0.7011853), 'index': 25, 'word': '##res', 'start': 62, 'end': 65}
{'entity': 'I-ORG', 'score': np.float32(0.90636957), 'index': 26, 'word': '##o', 'start': 65, 'end': 66}
{'entity': 'I-ORG', 'score': np.float32(0.47193617), 'index': 42, 'word': '##uc', 'start': 107, 'end': 109}
{'entity': 'I-PER', 'score': np.float32(0.9992021), 'index': 58, 'word': 'José', 'start': 153, 'end': 157}
{'entity': 'I-PER', 'score': np.float32(0.9996543), 'index': 59, 'word': 'Williams', 'start': 158, 'end': 166}
{'entity': 'I-PER', 'score': np.float32(0.9991881), 'index': 61, 'word': 'Jorge', 'start': 168, 'end': 173}
{'entity': 'I-PER', 'score': np.float32(0.99885774), 'index': 62, 'word': 'Mont', 'start': 174, 'end': 178}
{'entity': 'I-PER', 'score': np.float32(0.9991709), 'index': 63, 'word': '##oya', 'start': 178, 'end': 181}
{'entity': 'I-PER', 'score': np.float32(0.9993917), 'index': 65, 'word': 'Roberto', 'start': 183, 'end': 190}
{'entity': 'I-PER', 'score': np.float32(0.9926259), 'index': 66, 'word': 'Chi', 'start': 191, 'end': 194}
{'entity': 'I-PER', 'score': np.float32(0.9139741), 'index': 67, 'word': '##ab', 'start': 194, 'end': 196}
{'entity': 'I-PER', 'score': np.float32(0.9757815), 'index': 68, 'word': '##ra', 'start': 196, 'end': 198}
{'entity': 'I-PER', 'score': np.float32(0.9992575), 'index': 70, 'word': 'José', 'start': 200, 'end': 204}
{'entity': 'I-PER', 'score': np.float32(0.9988783), 'index': 71, 'word': 'C', 'start': 205, 'end': 206}
{'entity': 'I-PER', 'score': np.float32(0.9841547), 'index': 72, 'word': '##ue', 'start': 206, 'end': 208}
{'entity': 'I-PER', 'score': np.float32(0.99451524), 'index': 73, 'word': '##to', 'start': 208, 'end': 210}
{'entity': 'I-PER', 'score': np.float32(0.9993031), 'index': 75, 'word': 'Alfredo', 'start': 212, 'end': 219}
{'entity': 'I-PER', 'score': np.float32(0.99865365), 'index': 76, 'word': 'A', 'start': 220, 'end': 221}
{'entity': 'I-PER', 'score': np.float32(0.9933096), 'index': 77, 'word': '##zu', 'start': 221, 'end': 223}
{'entity': 'I-PER', 'score': np.float32(0.96755725), 'index': 78, 'word': '##r', 'start': 223, 'end': 224}
{'entity': 'I-PER', 'score': np.float32(0.992717), 'index': 79, 'word': '##ín', 'start': 224, 'end': 226}
{'entity': 'I-PER', 'score': np.float32(0.9993037), 'index': 81, 'word': 'Hamlet', 'start': 228, 'end': 234}
{'entity': 'I-PER', 'score': np.float32(0.9984609), 'index': 82, 'word': 'E', 'start': 235, 'end': 236}
{'entity': 'I-PER', 'score': np.float32(0.97252065), 'index': 83, 'word': '##chev', 'start': 236, 'end': 240}
{'entity': 'I-PER', 'score': np.float32(0.8886497), 'index': 84, 'word': '##ar', 'start': 240, 'end': 242}
{'entity': 'I-PER', 'score': np.float32(0.8477522), 'index': 85, 'word': '##r', 'start': 242, 'end': 243}
{'entity': 'I-PER', 'score': np.float32(0.98247015), 'index': 86, 'word': '##ía', 'start': 243, 'end': 245}
{'entity': 'I-PER', 'score': np.float32(0.99919814), 'index': 88, 'word': 'Am', 'start': 247, 'end': 249}
{'entity': 'I-PER', 'score': np.float32(0.9989133), 'index': 89, 'word': '##é', 'start': 249, 'end': 250}
{'entity': 'I-PER', 'score': np.float32(0.99864453), 'index': 90, 'word': '##ric', 'start': 250, 'end': 253}
{'entity': 'I-PER', 'score': np.float32(0.9991084), 'index': 91, 'word': '##o', 'start': 253, 'end': 254}
{'entity': 'I-PER', 'score': np.float32(0.9990662), 'index': 92, 'word': 'Go', 'start': 255, 'end': 257}
{'entity': 'I-PER', 'score': np.float32(0.9802639), 'index': 93, 'word': '##nza', 'start': 257, 'end': 260}
{'entity': 'I-PER', 'score': np.float32(0.99924135), 'index': 95, 'word': 'Patricia', 'start': 262, 'end': 270}
{'entity': 'I-PER', 'score': np.float32(0.99889475), 'index': 96, 'word': 'Ju', 'start': 271, 'end': 273}
{'entity': 'I-PER', 'score': np.float32(0.9992712), 'index': 97, 'word': '##árez', 'start': 273, 'end': 277}
{'entity': 'I-PER', 'score': np.float32(0.99943537), 'index': 99, 'word': 'Juan', 'start': 279, 'end': 283}
{'entity': 'I-PER', 'score': np.float32(0.99811673), 'index': 100, 'word': 'Liza', 'start': 284, 'end': 288}
{'entity': 'I-PER', 'score': np.float32(0.9391647), 'index': 101, 'word': '##rz', 'start': 288, 'end': 290}
{'entity': 'I-PER', 'score': np.float32(0.93479073), 'index': 102, 'word': '##ab', 'start': 290, 'end': 292}
{'entity': 'I-PER', 'score': np.float32(0.93114954), 'index': 103, 'word': '##uru', 'start': 292, 'end': 295}
{'entity': 'I-PER', 'score': np.float32(0.99947125), 'index': 105, 'word': 'Pedro', 'start': 297, 'end': 302}
{'entity': 'I-PER', 'score': np.float32(0.9996165), 'index': 106, 'word': 'Martínez', 'start': 303, 'end': 311}
{'entity': 'I-PER', 'score': np.float32(0.99929047), 'index': 108, 'word': 'Luc', 'start': 314, 'end': 317}
{'entity': 'I-PER', 'score': np.float32(0.9992466), 'index': 109, 'word': '##inda', 'start': 317, 'end': 321}
{'entity': 'I-PER', 'score': np.float32(0.999153), 'index': 110, 'word': 'V', 'start': 322, 'end': 323}
{'entity': 'I-PER', 'score': np.float32(0.9496727), 'index': 111, 'word': '##ás', 'start': 323, 'end': 325}
{'entity': 'I-PER', 'score': np.float32(0.99907553), 'index': 112, 'word': '##quez', 'start': 325, 'end': 329}
{'entity': 'I-ORG', 'score': np.float32(0.9971577), 'index': 227, 'word': 'SA', 'start': 640, 'end': 642}
{'entity': 'I-ORG', 'score': np.float32(0.9900474), 'index': 228, 'word': '##C', 'start': 642, 'end': 643}
{'entity': 'I-MISC', 'score': np.float32(0.7995355), 'index': 264, 'word': 'Con', 'start': 743, 'end': 746}
{'entity': 'I-ORG', 'score': np.float32(0.5717454), 'index': 268, 'word': '##ión', 'start': 752, 'end': 755}
{'entity': 'I-ORG', 'score': np.float32(0.9985821), 'index': 306, 'word': 'SA', 'start': 852, 'end': 854}
{'entity': 'I-ORG', 'score': np.float32(0.99437743), 'index': 307, 'word': '##C', 'start': 854, 'end': 855}
{'entity': 'I-ORG', 'score': np.float32(0.956351), 'index': 318, 'word': '##io', 'start': 889, 'end': 891}
{'entity': 'I-ORG', 'score': np.float32(0.9883562), 'index': 319, 'word': 'P', 'start': 892, 'end': 893}
{'entity': 'I-ORG', 'score': np.float32(0.6045321), 'index': 322, 'word': '##lic', 'start': 895, 'end': 898}
{'entity': 'I-ORG', 'score': np.float32(0.9245145), 'index': 323, 'word': '##o', 'start': 898, 'end': 899}

Note how the tokens of the sequence "Hugging Face" have been identified as an organisation, and "New York City",
"DUMBO" and "Manhattan Bridge" have been identified as locations.

Here is an example of doing named entity recognition, using a model and a tokenizer. The process is the following:

### PyTorch

Instantiate a tokenizer and a model from the checkpoint name. The model is identified as a BERT model and loads it with the weights stored in the checkpoint.

In [ ]:
from transformers import AutoModelForTokenClassification, AutoTokenizer
import torch

model = AutoModelForTokenClassification.from_pretrained("dbmdz/bert-large-cased-finetuned-conll03-english")
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

Some weights of the model checkpoint at dbmdz/bert-large-cased-finetuned-conll03-english were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

Define a sequence with known entities, such as "Hugging Face" as an organisation and "New York City" as a location.

In [ ]:
sequence = (
    "Hugging Face Inc. is a company based in New York City. Its headquarters are in DUMBO, "
    "therefore very close to the Manhattan Bridge."
)

Split words into tokens so that they can be mapped to predictions. We use a small hack by, first, completely encoding and decoding the sequence, so that we're left with a string that contains the special tokens.

In [ ]:
inputs = tokenizer(sequence, return_tensors="pt")

Encode that sequence into IDs (special tokens are added automatically).

In [ ]:
tokens = inputs.tokens()

Retrieve the predictions by passing the input to the model and getting the first output. This results in a distribution over the 9 possible classes for each token. We take the argmax to retrieve the most likely class for each token.

This outputs a list of each token mapped to its corresponding prediction. Differently from the pipeline, here every token has a prediction as we didn't remove the "0"th class, which means that no particular entity was found on that token.

In [ ]:
outputs = model(**inputs).logits
predictions = torch.argmax(outputs, dim=2)

Zip together each token with its prediction and print it. We can use the model.config.id2label property in order to recover the class name corresponding to the class number

In [ ]:
for token, prediction in zip(tokens, predictions[0].numpy()):
    print((token, model.config.id2label[prediction]))

('[CLS]', 'O')
('Hu', 'I-ORG')
('##gging', 'I-ORG')
('Face', 'I-ORG')
('Inc', 'I-ORG')
('.', 'O')
('is', 'O')
('a', 'O')
('company', 'O')
('based', 'O')
('in', 'O')
('New', 'I-LOC')
('York', 'I-LOC')
('City', 'I-LOC')
('.', 'O')
('Its', 'O')
('headquarters', 'O')
('are', 'O')
('in', 'O')
('D', 'I-LOC')
('##UM', 'I-LOC')
('##BO', 'I-LOC')
(',', 'O')
('therefore', 'O')
('very', 'O')
('close', 'O')
('to', 'O')
('the', 'O')
('Manhattan', 'I-LOC')
('Bridge', 'I-LOC')
('.', 'O')
('[SEP]', 'O')

### TensorFlow

In [ ]:
from transformers import TFAutoModelForTokenClassification, AutoTokenizer
import tensorflow as tf

model = TFAutoModelForTokenClassification.from_pretrained("dbmdz/bert-large-cased-finetuned-conll03-english")
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

All PyTorch model weights were used when initializing TFBertForTokenClassification.

All the weights of TFBertForTokenClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForTokenClassification for predictions without further training.

In [ ]:
sequence = (
    "Hugging Face Inc. is a company based in New York City. Its headquarters are in DUMBO, "
    "therefore very close to the Manhattan Bridge."
)

In [ ]:
inputs = tokenizer(sequence, return_tensors="tf")

In [ ]:
tokens = inputs.tokens()

In [ ]:
outputs = model(**inputs)[0]
predictions = tf.argmax(outputs, axis=2)

In [ ]:
for token, prediction in zip(tokens, predictions[0].numpy()):
    print((token, model.config.id2label[prediction]))

('[CLS]', 'O')
('Hu', 'I-ORG')
('##gging', 'I-ORG')
('Face', 'I-ORG')
('Inc', 'I-ORG')
('.', 'O')
('is', 'O')
('a', 'O')
('company', 'O')
('based', 'O')
('in', 'O')
('New', 'I-LOC')
('York', 'I-LOC')
('City', 'I-LOC')
('.', 'O')
('Its', 'O')
('headquarters', 'O')
('are', 'O')
('in', 'O')
('D', 'I-LOC')
('##UM', 'I-LOC')
('##BO', 'I-LOC')
(',', 'O')
('therefore', 'O')
('very', 'O')
('close', 'O')
('to', 'O')
('the', 'O')
('Manhattan', 'I-LOC')
('Bridge', 'I-LOC')
('.', 'O')
('[SEP]', 'O')

## Summarization

Summarization is the task of summarizing a document or an article into a shorter text. An example of a summarization dataset is the CNN / Daily Mail dataset, which consists of long news articles and was
created for the task of summarization. If you would like to fine-tune a model on a summarization task, various
approaches are described in this [document](https://github.com/huggingface/transformers/tree/main/examples/pytorch/summarization/README.md).

Here is an example of using the pipelines to do summarization. It leverages a Bart model that was fine-tuned on the CNN
/ Daily Mail data set.

In [ ]:
from transformers import pipeline

summarizer = pipeline("summarization")

ARTICLE = """ New York (CNN)When Liana Barrientos was 23 years old, she got married in Westchester County, New York.
A year later, she got married again in Westchester County, but to a different man and without divorcing her first husband.
Only 18 days after that marriage, she got hitched yet again. Then, Barrientos declared "I do" five more times, sometimes only within two weeks of each other.
In 2010, she married once more, this time in the Bronx. In an application for a marriage license, she stated it was her "first and only" marriage.
Barrientos, now 39, is facing two criminal counts of "offering a false instrument for filing in the first degree," referring to her false statements on the
2010 marriage license application, according to court documents.
Prosecutors said the marriages were part of an immigration scam.
On Friday, she pleaded not guilty at State Supreme Court in the Bronx, according to her attorney, Christopher Wright, who declined to comment further.
After leaving court, Barrientos was arrested and charged with theft of service and criminal trespass for allegedly sneaking into the New York subway through an emergency exit, said Detective
Annette Markowski, a police spokeswoman. In total, Barrientos has been married 10 times, with nine of her marriages occurring between 1999 and 2002.
All occurred either in Westchester County, Long Island, New Jersey or the Bronx. She is believed to still be married to four men, and at one time, she was married to eight men at once, prosecutors say.
Prosecutors said the immigration scam involved some of her husbands, who filed for permanent residence status shortly after the marriages.
Any divorces happened only after such filings were approved. It was unclear whether any of the men will be prosecuted.
The case was referred to the Bronx District Attorney\'s Office by Immigration and Customs Enforcement and the Department of Homeland Security\'s
Investigation Division. Seven of the men are from so-called "red-flagged" countries, including Egypt, Turkey, Georgia, Pakistan and Mali.
Her eighth husband, Rashid Rajput, was deported in 2006 to his native Pakistan after an investigation by the Joint Terrorism Task Force.
If convicted, Barrientos faces up to four years in prison.  Her next court appearance is scheduled for May 18.
"""

No model was supplied, defaulted to sshleifer/distilbart-cnn-12-6 and revision a4f8f3e (https://huggingface.co/sshleifer/distilbart-cnn-12-6).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/1.80k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.22G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.22G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

Device set to use cuda:0

Because the summarization pipeline depends on the `PreTrainedModel.generate()` method, we can override the default
arguments of `PreTrainedModel.generate()` directly in the pipeline for `max_length` and `min_length` as shown
below. This outputs the following summary:

In [ ]:
print(summarizer(ARTICLE, max_length=130, min_length=30, do_sample=False))

[{'summary_text': ' Liana Barrientos, 39, is charged with two counts of "offering a false instrument for filing in the first degree" In total, she has been married 10 times, with nine of her marriages occurring between 1999 and 2002 . At one time, she was married to eight men at once, prosecutors say .'}]

Here is an example of doing summarization using a model and a tokenizer. In this example we use Google's T5 model. Even though it was pre-trained only on a multi-task mixed dataset (including
CNN / Daily Mail), it yields very good results.

### PyTorch

Instantiate a tokenizer and a model from the checkpoint name. Summarization is usually done using an encoder-decoder model, such as Bart or T5.

In [ ]:
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

model = AutoModelForSeq2SeqLM.from_pretrained("t5-base")
tokenizer = AutoTokenizer.from_pretrained("t5-base")

config.json:   0%|          | 0.00/1.21k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/892M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

We already defined the article to summarize, so we only have to add the T5 specific prefix "summarize: ".

In [ ]:
# T5 uses a max_length of 512 so we cut the article to 512 tokens.
inputs = tokenizer("summarize: " + ARTICLE, return_tensors="pt", max_length=512, truncation=True)

Use the PreTrainedModel.generate() method to generate the summary. The `num_beams` argument simply sets the number of options from which to sample when generating the summary (see [Beam Search](https://en.wikipedia.org/wiki/Beam_search#Uses))

In [ ]:
outputs = model.generate(
    inputs["input_ids"], max_length=150, min_length=40, length_penalty=2.0, num_beams=4, early_stopping=True
)

print(tokenizer.decode(outputs[0], skip_special_tokens=True))

prosecutors say the marriages were part of an immigration scam . if convicted, barrientos faces two criminal counts of "offering a false instrument for filing in the first degree" she has been married 10 times, nine of them between 1999 and 2002 .

### TensorFlow

In [ ]:
from transformers import TFAutoModelForSeq2SeqLM, AutoTokenizer

model = TFAutoModelForSeq2SeqLM.from_pretrained("t5-base")
tokenizer = AutoTokenizer.from_pretrained("t5-base")

All PyTorch model weights were used when initializing TFT5ForConditionalGeneration.

All the weights of TFT5ForConditionalGeneration were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFT5ForConditionalGeneration for predictions without further training.

In [ ]:
# T5 uses a max_length of 512 so we cut the article to 512 tokens.
inputs = tokenizer("summarize: " + ARTICLE, return_tensors="tf", max_length=512)

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.

In [ ]:
outputs = model.generate(
    inputs["input_ids"], max_length=150, min_length=40, length_penalty=2.0, num_beams=4, early_stopping=True
)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

prosecutors say the marriages were part of an immigration scam . if convicted, barrientos faces two criminal counts of "offering a false instrument for filing in the first degree" she has been married 10 times, nine of them between 1999 and 2002 .

## Translation

Translation is the task of translating a text from one language to another.

An example of a translation dataset is the WMT English to German dataset, which has sentences in English as the input
data and the corresponding sentences in German as the target data. If you would like to fine-tune a model on a
translation task, various approaches are described in this [document](https://github.com/huggingface/transformers/tree/main/examples/pytorch/translation/README.md).

Here is an example of using the pipelines to do translation. It leverages a T5 model that was only pre-trained on a
multi-task mixture dataset (including WMT), yet, yielding impressive translation results. We specify `"translation_en_to_de"` to make sure we load the model specialized in translating from English to German. Many translation tasks have default fine-tuned models that can be accessed by specifying `"translation_xx_to_yy"` where "xx" and "yy" are the [ISO 639 two letter codes](https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes) of the source and target languages, respectivelly.

In [ ]:
from transformers import pipeline

translator = pipeline("translation_en_to_de")
print(translator("Hugging Face is a technology company based in New York and Paris", max_length=40))

No model was supplied, defaulted to google-t5/t5-base and revision a9723ea (https://huggingface.co/google-t5/t5-base).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/1.21k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/892M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

Device set to use cuda:0

[{'translation_text': 'Hugging Face ist ein Technologieunternehmen mit Sitz in New York und Paris.'}]

Because the translation pipeline depends on the `PreTrainedModel.generate()` method, we can override the default
arguments of `PreTrainedModel.generate()` directly in the pipeline as is shown for `max_length` above.

Here is an example of doing translation using a model and a tokenizer.

### PyTorch

Instantiate a tokenizer and a model from the checkpoint name. Translation is usually done using an encoder-decoder model, such as Bart or T5.

In [ ]:
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

model = AutoModelForSeq2SeqLM.from_pretrained("t5-base")
tokenizer = AutoTokenizer.from_pretrained("t5-base")

Add the T5 specific prefix "translate English to German: "

In [ ]:
inputs = tokenizer(
    "translate English to German: Hugging Face is a technology company based in New York and Paris",
    return_tensors="pt",
)

Use the `PreTrainedModel.generate()` method to perform the translation.

In [ ]:
outputs = model.generate(inputs["input_ids"], max_length=40, num_beams=4, early_stopping=True)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

Hugging Face ist ein Technologieunternehmen mit Sitz in New York und Paris.

### TensorFlow

In [ ]:
from transformers import TFAutoModelForSeq2SeqLM, AutoTokenizer

model = TFAutoModelForSeq2SeqLM.from_pretrained("t5-base")
tokenizer = AutoTokenizer.from_pretrained("t5-base")

All PyTorch model weights were used when initializing TFT5ForConditionalGeneration.

All the weights of TFT5ForConditionalGeneration were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFT5ForConditionalGeneration for predictions without further training.

In [ ]:
inputs = tokenizer(
    "translate English to German: Hugging Face is a technology company based in New York and Paris",
    return_tensors="tf",
)

In [ ]:
outputs = model.generate(inputs["input_ids"], max_length=40, num_beams=4, early_stopping=True)

print(tokenizer.decode(outputs[0], skip_special_tokens=True))

Hugging Face ist ein Technologieunternehmen mit Sitz in New York und Paris.

We get the same translation as with the pipeline example.

---

**The following examples will only include the PyTorch implementations as TensorFlow is incompatible with the Python based feature extractors provided by HuggingFace**

## Audio classification

Audio classification assigns a class to an audio signal. The Keyword Spotting dataset from the [SUPERB](https://huggingface.co/datasets/superb) benchmark is an example dataset that can be used for audio classification fine-tuning. This dataset contains ten classes of keywords for classification.
The following examples demonstrate how to use a [pipeline()](https://huggingface.co/docs/transformers/main/en/main_classes/pipelines#transformers.pipeline) and a model and tokenizer for audio classification inference:

In [ ]:
from transformers import pipeline
from datasets import load_dataset
import torch
import soundfile as sf

# Set random seed for reproducibility
torch.manual_seed(42)

# Load dataset
dataset = load_dataset("hf-internal-testing/librispeech_asr_demo", "clean", split="validation", trust_remote_code=True)

# Sort dataset and get the first audio file
dataset = dataset.sort("id")
audio_data = dataset[0]["audio"]["array"]
sample_rate = dataset[0]["audio"]["sampling_rate"]

# Save the audio file as WAV
audio_filename = "saved_audio.wav"
sf.write(audio_filename, audio_data, sample_rate)

print(f"Audio file saved as: {audio_filename}")

librispeech_asr_demo.py:   0%|          | 0.00/5.17k [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Audio file saved as: saved_audio.wav

In [ ]:
from transformers import pipeline
from datasets import load_dataset
import torch

torch.manual_seed(42)
dataset = load_dataset("hf-internal-testing/librispeech_asr_demo", "clean", split="validation", trust_remote_code=True)
dataset = dataset.sort("id")
audio_file = dataset[0]["audio"]["path"]

audio_classifier = pipeline(
    task="audio-classification", model="ehcalabres/wav2vec2-lg-xlsr-en-speech-emotion-recognition"
)

librispeech_asr_demo.py:   0%|          | 0.00/5.17k [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

Generating validation split: 0 examples [00:00, ? examples/s]

config.json:   0%|          | 0.00/2.28k [00:00<?, ?B/s]

/usr/local/lib/python3.11/dist-packages/transformers/configuration_utils.py:310: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(

model.safetensors:   0%|          | 0.00/1.27G [00:00<?, ?B/s]

Some weights of the model checkpoint at ehcalabres/wav2vec2-lg-xlsr-en-speech-emotion-recognition were not used when initializing Wav2Vec2ForSequenceClassification: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.output.bias', 'classifier.output.weight']
- This IS expected if you are initializing Wav2Vec2ForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Wav2Vec2ForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of Wav2Vec2ForSequenceClassification were not initialized from the model checkpoint at ehcalabres/wav2vec2-lg-xlsr-en-speech-emotion-recognition and are newly initialized: ['classifier.bias', 'classifier.weight', 'projector.bias', 'projector.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

preprocessor_config.json:   0%|          | 0.00/214 [00:00<?, ?B/s]

Device set to use cuda:0

In [ ]:
predictions = audio_classifier(audio_file)
predictions = [{"score": round(pred["score"], 4), "label": pred["label"]} for pred in predictions]
predictions

[{'score': 0.1315, 'label': 'fearful'},
 {'score': 0.1265, 'label': 'disgust'},
 {'score': 0.1262, 'label': 'happy'},
 {'score': 0.1252, 'label': 'angry'},
 {'score': 0.1238, 'label': 'sad'},
 {'score': 0.1227, 'label': 'surprised'},
 {'score': 0.1225, 'label': 'neutral'},
 {'score': 0.1216, 'label': 'calm'}]

In [ ]:
from transformers import pipeline
import torch

# Set seed for reproducibility
torch.manual_seed(42)

# Load pre-trained audio classification model
audio_classifier = pipeline(
    task="audio-classification",
    model="ehcalabres/wav2vec2-lg-xlsr-en-speech-emotion-recognition"
)

# Path to the uploaded audio file
audio_file = "trum_zelensky.wav"

# Perform classification
predictions = audio_classifier(audio_file)

# Format results
predictions = [{"score": round(pred["score"], 4), "label": pred["label"]} for pred in predictions]

# Display results
print(predictions)

/usr/local/lib/python3.11/dist-packages/transformers/configuration_utils.py:315: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
Some weights of the model checkpoint at ehcalabres/wav2vec2-lg-xlsr-en-speech-emotion-recognition were not used when initializing Wav2Vec2ForSequenceClassification: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.output.bias', 'classifier.output.weight']
- This IS expected if you are initializing Wav2Vec2ForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Wav2Vec2ForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of Wav2Vec2ForSequenceClassification were not initialized from the model checkpoint at ehcalabres/wav2vec2-lg-xlsr-en-speech-emotion-recognition and are newly initialized: ['classifier.bias', 'classifier.weight', 'projector.bias', 'projector.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Device set to use cuda:0

FileNotFoundError: [Errno 2] No such file or directory: 'trum_zelensky.wav'

### PyTorch

Instantiate a feature extractor and a model from the checkpoint name.

In [ ]:
from transformers import AutoFeatureExtractor, AutoModelForAudioClassification
from datasets import load_dataset
import torch

dataset = load_dataset("hf-internal-testing/librispeech_asr_demo", "clean", split="validation")
dataset = dataset.sort("id")
sampling_rate = dataset.features["audio"].sampling_rate

feature_extractor = AutoFeatureExtractor.from_pretrained("superb/wav2vec2-base-superb-ks")
model = AutoModelForAudioClassification.from_pretrained("superb/wav2vec2-base-superb-ks")

/usr/local/lib/python3.11/dist-packages/transformers/configuration_utils.py:312: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(

Process the audio signal to be classified with a feature extractor.

In [ ]:
inputs = feature_extractor(dataset[0]["audio"]["array"], sampling_rate=sampling_rate, return_tensors="pt")

Pass the input through the model and take the argmax to retrieve the most likely class.

In [ ]:
with torch.no_grad():
    logits = model(**inputs).logits

predicted_class_ids = torch.argmax(logits, dim=-1).item()

Convert the class id to a class name with id2label to return an interpretable result.

In [ ]:
predicted_label = model.config.id2label[predicted_class_ids]
predicted_label

'_unknown_'

## Automatic speech recognition

Automatic speech recognition transcribes an audio signal to text. The [Common Voice](https://huggingface.co/datasets/common_voice) dataset is an example dataset that can be used for automatic speech recognition fine-tuning. It contains an audio file of a speaker and the corresponding sentence.

The following examples demonstrate how to use a [pipeline()](https://huggingface.co/docs/transformers/main/en/main_classes/pipelines#transformers.pipeline) and a model and tokenizer for automatic speech recognition inference:

In [ ]:
from transformers import pipeline
from datasets import load_dataset

dataset = load_dataset("hf-internal-testing/librispeech_asr_demo", "clean", split="validation")
dataset = dataset.sort("id")
audio_file = dataset[0]["audio"]["path"]

speech_recognizer = pipeline(task="automatic-speech-recognition", model="facebook/wav2vec2-base-960h")

config.json:   0%|          | 0.00/1.60k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/378M [00:00<?, ?B/s]

Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

tokenizer_config.json:   0%|          | 0.00/163 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/291 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/85.0 [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/159 [00:00<?, ?B/s]

Device set to use cpu

In [ ]:
speech_recognizer(audio_file)

{'text': 'MISTER QUILTER IS THE APOSTLE OF THE MIDDLE CLASSES AND WE ARE GLAD TO WELCOME HIS GOSPEL'}

### PyTorch

Instantiate a processor (which regroups a feature extractor for input processing and a tokenizer for decoding) and a model from the checkpoint name.

In [ ]:
from transformers import AutoProcessor, AutoModelForCTC
from datasets import load_dataset
import torch

dataset = load_dataset("hf-internal-testing/librispeech_asr_demo", "clean", split="validation")
dataset = dataset.sort("id")
sampling_rate = dataset.features["audio"].sampling_rate

processor = AutoProcessor.from_pretrained("facebook/wav2vec2-base-960h")
model = AutoModelForCTC.from_pretrained("facebook/wav2vec2-base-960h")

Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Process the audio signal and text with a processor.

In [ ]:
inputs = processor(dataset[0]["audio"]["array"], sampling_rate=sampling_rate, return_tensors="pt")

Pass the input through the model and take the argmax to retrieve the predicted text.

In [ ]:
with torch.no_grad():
    logits = model(**inputs).logits
predicted_ids = torch.argmax(logits, dim=-1)

Decode the text with a tokenizer to obtain the transcription.

In [ ]:
transcription = processor.batch_decode(predicted_ids)
transcription[0]

'MISTER QUILTER IS THE APOSTLE OF THE MIDDLE CLASSES AND WE ARE GLAD TO WELCOME HIS GOSPEL'

## Image classification

Like text and audio classification, image classification assigns a class to an image. The [CIFAR-100](https://huggingface.co/datasets/cifar100) dataset is an example dataset that can be used for image classification fine-tuning. It contains an image and the corresponding class.

The following examples demonstrate how to use a [pipeline()](https://huggingface.co/docs/transformers/main/en/main_classes/pipelines#transformers.pipeline) and a model and tokenizer for image classification inference:

In [ ]:
from transformers import pipeline

vision_classifier = pipeline(task="image-classification")
result = vision_classifier(
    images="https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/pipeline-cat-chonk.jpeg"
)
print("\n".join([f"Class {d['label']} with score {round(d['score'], 4)}" for d in result]))

No model was supplied, defaulted to google/vit-base-patch16-224 and revision 3f49326 (https://huggingface.co/google/vit-base-patch16-224).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/69.7k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/346M [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/160 [00:00<?, ?B/s]

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.
Device set to use cpu

Class lynx, catamount with score 0.4335
Class cougar, puma, catamount, mountain lion, painter, panther, Felis concolor with score 0.0348
Class snow leopard, ounce, Panthera uncia with score 0.0324
Class Egyptian cat with score 0.0239
Class tiger cat with score 0.0229

### PyTorch

Instantiate an image processor and a model from the checkpoint name.

In [ ]:
from transformers import AutoImageProcessor, AutoModelForImageClassification
import torch
from datasets import load_dataset

dataset = load_dataset("huggingface/cats-image", trust_remote_code=True)
image = dataset["test"]["image"][0]

feature_extractor = AutoImageProcessor.from_pretrained("google/vit-base-patch16-224")
model = AutoModelForImageClassification.from_pretrained("google/vit-base-patch16-224")

cats-image.py:   0%|          | 0.00/2.56k [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/173k [00:00<?, ?B/s]

Generating test split: 0 examples [00:00, ? examples/s]

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.

Process the image to be classified with an image processor.

In [ ]:
inputs = feature_extractor(image, return_tensors="pt")

Pass the input through the model and take the argmax to retrieve the predicted class.

In [ ]:
with torch.no_grad():
    logits = model(**inputs).logits

predicted_label = logits.argmax(-1).item()

Convert the class id to a class name with id2label to return an interpretable result.

In [ ]:
print(model.config.id2label[predicted_label])

Egyptian cat

## Acknowledgement

This class was adapted from HugginfFace's "notebooks" repository of examples, which you can find [here](https://github.com/huggingface/notebooks/tree/main)